;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_stderr
	.import		_fprintf
	.import		_exit
	.export		__afailed

.segment	"RODATA"

L0004:
	.byte	$41,$53,$53,$45,$52,$54,$49,$4F,$4E,$20,$46,$41,$49,$4C,$45,$44
	.byte	$20,$49,$4E,$20,$25,$73,$28,$25,$75,$29,$9B,$00

; ---------------------------------------------------------------
; void __near__ _afailed (__near__ unsigned char*, unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	__afailed: near

.segment	"CODE"

	jsr     decsp4
	lda     _stderr
	ldy     #$02
	sta     (sp),y
	iny
	lda     _stderr+1
	sta     (sp),y
	lda     #<(L0004)
	ldy     #$00
	sta     (sp),y
	iny
	lda     #>(L0004)
	sta     (sp),y
	ldy     #$09
	jsr     pushwysp
	ldy     #$09
	jsr     pushwysp
	ldy     #$08
	jsr     _fprintf
	ldx     #$00
	lda     #$02
	jsr     _exit
	jmp     incsp4

.endproc

