;
; File generated by co65 v 2.14.0 using model `cc65-module'
;
.fopt		compiler,"co65 v 2.14.0"
.case		on
.debuginfo	off
.export		_atrxmj8_joy

;
; CODE SEGMENT
;
.segment	"CODE"
_atrxmj8_joy:
	.byte	$6A
	.byte	$6F
	.byte	$79
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$08
	.byte	$10
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.word	_atrxmj8_joy+24
	.word	_atrxmj8_joy+43
	.word	_atrxmj8_joy+44
	.word	_atrxmj8_joy+49
	.byte	$00
	.byte	$00
	.byte	$A9
	.byte	$30
	.byte	$8D
	.byte	$02
	.byte	$D3
	.byte	$A9
	.byte	$F0
	.byte	$8D
	.byte	$00
	.byte	$D3
	.byte	$A9
	.byte	$34
	.byte	$8D
	.byte	$02
	.byte	$D3
	.byte	$A9
	.byte	$00
	.byte	$A2
	.byte	$00
	.byte	$60
	.byte	$A9
	.byte	$08
	.byte	$A2
	.byte	$00
	.byte	$60
	.byte	$0A
	.byte	$0A
	.byte	$0A
	.byte	$0A
	.byte	$8D
	.byte	$00
	.byte	$D3
	.byte	$AD
	.byte	$00
	.byte	$D3
	.byte	$29
	.byte	$0F
	.byte	$0A
	.byte	$0D
	.byte	$10
	.byte	$D0
	.byte	$49
	.byte	$1F
	.byte	$A2
	.byte	$00
	.byte	$60

;
; DATA SEGMENT
;
.segment	"DATA"
DATA:

;
; BSS SEGMENT
;
.segment	"BSS"
BSS:
	.res	0

;
; ZEROPAGE SEGMENT
;
.import	__ZP_START__		; Linker generated symbol
ZEROPAGE = __ZP_START__

.end
