;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_stdin
	.import		_fgetc
	.export		_getchar

; ---------------------------------------------------------------
; int __near__ getchar (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_getchar: near

.segment	"CODE"

	lda     _stdin
	ldx     _stdin+1
	jmp     _fgetc

.endproc

