;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		__ctype
	.import		__seterrno
	.export		_strtol

; ---------------------------------------------------------------
; long __near__ __fastcall__ strtol (__near__ const unsigned char*, __near__ __near__ unsigned char**, int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_strtol: near

.segment	"CODE"

	jsr     pushax
	lda     regbank+4
	ldx     regbank+5
	jsr     pushax
	ldy     #$07
	lda     (sp),y
	sta     regbank+4+1
	dey
	lda     (sp),y
	sta     regbank+4
	jsr     pushl0
	jsr     pusha
	jsr     pusha
	jsr     push0
	jsr     decsp6
	jmp     L000A
L0008:	inc     regbank+4
	bne     L000A
	inc     regbank+4+1
L000A:	ldy     #$00
	lda     (regbank+4),y
	tay
	lda     __ctype,y
	and     #$60
	bne     L0008
	tay
	lda     (regbank+4),y
	cmp     #$2B
	beq     L0022
	cmp     #$2D
	bne     L001C
	lda     #$01
	ldy     #$09
	sta     (sp),y
L0022:	inc     regbank+4
	bne     L001C
	inc     regbank+4+1
L001C:	ldy     #$10
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L00BD
	tay
	lda     (regbank+4),y
	cmp     #$30
	bne     L00BC
	inc     regbank+4
	bne     L002B
	inc     regbank+4+1
L002B:	lda     (regbank+4),y
	cmp     #$78
	beq     L00BA
	cmp     #$58
	bne     L00BB
L00BA:	inc     regbank+4
	bne     L0030
	inc     regbank+4+1
L0030:	ldy     #$10
	tya
	jmp     L00D4
L00BB:	ldy     #$10
	lda     #$08
	sta     (sp),y
	lda     #$00
	iny
	sta     (sp),y
	jmp     L003A
L00BC:	ldy     #$10
	lda     #$0A
L00D4:	sta     (sp),y
	lda     #$00
	iny
	sta     (sp),y
	jmp     L003A
L00BD:	lda     (sp),y
	bne     L003A
	dey
	lda     (sp),y
	cmp     #$10
	bne     L003A
	ldy     #$00
	lda     (regbank+4),y
	cmp     #$30
	bne     L003A
	iny
	lda     (regbank+4),y
	cmp     #$78
	beq     L00C2
	cmp     #$58
	bne     L003A
L00C2:	lda     #$02
	clc
	adc     regbank+4
	sta     regbank+4
	bcc     L003A
	inc     regbank+4+1
L003A:	ldy     #$09
	lda     (sp),y
	beq     L0046
	ldy     #$01
	lda     #$00
	sta     (sp),y
	iny
	sta     (sp),y
	iny
	sta     (sp),y
	lda     #$80
	jmp     L00CF
L0046:	ldy     #$01
	lda     #$FF
	sta     (sp),y
	iny
	sta     (sp),y
	iny
	sta     (sp),y
	lda     #$7F
L00CF:	iny
	sta     (sp),y
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$15
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     axlong
	jsr     tosumodeax
	ldy     #$00
	sta     (sp),y
	ldy     #$04
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$15
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     axlong
	jsr     tosudiveax
	ldy     #$01
	jsr     steaxysp
L0052:	ldy     #$00
	lda     (regbank+4),y
	tay
	lda     __ctype,y
	and     #$04
	beq     L0056
	ldx     #$00
	lda     (regbank+4,x)
	sec
	sbc     #$30
	jmp     L00D3
L0056:	tay
	lda     (regbank+4),y
	tay
	lda     __ctype,y
	and     #$02
	beq     L0067
	ldx     #$00
	lda     (regbank+4,x)
	sec
	sbc     #$37
	jmp     L00D3
L0067:	tay
	lda     (regbank+4),y
	tay
	lda     __ctype,y
	and     #$01
	jeq     L0053
	ldx     #$00
	lda     (regbank+4,x)
	sec
	sbc     #$57
L00D3:	ldy     #$05
	sta     (sp),y
	ldy     #$10
	cmp     (sp),y
	txa
	iny
	sbc     (sp),y
	bcs     L0053
	ldy     #$0D
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$08
	jsr     ldeaxysp
	jsr     tosugteax
	bne     L008E
	ldy     #$0D
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$08
	jsr     ldeaxysp
	jsr     toseqeax
	beq     L008D
	ldy     #$05
	lda     (sp),y
	sec
	ldy     #$00
	sbc     (sp),y
	sta     tmp1
	lda     tmp1
	beq     L008D
	bcc     L008D
L008E:	lda     #$01
	ldy     #$08
	sta     (sp),y
L008D:	ldy     #$08
	lda     (sp),y
	bne     L0095
	ldy     #$0D
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$15
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     axlong
	jsr     tosumuleax
	jsr     pusheax
	ldy     #$09
	ldx     #$00
	lda     (sp),y
	jsr     tosadd0ax
	ldy     #$0A
	jsr     steaxysp
	ldy     #$06
	ldx     #$00
	lda     #$01
	jsr     addeqysp
L0095:	inc     regbank+4
	jne     L0052
	inc     regbank+4+1
	jmp     L0052
L0053:	ldy     #$13
	lda     (sp),y
	dey
	ora     (sp),y
	beq     L00A4
	ldy     #$06
	lda     (sp),y
	iny
	ora     (sp),y
	beq     L009F
	ldy     #$13
	lda     (sp),y
	sta     sreg+1
	dey
	lda     (sp),y
	sta     sreg
	lda     regbank+4
	ldy     #$00
	sta     (sreg),y
	iny
	lda     regbank+4+1
	jmp     L00D1
L009F:	ldy     #$13
	lda     (sp),y
	sta     sreg+1
	dey
	lda     (sp),y
	sta     sreg
	ldy     #$15
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$00
	sta     (sreg),y
	iny
	txa
L00D1:	sta     (sreg),y
L00A4:	ldy     #$08
	lda     (sp),y
	beq     L00AF
	lda     #$0F
	jsr     __seterrno
	ldy     #$09
	lda     (sp),y
	beq     L00AB
	ldx     #$00
	stx     sreg
	lda     #$80
	sta     sreg+1
	txa
	jmp     L00B4
L00AB:	ldx     #$FF
	stx     sreg
	lda     #$7F
	sta     sreg+1
	txa
	jmp     L00B4
L00AF:	iny
	lda     (sp),y
	beq     L00B1
	ldy     #$0D
	jsr     ldeaxysp
	jsr     negeax
	jmp     L00B4
L00B1:	ldy     #$0D
	jsr     ldeaxysp
L00B4:	pha
	ldy     #$0E
	lda     (sp),y
	sta     regbank+4
	iny
	lda     (sp),y
	sta     regbank+5
	pla
	ldy     #$16
	jmp     addysp

.endproc

