;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		__ctype
	.import		__seterrno
	.export		_strtoul

; ---------------------------------------------------------------
; unsigned long __near__ __fastcall__ strtoul (__near__ const unsigned char*, __near__ __near__ unsigned char**, int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_strtoul: near

.segment	"CODE"

	jsr     pushax
	lda     regbank+4
	ldx     regbank+5
	jsr     pushax
	ldy     #$07
	lda     (sp),y
	sta     regbank+4+1
	dey
	lda     (sp),y
	sta     regbank+4
	jsr     pushl0
	jsr     pusha
	jsr     pusha
	jsr     push0
	jsr     decsp6
	jmp     L000A
L0008:	inc     regbank+4
	bne     L000A
	inc     regbank+4+1
L000A:	ldy     #$00
	lda     (regbank+4),y
	tay
	lda     __ctype,y
	and     #$60
	bne     L0008
	tay
	lda     (regbank+4),y
	cmp     #$2B
	beq     L0022
	cmp     #$2D
	bne     L001C
	lda     #$01
	ldy     #$09
	sta     (sp),y
L0022:	inc     regbank+4
	bne     L001C
	inc     regbank+4+1
L001C:	ldy     #$10
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L00AF
	tay
	lda     (regbank+4),y
	cmp     #$30
	bne     L00AE
	inc     regbank+4
	bne     L002B
	inc     regbank+4+1
L002B:	lda     (regbank+4),y
	cmp     #$58
	beq     L00AC
	cmp     #$D8
	bne     L00AD
L00AC:	inc     regbank+4
	bne     L0030
	inc     regbank+4+1
L0030:	ldy     #$10
	tya
	jmp     L00C5
L00AD:	ldy     #$10
	lda     #$08
	sta     (sp),y
	lda     #$00
	iny
	sta     (sp),y
	jmp     L003A
L00AE:	ldy     #$10
	lda     #$0A
L00C5:	sta     (sp),y
	lda     #$00
	iny
	sta     (sp),y
	jmp     L003A
L00AF:	lda     (sp),y
	bne     L003A
	dey
	lda     (sp),y
	cmp     #$10
	bne     L003A
	ldy     #$00
	lda     (regbank+4),y
	cmp     #$30
	bne     L003A
	iny
	lda     (regbank+4),y
	cmp     #$58
	beq     L00B4
	cmp     #$D8
	bne     L003A
L00B4:	lda     #$02
	clc
	adc     regbank+4
	sta     regbank+4
	bcc     L003A
	inc     regbank+4+1
L003A:	ldx     #$FF
	stx     sreg
	stx     sreg+1
	txa
	jsr     pusheax
	ldy     #$15
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     axlong
	jsr     tosumodeax
	ldy     #$00
	sta     (sp),y
	ldx     #$FF
	stx     sreg
	stx     sreg+1
	txa
	jsr     pusheax
	ldy     #$15
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     axlong
	jsr     tosudiveax
	ldy     #$01
	jsr     steaxysp
L004A:	ldy     #$00
	lda     (regbank+4),y
	tay
	lda     __ctype,y
	and     #$04
	beq     L004E
	ldx     #$00
	lda     (regbank+4,x)
	sec
	sbc     #$30
	jmp     L00C4
L004E:	tay
	lda     (regbank+4),y
	tay
	lda     __ctype,y
	and     #$02
	beq     L005F
	ldx     #$00
	lda     (regbank+4,x)
	sec
	sbc     #$B7
	jmp     L00C4
L005F:	tay
	lda     (regbank+4),y
	tay
	lda     __ctype,y
	and     #$01
	jeq     L004B
	ldx     #$00
	lda     (regbank+4,x)
	sec
	sbc     #$37
L00C4:	ldy     #$05
	sta     (sp),y
	ldy     #$10
	cmp     (sp),y
	txa
	iny
	sbc     (sp),y
	bcs     L004B
	ldy     #$0D
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$08
	jsr     ldeaxysp
	jsr     tosugteax
	bne     L0086
	ldy     #$0D
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$08
	jsr     ldeaxysp
	jsr     toseqeax
	beq     L0085
	ldy     #$05
	lda     (sp),y
	sec
	ldy     #$00
	sbc     (sp),y
	sta     tmp1
	lda     tmp1
	beq     L0085
	bcc     L0085
L0086:	lda     #$01
	ldy     #$08
	sta     (sp),y
L0085:	ldy     #$08
	lda     (sp),y
	bne     L008D
	ldy     #$0D
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$15
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     axlong
	jsr     tosumuleax
	jsr     pusheax
	ldy     #$09
	ldx     #$00
	lda     (sp),y
	jsr     tosadd0ax
	ldy     #$0A
	jsr     steaxysp
	ldy     #$06
	ldx     #$00
	lda     #$01
	jsr     addeqysp
L008D:	inc     regbank+4
	jne     L004A
	inc     regbank+4+1
	jmp     L004A
L004B:	ldy     #$13
	lda     (sp),y
	dey
	ora     (sp),y
	beq     L009C
	ldy     #$06
	lda     (sp),y
	iny
	ora     (sp),y
	beq     L0097
	ldy     #$13
	lda     (sp),y
	sta     sreg+1
	dey
	lda     (sp),y
	sta     sreg
	lda     regbank+4
	ldy     #$00
	sta     (sreg),y
	iny
	lda     regbank+4+1
	jmp     L00C2
L0097:	ldy     #$13
	lda     (sp),y
	sta     sreg+1
	dey
	lda     (sp),y
	sta     sreg
	ldy     #$15
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$00
	sta     (sreg),y
	iny
	txa
L00C2:	sta     (sreg),y
L009C:	ldy     #$08
	lda     (sp),y
	beq     L009F
	lda     #$0F
	jsr     __seterrno
	ldx     #$FF
	stx     sreg
	stx     sreg+1
	txa
	jmp     L00A7
L009F:	iny
	lda     (sp),y
	beq     L00A4
	ldy     #$0D
	jsr     ldeaxysp
	jsr     negeax
	jmp     L00A7
L00A4:	ldy     #$0D
	jsr     ldeaxysp
L00A7:	pha
	ldy     #$0E
	lda     (sp),y
	sta     regbank+4
	iny
	lda     (sp),y
	sta     regbank+5
	pla
	ldy     #$16
	jmp     addysp

.endproc

