;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_stderr
	.import		_fputs
	.export		_abort
	.import		_exit
	.import		_raise

.segment	"RODATA"

L0005:
	.byte	$C1,$C2,$CE,$CF,$D2,$CD,$C1,$CC,$20,$D0,$D2,$CF,$C7,$D2,$C1,$CD
	.byte	$20,$D4,$C5,$D2,$CD,$C9,$CE,$C1,$D4,$C9,$CF,$CE,$0D,$00

; ---------------------------------------------------------------
; void __near__ abort (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_abort: near

.segment	"CODE"

	ldx     #$00
	txa
	jsr     _raise
	lda     #<(L0005)
	ldx     #>(L0005)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	ldx     #$00
	lda     #$03
	jmp     _exit

.endproc

