;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_open
	.import		_close
	.import		_write
	.import		_read
	.import		_pen_adjuster
	.import		_pen_calibrate
	.export		_pen_adjust

.segment	"BSS"

_name:
	.res	2,$00

; ---------------------------------------------------------------
; void __near__ __fastcall__ pen_adjust (__near__ const unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_pen_adjust: near

.segment	"CODE"

	jsr     pushax
	ldy     #$00
	lda     (sp),y
	iny
	ora     (sp),y
	beq     L001D
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     (ptr1),y
	beq     L001D
	iny
	lda     (sp),y
	sta     _name+1
	dey
	lda     (sp),y
	sta     _name
	lda     #<(_adjuster)
	sta     _pen_adjuster
	lda     #>(_adjuster)
	jmp     L002A
L001D:	lda     #<(_pen_calibrate)
	sta     _pen_adjuster
	lda     #>(_pen_calibrate)
L002A:	sta     _pen_adjuster+1
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ __fastcall__ adjuster (__near__ unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_adjuster: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp4
	lda     _name
	ldy     #$02
	sta     (sp),y
	iny
	lda     _name+1
	sta     (sp),y
	lda     #$01
	ldy     #$00
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	ldy     #$04
	jsr     _open
	jsr     pushax
	ldy     #$01
	lda     (sp),y
	tax
	cpx     #$80
	bcc     L0005
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _pen_calibrate
	jsr     decsp4
	lda     _name
	ldy     #$02
	sta     (sp),y
	iny
	lda     _name+1
	sta     (sp),y
	lda     #$92
	ldy     #$00
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	ldy     #$04
	jsr     _open
	jsr     stax0sp
	txa
	bmi     L0015
	jsr     decsp4
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$07
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldx     #$00
	tya
	jsr     _write
	jmp     L002E
L0005:	jsr     decsp4
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$07
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldx     #$00
	tya
	jsr     _read
L002E:	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _close
L0015:	jmp     incsp4

.endproc

