;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_exit
	.import		_strlen
	.import		_clrscr
	.import		_kbhit
	.import		_gotoxy
	.import		_wherex
	.import		_cputc
	.import		_cputcxy
	.import		_cputsxy
	.import		_cgetc
	.import		_cursor
	.import		_revers
	.import		_textcolor
	.import		_bgcolor
	.import		_bordercolor
	.import		_chline
	.import		_chlinexy
	.import		_cvlinexy
	.import		_cclearxy
	.import		_cputhex8
	.import		_cputhex16
	.import		__ctype
	.import		_toupper
	.import		_brk_a
	.import		_brk_x
	.import		_brk_y
	.import		_brk_sr
	.import		_brk_pc
	.import		_DbgDisAsm
	.import		_DbgDisAsmLen
	.import		_DbgIsRAM
	.import		_DbgMemDump
	.import		_DbgSP
	.import		_DbgCS
	.import		_DbgHI
	.export		_DbgBreakCount
	.export		_DbgBreaks
	.import		_DbgGetBreakSlot
	.import		_DbgIsBreak
	.export		_DbgEntry

.segment	"DATA"

_RegText:
	.byte	$01
	.byte	$00
	.addr	L0004
	.byte	$01
	.byte	$01
	.addr	L0008
	.byte	$01
	.byte	$02
	.addr	L000C
	.byte	$01
	.byte	$03
	.addr	L0010
	.byte	$01
	.byte	$04
	.addr	L0014
	.byte	$01
	.byte	$05
	.addr	L0018
	.byte	$01
	.byte	$06
	.addr	L001C
	.byte	$01
	.byte	$07
	.addr	L0020
_HelpText:
	.byte	$01
	.byte	$00
	.addr	L0024
	.byte	$01
	.byte	$01
	.addr	L0028
	.byte	$01
	.byte	$02
	.addr	L002C
	.byte	$01
	.byte	$03
	.addr	L0030
	.byte	$01
	.byte	$04
	.addr	L0034
	.byte	$01
	.byte	$05
	.addr	L0038
	.byte	$01
	.byte	$06
	.addr	L003C
	.byte	$01
	.byte	$07
	.addr	L0040
	.byte	$01
	.byte	$08
	.addr	L0044
	.byte	$01
	.byte	$09
	.addr	L0048
	.byte	$01
	.byte	$0A
	.addr	L004C
	.byte	$01
	.byte	$0B
	.addr	L0050
	.byte	$01
	.byte	$0C
	.addr	L0054
	.byte	$01
	.byte	$0D
	.addr	L0058
	.byte	$01
	.byte	$0E
	.addr	L005C
	.byte	$01
	.byte	$0F
	.addr	L0060
	.byte	$01
	.byte	$10
	.addr	L0064
	.byte	$01
	.byte	$11
	.addr	L0068
_AsmFrame:
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$00
	.byte	$00
	.byte	$1E
	.byte	$0F
	.byte	$1D
	.byte	$0E
	.byte	$01
	.addr	_AsmHandler
	.byte	$00
	.word	$0000
_RegFrame:
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$1E
	.byte	$00
	.byte	$27
	.byte	$09
	.byte	$08
	.byte	$08
	.byte	$01
	.addr	_RegHandler
	.byte	$08
	.addr	_RegText
_StackFrame:
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$1E
	.byte	$09
	.byte	$27
	.byte	$0F
	.byte	$08
	.byte	$05
	.byte	$01
	.addr	_StackHandler
	.byte	$00
	.word	$0000
_CStackFrame:
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$1E
	.byte	$0F
	.byte	$27
	.byte	$18
	.byte	$08
	.byte	$08
	.byte	$01
	.addr	_CStackHandler
	.byte	$00
	.word	$0000
_DumpFrame:
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$00
	.byte	$0F
	.byte	$1E
	.byte	$18
	.byte	$1D
	.byte	$08
	.byte	$01
	.addr	_DumpHandler
	.byte	$00
	.word	$0000
_HelpFrame:
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$00
	.byte	$00
	.byte	$27
	.byte	$18
	.byte	$26
	.byte	$17
	.byte	$00
	.addr	_HelpHandler
	.byte	$12
	.addr	_HelpText
_Frames:
	.addr	_AsmFrame
	.addr	_RegFrame
	.addr	_StackFrame
	.addr	_CStackFrame
	.addr	_DumpFrame
	.addr	_HelpFrame
_ActiveFrame:
	.word	$FFFF
_ActivePrompt:
	.word	$0000
_DbgBreakCount:
	.byte	$00

.segment	"RODATA"

L002C:
	.byte	$46,$33,$2C,$20,$75,$20,$20,$20,$20,$20,$52,$75,$6E,$20,$75,$6E
	.byte	$74,$69,$6C,$20,$73,$75,$62,$72,$6F,$75,$74,$69,$6E,$65,$20,$72
	.byte	$65,$74,$75,$72,$6E,$73,$00
L0238:
	.byte	$43,$61,$6E,$6E,$6F,$74,$20,$73,$65,$74,$20,$62,$72,$65,$61,$6B
	.byte	$70,$6F,$69,$6E,$74,$20,$2D,$20,$70,$72,$65,$73,$73,$20,$61,$20
	.byte	$6B,$65,$79,$00
L024C:
	.byte	$54,$6F,$6F,$20,$6D,$61,$6E,$79,$20,$62,$72,$65,$61,$6B,$70,$6F
	.byte	$69,$6E,$74,$73,$20,$2D,$20,$70,$72,$65,$73,$73,$20,$61,$20,$6B
	.byte	$65,$79,$00
L0068:
	.byte	$73,$20,$20,$20,$20,$20,$20,$20,$20,$20,$53,$6B,$69,$70,$20,$6E
	.byte	$65,$78,$74,$20,$69,$6E,$73,$74,$72,$75,$63,$74,$69,$6F,$6E,$00
L003C:
	.byte	$31,$2D,$35,$20,$20,$20,$20,$20,$20,$20,$53,$65,$6C,$65,$63,$74
	.byte	$20,$61,$63,$74,$69,$76,$65,$20,$77,$69,$6E,$64,$6F,$77,$00
L005C:
	.byte	$70,$20,$20,$20,$20,$20,$20,$20,$20,$20,$55,$73,$65,$20,$61,$73
	.byte	$20,$6E,$65,$77,$20,$50,$43,$20,$76,$61,$6C,$75,$65,$00
L0054:
	.byte	$66,$20,$20,$20,$20,$20,$20,$20,$20,$20,$46,$6F,$6C,$6C,$6F,$77
	.byte	$20,$69,$6E,$73,$74,$72,$75,$63,$74,$69,$6F,$6E,$00
L0028:
	.byte	$46,$32,$2C,$20,$74,$20,$20,$20,$20,$20,$54,$6F,$67,$67,$6C,$65
	.byte	$20,$62,$72,$65,$61,$6B,$70,$6F,$69,$6E,$74,$00
L0233:
	.byte	$49,$6E,$76,$61,$6C,$69,$64,$20,$69,$6E,$70,$75,$74,$20,$2D,$20
	.byte	$70,$72,$65,$73,$73,$20,$61,$20,$6B,$65,$79,$00
L0171:
	.byte	$50,$72,$65,$73,$73,$20,$61,$6E,$79,$20,$6B,$65,$79,$20,$74,$6F
	.byte	$20,$63,$6F,$6E,$74,$69,$6E,$75,$65,$00
L0030:
	.byte	$46,$34,$2C,$20,$68,$20,$20,$20,$20,$20,$52,$75,$6E,$20,$74,$6F
	.byte	$20,$63,$75,$72,$73,$6F,$72,$00
L0064:
	.byte	$72,$20,$20,$20,$20,$20,$20,$20,$20,$20,$52,$65,$64,$72,$61,$77
	.byte	$20,$73,$63,$72,$65,$65,$6E,$00
L004C:
	.byte	$61,$2F,$7A,$20,$20,$20,$20,$20,$20,$20,$4D,$6F,$76,$65,$20,$75
	.byte	$70,$2F,$64,$6F,$77,$6E,$00
L0048:
	.byte	$43,$75,$72,$73,$6F,$72,$20,$20,$20,$20,$4D,$6F,$76,$65,$20,$75
	.byte	$70,$2F,$64,$6F,$77,$6E,$00
L0058:
	.byte	$6F,$20,$20,$20,$20,$20,$20,$20,$20,$20,$47,$6F,$74,$6F,$20,$6F
	.byte	$72,$69,$67,$69,$6E,$00
L0034:
	.byte	$46,$37,$2C,$20,$73,$70,$61,$63,$65,$20,$53,$74,$65,$70,$20,$69
	.byte	$6E,$74,$6F,$00
L0038:
	.byte	$46,$38,$2C,$20,$65,$6E,$74,$65,$72,$20,$53,$74,$65,$70,$20,$6F
	.byte	$76,$65,$72,$00
L0040:
	.byte	$2B,$20,$20,$20,$20,$20,$20,$20,$20,$20,$50,$61,$67,$65,$20,$64
	.byte	$6F,$77,$6E,$00
L0050:
	.byte	$63,$20,$20,$20,$20,$20,$20,$20,$20,$20,$43,$6F,$6E,$74,$69,$6E
	.byte	$75,$65,$00
L0044:
	.byte	$2D,$20,$20,$20,$20,$20,$20,$20,$20,$20,$50,$61,$67,$65,$20,$75
	.byte	$70,$00
L016D:
	.byte	$50,$72,$65,$73,$73,$20,$46,$31,$20,$66,$6F,$72,$20,$68,$65,$6C
	.byte	$70,$00
L0060:
	.byte	$71,$20,$20,$20,$20,$20,$20,$20,$20,$20,$51,$75,$69,$74,$00
L0024:
	.byte	$46,$31,$2C,$20,$3F,$20,$20,$20,$20,$20,$48,$65,$6C,$70,$00
L022D:
	.byte	$47,$6F,$74,$6F,$3A,$20,$00
L0008:
	.byte	$53,$52,$00
L001C:
	.byte	$43,$53,$00
L0020:
	.byte	$48,$49,$00
L0018:
	.byte	$53,$50,$00
L03DD:
	.byte	$2D,$3E,$00
L0004:
	.byte	$50,$43,$00
L0010:
	.byte	$58,$00
L000C:
	.byte	$41,$00
L0014:
	.byte	$59,$00

.segment	"BSS"

_AsmAddr:
	.res	2,$00
_DumpAddr:
	.res	2,$00
_CStackAddr:
	.res	2,$00
_StackAddr:
	.res	1,$00
_PromptColor:
	.res	1,$00
_PromptLength:
	.res	1,$00
_DbgBreaks:
	.res	48,$00

; ---------------------------------------------------------------
; unsigned char __near__ AsmHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AsmHandler: near

.segment	"CODE"

	jsr     decsp3
L031E:	jsr     _UpdateAsm
	jsr     stax0sp
	jsr     _GetKeyUpdate
	ldy     #$02
	sta     (sp),y
	cmp     #$2B
	beq     L0329
	cmp     #$2D
	beq     L032D
	cmp     #$61
	jeq     L0345
	cmp     #$66
	beq     L0337
	cmp     #$67
	beq     L033A
	cmp     #$6F
	beq     L033E
	cmp     #$70
	beq     L0341
	cmp     #$74
	beq     L0333
	cmp     #$7A
	jeq     L034B
	jmp     L052E
L0329:	dey
	lda     (sp),y
	sta     _AsmAddr+1
	lda     (sp)
	sta     _AsmAddr
	bra     L031E
L032D:	jsr     decsp3
	lda     _AsmAddr
	dey
	sta     (sp),y
	iny
	lda     _AsmAddr+1
	sta     (sp),y
	lda     _AsmFrame+9
	sta     (sp)
	jsr     _AsmBack
	sta     _AsmAddr
	stx     _AsmAddr+1
	bra     L031E
L0333:	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     pushax
	jsr     _DbgToggleUserBreak
	bra     L031E
L0337:	jsr     _AsmFollow
	bra     L031E
L033A:	lda     #<(_AsmAddr)
	ldx     #>(_AsmAddr)
	jsr     pushax
	jsr     _InputGoto
	jmp     L031E
L033E:	jsr     _AsmHome
	jmp     L031E
L0341:	lda     _AsmAddr
	sta     _brk_pc
	lda     _AsmAddr+1
	sta     _brk_pc+1
	jmp     L031E
L0345:	jsr     decsp3
	lda     _AsmAddr
	dey
	sta     (sp),y
	iny
	lda     _AsmAddr+1
	sta     (sp),y
	lda     #$01
	sta     (sp)
	jsr     _AsmBack
	sta     _AsmAddr
	stx     _AsmAddr+1
	jmp     L031E
L034B:	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     _DbgDisAsmLen
	clc
	adc     _AsmAddr
	sta     _AsmAddr
	txa
	adc     _AsmAddr+1
	sta     _AsmAddr+1
	jmp     L031E
L052E:	ldx     #$00
	lda     (sp),y
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ RegHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_RegHandler: near

.segment	"CODE"

	jmp     _GetKeyUpdate

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ StackHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_StackHandler: near

.segment	"CODE"

	jsr     decsp1
	lda     _StackFrame+9
	jsr     pusha
L03A9:	jsr     _GetKeyUpdate
	ldy     #$01
	sta     (sp),y
	cmp     #$2B
	beq     L03B2
	cmp     #$2D
	beq     L03B6
	cmp     #$61
	beq     L03BD
	cmp     #$6F
	beq     L03BA
	cmp     #$7A
	beq     L03C0
	bra     L052F
L03B2:	lda     (sp)
	clc
	adc     _StackAddr
	sta     _StackAddr
	bra     L03B0
L03B6:	lda     (sp)
	eor     #$FF
	sec
	adc     _StackAddr
	sta     _StackAddr
	bra     L03B0
L03BA:	jsr     _StackHome
	bra     L03B0
L03BD:	dec     _StackAddr
	bra     L03B0
L03C0:	inc     _StackAddr
	bra     L03B0
L052F:	ldx     #$00
	lda     (sp),y
	jmp     incsp2
L03B0:	jsr     _UpdateStack
	bra     L03A9

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ CStackHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_CStackHandler: near

.segment	"CODE"

	jsr     decsp1
	lda     _CStackFrame+9
	asl     a
	jsr     pusha
L03E9:	jsr     _GetKeyUpdate
	ldy     #$01
	sta     (sp),y
	cmp     #$2B
	beq     L03F2
	cmp     #$2D
	beq     L03F6
	cmp     #$61
	beq     L03FD
	cmp     #$6F
	beq     L03FA
	cmp     #$7A
	beq     L0402
	bra     L0530
L03F2:	lda     (sp)
	clc
	adc     _CStackAddr
	sta     _CStackAddr
	lda     #$00
	adc     _CStackAddr+1
	sta     _CStackAddr+1
	bra     L03F0
L03F6:	lda     (sp)
	eor     #$FF
	sec
	adc     _CStackAddr
	sta     _CStackAddr
	lda     #$FF
	adc     _CStackAddr+1
	sta     _CStackAddr+1
	bra     L03F0
L03FA:	jsr     _CStackHome
	bra     L03F0
L03FD:	lda     _CStackAddr
	sec
	sbc     #$02
	sta     _CStackAddr
	bcs     L03F0
	dec     _CStackAddr+1
	bra     L03F0
L0402:	lda     #$02
	clc
	adc     _CStackAddr
	sta     _CStackAddr
	bcc     L03F0
	inc     _CStackAddr+1
	bra     L03F0
L0530:	ldx     #$00
	lda     (sp),y
	jmp     incsp2
L03F0:	jsr     _UpdateCStack
	bra     L03E9

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ DumpHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DumpHandler: near

.segment	"CODE"

	jsr     decsp1
	ldx     #$00
	lda     _DumpFrame+9
	jsr     shlax3
	jsr     pushax
L0428:	jsr     _GetKeyUpdate
	ldy     #$02
	sta     (sp),y
	cmp     #$2B
	beq     L0431
	cmp     #$2D
	beq     L0435
	cmp     #$61
	beq     L0440
	cmp     #$67
	beq     L0439
	cmp     #$6F
	beq     L043D
	cmp     #$7A
	beq     L0445
	bra     L0531
L0431:	dey
	lda     (sp),y
	tax
	lda     (sp)
	clc
	adc     _DumpAddr
	sta     _DumpAddr
	txa
	adc     _DumpAddr+1
	sta     _DumpAddr+1
	bra     L042F
L0435:	dey
	lda     (sp),y
	tax
	lda     (sp)
	eor     #$FF
	sec
	adc     _DumpAddr
	sta     _DumpAddr
	txa
	eor     #$FF
	adc     _DumpAddr+1
	sta     _DumpAddr+1
	bra     L042F
L0439:	lda     #<(_DumpAddr)
	ldx     #>(_DumpAddr)
	jsr     pushax
	jsr     _InputGoto
	bra     L042F
L043D:	jsr     _DumpHome
	bra     L042F
L0440:	lda     _DumpAddr
	sec
	sbc     #$08
	sta     _DumpAddr
	bcs     L042F
	dec     _DumpAddr+1
	bra     L042F
L0445:	lda     #$08
	clc
	adc     _DumpAddr
	sta     _DumpAddr
	bcc     L042F
	inc     _DumpAddr+1
	bra     L042F
L0531:	ldx     #$00
	lda     (sp),y
	jmp     incsp3
L042F:	jsr     _UpdateDump
	jmp     L0428

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ HelpHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_HelpHandler: near

.segment	"CODE"

	lda     _ActiveFrame
	ldx     _ActiveFrame+1
	jsr     pushax
	jsr     decsp3
	lda     #$05
	ldy     #$01
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	ina
	sta     (sp)
	jsr     _ActivateFrame
	jsr     _AnyKeyPrompt
	jsr     _cgetc
	lda     (sp)
	jsr     pusha
	jsr     _Redraw
	ldx     #$00
	txa
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ DisplayPrompt (__near__ unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DisplayPrompt: near

.segment	"CODE"

	jsr     decsp1
	lda     #$01
	jsr     _textcolor
	sta     (sp)
	lda     _ActivePrompt
	ora     _ActivePrompt+1
	beq     L0152
	lda     _PromptColor
	jsr     _textcolor
	jsr     decsp2
	lda     #$28
	sec
	sbc     _PromptLength
	lsr     a
	ldy     #$01
	sta     (sp),y
	lda     #$18
	sta     (sp)
	lda     _PromptLength
	jsr     _chlinexy
L0152:	ldy     #$02
	lda     (sp),y
	sta     _ActivePrompt+1
	dey
	lda     (sp),y
	sta     _ActivePrompt
	lda     (sp)
	sta     _PromptColor
	lda     _ActivePrompt
	ldx     _ActivePrompt+1
	jsr     _strlen
	sta     _PromptLength
	lda     #$01
	jsr     _textcolor
	jsr     decsp2
	lda     #$28
	sec
	sbc     _PromptLength
	lsr     a
	ldy     #$01
	sta     (sp),y
	lda     #$18
	sta     (sp)
	lda     _ActivePrompt
	ldx     _ActivePrompt+1
	jsr     _cputsxy
	lda     _PromptColor
	jsr     _textcolor
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ SingleStep (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_SingleStep: near

.segment	"CODE"

	jsr     decsp1
	lda     _brk_pc
	sta     ptr1
	lda     _brk_pc+1
	sta     ptr1+1
	lda     (ptr1)
	cmp     #$10
	beq     L047E
	cmp     #$20
	jeq     L0492
	cmp     #$30
	beq     L047E
	cmp     #$40
	beq     L048D
	cmp     #$4C
	beq     L0468
	cmp     #$50
	beq     L047E
	cmp     #$60
	beq     L048A
	cmp     #$6C
	beq     L046C
	cmp     #$70
	beq     L047E
	cmp     #$90
	beq     L047E
	cmp     #$B0
	beq     L047E
	cmp     #$D0
	beq     L047E
	cmp     #$F0
	beq     L047E
	bra     L0466
L0468:	jsr     _GetArg16
	bra     L0533
L046C:	jsr     _GetArg16
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	bra     L0533
L047E:	lda     _brk_pc
	ldx     _brk_pc+1
	ldy     #$01
	jsr     ldaidx
	sta     (sp)
	lda     (sp)
	beq     L0466
	ldx     #$00
	lda     (sp)
	bpl     L0487
	dex
L0487:	clc
	adc     _brk_pc
	pha
	txa
	adc     _brk_pc+1
	tax
	pla
	clc
	adc     #$02
	bcc     L0488
	inx
L0488:	jsr     pushax
	jsr     _DbgSetTmpBreak
	bra     L0466
L048A:	jsr     _SetRTSBreak
	jmp     incsp2
L048D:	lda     #$01
	jsr     pusha
	jsr     _GetStack16
	bra     L0533
L0492:	ldy     #$01
	lda     (sp),y
	beq     L0466
	jsr     _GetArg16
	bra     L0533
L0466:	lda     _brk_pc
	ldx     _brk_pc+1
	jsr     pushax
	lda     _brk_pc
	ldx     _brk_pc+1
	jsr     _DbgDisAsmLen
	jsr     tosaddax
L0533:	jsr     pushax
	jsr     _DbgSetTmpBreak
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ RedrawStatic (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_RedrawStatic: near

.segment	"CODE"

	lda     #$FF
	sta     _ActiveFrame
	sta     _ActiveFrame+1
	ina
	jsr     _bordercolor
	lda     #$00
	jsr     _bgcolor
	jsr     _clrscr
	lda     #$00
	jsr     _cursor
	lda     #$01
	jsr     _textcolor
	jsr     _DrawFrames
	jsr     _HelpPrompt
	jsr     decsp3
	ldy     #$03
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	sta     (sp)
	jsr     _ActivateFrame
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ Redraw (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Redraw: near

.segment	"CODE"

	lda     (sp)
	jsr     pusha
	jsr     _RedrawStatic
	jsr     _UpdateAsm
	jsr     _UpdateReg
	jsr     _UpdateStack
	jsr     _UpdateCStack
	jsr     _UpdateDump
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ GetKeyUpdate (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_GetKeyUpdate: near

.segment	"BSS"

L04B4:
	.res	1,$00

.segment	"CODE"

	bra     L04B7
L0534:	lda     L04B4
	beq     L04BD
	cmp     #$01
	beq     L04C0
	cmp     #$02
	beq     L04C3
	cmp     #$03
	beq     L04C6
	bra     L0535
L04BD:	jsr     _UpdateAsm
	bra     L0535
L04C0:	jsr     _UpdateStack
	bra     L0535
L04C3:	jsr     _UpdateCStack
	bra     L0535
L04C6:	jsr     _UpdateDump
L0535:	lda     L04B4
	ina
	and     #$03
	sta     L04B4
L04B7:	jsr     _kbhit
	tax
	beq     L0534
	jmp     _cgetc

.endproc

; ---------------------------------------------------------------
; void __near__ DrawFrame (register __near__ struct $anon-struct-0008*, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DrawFrame: near

.segment	"CODE"

	ldy     #$01
	ldx     #$04
	jsr     regswap2
	ldy     #$0B
	jsr     subysp
	ldy     #$0B
	lda     (sp),y
	beq     L00CF
	lda     #$01
	jsr     _textcolor
	sta     (sp)
	lda     #$2B
	ldy     #$07
	sta     (sp),y
	dey
	sta     (sp),y
	dey
	sta     (sp),y
	bra     L0538
L00CF:	ina
	jsr     _textcolor
	sta     (sp)
	lda     (regbank+4)
	ldy     #$07
	sta     (sp),y
	ldy     #$01
	lda     (regbank+4),y
	ldy     #$06
	sta     (sp),y
	ldy     #$02
	lda     (regbank+4),y
	ldy     #$05
	sta     (sp),y
	ldy     #$03
	lda     (regbank+4),y
L0538:	ldy     #$04
	sta     (sp),y
	lda     (regbank+4),y
	dey
	sta     (sp),y
	ldy     #$05
	lda     (regbank+4),y
	ldy     #$02
	sta     (sp),y
	ldy     #$08
	lda     (regbank+4),y
	ldy     #$01
	sta     (sp),y
	jsr     decsp2
	ldy     #$05
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	ldy     #$04
	lda     (sp),y
	sta     (sp)
	ldy     #$09
	lda     (sp),y
	jsr     _cputcxy
	ldy     #$01
	lda     (sp),y
	jsr     _chline
	ldy     #$06
	lda     (sp),y
	jsr     _cputc
	jsr     decsp2
	ldy     #$05
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	ldy     #$04
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	sta     (sp)
	ldy     #$09
	lda     (regbank+4),y
	jsr     _cvlinexy
	ldy     #$05
	lda     (sp),y
	jsr     _cputc
	ldy     #$01
	lda     (sp),y
	jsr     _chline
	ldy     #$04
	lda     (sp),y
	jsr     _cputc
	jsr     decsp2
	ldy     #$06
	lda     (regbank+4),y
	ldy     #$01
	sta     (sp),y
	ldy     #$04
	lda     (sp),y
	sta     (sp)
	ldy     #$09
	lda     (regbank+4),y
	jsr     _cvlinexy
	lda     #$01
	jsr     _textcolor
	ldy     #$0D
	lda     (regbank+4),y
	ldy     #$08
	sta     (sp),y
	ldy     #$0F
	lda     (regbank+4),y
	tax
	dey
	lda     (regbank+4),y
	ldy     #$09
	jsr     staxysp
	bra     L010C
L010A:	jsr     decsp2
	ldy     #$05
	lda     (sp),y
	jsr     pusha0
	ldy     #$0E
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     (ptr1)
	jsr     tosadda0
	ldy     #$01
	sta     (sp),y
	ldy     #$04
	lda     (sp),y
	jsr     pusha0
	ldy     #$0E
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$01
	lda     (ptr1),y
	jsr     tosadda0
	sta     (sp)
	ldy     #$0C
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$03
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _cputsxy
	ldy     #$09
	ldx     #$00
	lda     #$04
	jsr     addeqysp
L010C:	ldy     #$08
	lda     (sp),y
	pha
	dea
	sta     (sp),y
	pla
	tax
	bne     L010A
	lda     (sp)
	jsr     _textcolor
	ldy     #$0C
	lda     (sp),y
	sta     regbank+4
	iny
	lda     (sp),y
	sta     regbank+5
	iny
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ DrawFrames (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DrawFrames: near

.segment	"CODE"

	jsr     decsp3
	lda     #$00
	ldy     #$02
L053A:	sta     (sp),y
	cmp     #$06
	bcs     L0117
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L053B
	inx
	clc
L053B:	adc     #<(_Frames)
	sta     ptr1
	txa
	adc     #>(_Frames)
	sta     ptr1+1
	dey
	lda     (ptr1),y
	tax
	lda     (ptr1)
	jsr     stax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0A
	lda     (ptr1),y
	beq     L0118
	jsr     decsp3
	ldy     #$04
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$00
	sta     (sp)
	jsr     _DrawFrame
L0118:	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	bra     L053A
L0117:	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ ActivateFrame (int, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ActivateFrame: near

.segment	"CODE"

	jsr     decsp1
	lda     regbank+4
	ldx     regbank+5
	jsr     pushax
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	cpx     _ActiveFrame+1
	bne     L053E
	cmp     _ActiveFrame
	jeq     L012A
L053E:	ldx     _ActiveFrame+1
	bmi     L012C
	jsr     decsp3
	lda     _ActiveFrame
	ldx     _ActiveFrame+1
	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     #<(_Frames)
	sta     ptr1
	lda     tmp1
	adc     #>(_Frames)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	ldy     #$01
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$00
	sta     (sp)
	jsr     _DrawFrame
L012C:	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     _ActiveFrame
	stx     _ActiveFrame+1
	txa
	bmi     L0132
	lda     _ActiveFrame
	ldx     _ActiveFrame+1
	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     #<(_Frames)
	sta     ptr1
	lda     tmp1
	adc     #>(_Frames)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	sta     regbank+4
	stx     regbank+4+1
	ldy     #$03
	lda     (sp),y
	beq     L013C
	ldy     #$05
	lda     (regbank+4),y
	ina
	ldy     #$02
L053D:	sta     (sp),y
	lda     (sp),y
	jsr     pusha0
	ldy     #$07
	lda     (regbank+4),y
	jsr     tosicmp0
	bcs     L013C
	jsr     decsp2
	ldy     #$04
	lda     (regbank+4),y
	ina
	ldy     #$01
	sta     (sp),y
	ldy     #$04
	lda     (sp),y
	sta     (sp)
	ldy     #$08
	lda     (regbank+4),y
	jsr     _cclearxy
	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	bra     L053D
L013C:	jsr     decsp3
	lda     regbank+4
	ldy     #$01
	sta     (sp),y
	iny
	lda     regbank+4+1
	sta     (sp),y
	lda     #$01
	sta     (sp)
	jsr     _DrawFrame
L0132:	lda     _ActivePrompt
	ldx     _ActivePrompt+1
	jsr     pushax
	jsr     _DisplayPrompt
L012A:	lda     (sp)
	sta     regbank+4
	ldy     #$01
	lda     (sp),y
	sta     regbank+5
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; void __near__ HelpPrompt (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_HelpPrompt: near

.segment	"CODE"

	lda     #<(L016D)
	ldx     #>(L016D)
	jsr     pushax
	jmp     _DisplayPrompt

.endproc

; ---------------------------------------------------------------
; void __near__ AnyKeyPrompt (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AnyKeyPrompt: near

.segment	"CODE"

	lda     #<(L0171)
	ldx     #>(L0171)
	jsr     pushax
	jmp     _DisplayPrompt

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ IsAbortKey (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_IsAbortKey: near

.segment	"CODE"

	ldx     #$00
	txa
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Input (__near__ unsigned char*, __near__ unsigned char*, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Input: near

.segment	"CODE"

	ldy     #$0A
	jsr     subysp
	lda     #$00
	ldy     #$01
	sta     (sp),y
	lda     #$18
	sta     (sp)
	lda     #$28
	jsr     _cclearxy
	lda     #$01
	jsr     _textcolor
	ldy     #$05
	sta     (sp),y
	jsr     decsp2
	lda     #$00
	ldy     #$01
	sta     (sp),y
	lda     #$18
	sta     (sp)
	ldy     #$0E
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _cputsxy
	lda     #$01
	jsr     _textcolor
	jsr     _wherex
	ldy     #$03
	sta     (sp),y
	lda     #$01
	jsr     _cursor
	ldy     #$04
	sta     (sp),y
	lda     #$00
	ldy     #$01
	sta     (sp),y
	iny
	sta     (sp),y
L018C:	jsr     _cgetc
	sta     (sp)
	tay
	lda     __ctype,y
	and     #$07
	beq     L0191
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	ldy     #$08
	cmp     (sp),y
	bcs     L0191
	ldy     #$02
	lda     (sp),y
	clc
	ldy     #$09
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	lda     (sp)
	sta     (ptr1)
	jsr     decsp2
	ldy     #$04
	lda     (sp),y
	clc
	iny
	adc     (sp),y
	ldy     #$01
	sta     (sp),y
	lda     #$18
	sta     (sp)
	iny
	lda     (sp),y
	jsr     _cputcxy
	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	bra     L0542
L0191:	ldy     #$02
	lda     (sp),y
	beq     L054B
	lda     (sp)
	cmp     #$08
	bne     L054B
	ldy     #$02
	lda     (sp),y
	sec
	sbc     #$01
	sta     (sp),y
	jsr     decsp2
	ldy     #$04
	lda     (sp),y
	clc
	iny
	adc     (sp),y
	ldy     #$01
	sta     (sp),y
	lda     #$18
	sta     (sp)
	lda     #$20
	jsr     _cputcxy
	ldy     #$02
	lda     (sp),y
	clc
	iny
	adc     (sp),y
	jsr     pusha
	lda     #$18
	jsr     _gotoxy
	bra     L01C0
L054B:	lda     (sp)
	cmp     #$0A
	bne     L0549
	ldy     #$02
	lda     (sp),y
	clc
	ldy     #$09
	adc     (sp),y
	sta     ptr1
	lda     #$00
	iny
	adc     (sp),y
	sta     ptr1+1
	lda     #$00
	sta     (ptr1)
	ina
	bra     L054A
L0549:	lda     (sp)
	jsr     pusha
	jsr     _IsAbortKey
	tax
	beq     L01C0
	lda     #$02
L054A:	ldy     #$01
L0542:	sta     (sp),y
L01C0:	ldy     #$01
	lda     (sp),y
	jeq     L018C
	ldy     #$04
	lda     (sp),y
	jsr     _cursor
	ldy     #$05
	lda     (sp),y
	jsr     _textcolor
	jsr     _DrawFrames
	lda     _ActiveFrame
	ldx     _ActiveFrame+1
	ldy     #$06
	jsr     staxysp
	lda     #$FF
	sta     _ActiveFrame
	sta     _ActiveFrame+1
	jsr     decsp3
	ldy     #$0A
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$00
	sta     (sp)
	jsr     _ActivateFrame
	ldy     #$01
	lda     (sp),y
	cmp     #$01
	jsr     booleq
	ldy     #$0D
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ InputHex (__near__ unsigned char*, __near__ unsigned int*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InputHex: near

.segment	"CODE"

	ldy     #$0F
	jsr     subysp
	ldy     #$12
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$03
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     sp
	ldx     sp+1
	clc
	adc     #$0A
	bcc     L01DA
	inx
L01DA:	ldy     #$01
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$04
	sta     (sp)
	jsr     _Input
	tax
	jeq     L0221
	ldy     #$05
	lda     (sp),y
	tay
	lda     __ctype,y
	and     #$08
	bne     L0550
	tax
	jmp     L0221
L0550:	lda     sp
	ldx     sp+1
	clc
	adc     #$05
	bcc     L01EE
	inx
L01EE:	ldy     #$03
	jsr     staxysp
	lda     #$00
	sta     (sp)
	ldy     #$01
	sta     (sp),y
	bra     L01F3
L01F1:	ldy     #$01
	lda     (sp),y
	tax
	lda     (sp)
	jsr     shlax4
	jsr     stax0sp
	ldy     #$02
	lda     (sp),y
	tay
	lda     __ctype,y
	and     #$04
	beq     L0206
	ldy     #$02
	lda     (sp),y
	sec
	sbc     #$30
	bra     L054D
L0206:	ldy     #$02
	lda     (sp),y
	ldx     #$00
	jsr     _toupper
	sec
	sbc     #$37
	ldy     #$02
L054D:	sta     (sp),y
	ldx     #$00
	jsr     addeq0sp
	ldy     #$03
	ldx     #$00
	lda     #$01
	jsr     addeqysp
L01F3:	ldy     #$04
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     (ptr1)
	dey
	sta     (sp),y
	tax
	beq     L054C
	lda     (sp),y
	tay
	lda     __ctype,y
	and     #$08
	bne     L01F1
L054C:	ldy     #$0B
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$01
	lda     (sp),y
	tax
	lda     (sp)
	sta     (ptr1)
	ldy     #$01
	txa
	sta     (ptr1),y
	ldx     #$00
	tya
L0221:	ldy     #$0E
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ ErrorPrompt (__near__ unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ErrorPrompt: near

.segment	"CODE"

	lda     _ActivePrompt
	ldx     _ActivePrompt+1
	jsr     pushax
	ldy     #$05
	jsr     pushwysp
	jsr     _DisplayPrompt
	jsr     _cgetc
	jsr     pushw0sp
	jsr     _DisplayPrompt
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ InputGoto (__near__ unsigned int*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InputGoto: near

.segment	"CODE"

	jsr     decsp5
	lda     #<(L022D)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L022D)
	sta     (sp),y
	ldy     #$06
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     (sp)
	ldy     #$01
	txa
	sta     (sp),y
	jsr     _InputHex
	sta     (sp)
	lda     (sp)
	bne     L0555
	lda     #<(L0233)
	ldx     #>(L0233)
	jsr     pushax
	jsr     _ErrorPrompt
L0555:	ldx     #$00
	lda     (sp)
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ BreakInRomError (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_BreakInRomError: near

.segment	"CODE"

	lda     #<(L0238)
	ldx     #>(L0238)
	jsr     pushax
	jmp     _ErrorPrompt

.endproc

; ---------------------------------------------------------------
; void __near__ DbgSetTmpBreak (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DbgSetTmpBreak: near

.segment	"CODE"

	jsr     _DbgGetBreakSlot
	jsr     pushax
	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	lda     (sp)
	sta     ptr1
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     (ptr1)
	dey
	txa
	sta     (ptr1),y
	lda     (sp),y
	sta     ptr1+1
	lda     (sp)
	sta     ptr1
	lda     #$80
	ldy     #$03
	sta     (ptr1),y
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ DbgToggleUserBreak (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DbgToggleUserBreak: near

.segment	"CODE"

	lda     regbank+4
	ldx     regbank+5
	jsr     pushax
	ldy     #$05
	jsr     pushwysp
	jsr     _DbgIsBreak
	sta     regbank+4
	stx     regbank+4+1
	lda     regbank+4
	ora     regbank+4+1
	beq     L0243
	lda     #$00
	ldy     #$03
	sta     (regbank+4),y
	dec     _DbgBreakCount
	bra     L0253
L0243:	lda     _DbgBreakCount
	cmp     #$0A
	bcc     L0249
	lda     #<(L024C)
	ldx     #>(L024C)
	jsr     pushax
	jsr     _ErrorPrompt
	bra     L0253
L0249:	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _DbgIsRAM
	stx     tmp1
	ora     tmp1
	bne     L024F
	jsr     _BreakInRomError
	bra     L0253
L024F:	jsr     _DbgGetBreakSlot
	sta     regbank+4
	stx     regbank+4+1
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     (ptr1)
	dey
	txa
	sta     (ptr1),y
	tya
	ldy     #$03
	sta     (regbank+4),y
	inc     _DbgBreakCount
L0253:	lda     (sp)
	sta     regbank+4
	ldy     #$01
	lda     (sp),y
	sta     regbank+5
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ DbgResetTmpBreaks (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DbgResetTmpBreaks: near

.segment	"CODE"

	jsr     decsp1
	lda     #<(_DbgBreaks)
	ldx     #>(_DbgBreaks)
	jsr     pushax
	lda     #$00
	ldy     #$02
L0557:	sta     (sp),y
	cmp     #$0A
	bcs     L025E
	dey
	lda     (sp),y
	sta     ptr1+1
	lda     (sp)
	sta     ptr1
	ldy     #$03
	lda     (ptr1),y
	cmp     #$80
	bne     L0265
	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	lda     (sp)
	sta     ptr1
	lda     #$00
	ldy     #$03
	sta     (ptr1),y
L0265:	ldx     #$00
	lda     #$04
	jsr     addeq0sp
	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	bra     L0557
L025E:	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ DbgTmpBreaksOk (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DbgTmpBreaksOk: near

.segment	"CODE"

	jsr     decsp1
	lda     #<(_DbgBreaks)
	ldx     #>(_DbgBreaks)
	jsr     pushax
	lda     #$00
	ldy     #$02
L0558:	sta     (sp),y
	ldx     #$00
	lda     (sp),y
	cmp     #$0A
	bcs     L055A
	dey
	lda     (sp),y
	sta     ptr1+1
	lda     (sp)
	sta     ptr1
	ldy     #$03
	lda     (ptr1),y
	cmp     #$80
	bne     L0274
	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	lda     (sp)
	sta     ptr1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	jsr     _DbgIsRAM
	stx     tmp1
	ora     tmp1
	bne     L0274
	jsr     _BreakInRomError
	jsr     _DbgResetTmpBreaks
	ldx     #$00
	txa
	jmp     incsp3
L0274:	ldx     #$00
	lda     #$04
	jsr     addeq0sp
	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	bra     L0558
L055A:	lda     #$01
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ AsmBack (unsigned int, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AsmBack: near

.segment	"CODE"

	ldy     #$43
	jsr     subysp
	lda     #$06
	jsr     pusha0
L0281:	lda     #$00
	ldy     #$02
	sta     (sp),y
	ldy     #$49
	jsr     pushwysp
	ldy     #$47
	ldx     #$00
	lda     (sp),y
	jsr     mulax3
	jsr     tossubax
	sec
	sbc     (sp)
	pha
	txa
	ldy     #$01
	sbc     (sp),y
	tax
	pla
	ldy     #$43
	jsr     staxysp
L028A:	ldy     #$44
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _DbgDisAsmLen
	ldy     #$43
	jsr     addeqysp
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L055E
	inx
	clc
L055E:	adc     #$03
	bcc     L0293
	inx
	clc
L0293:	adc     sp
	sta     ptr1
	txa
	adc     sp+1
	sta     ptr1+1
	ldy     #$44
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     (ptr1)
	ldy     #$01
	txa
	sta     (ptr1),y
	iny
	lda     (sp),y
	ina
	and     #$1F
	sta     (sp),y
	ldy     #$44
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$46
	cmp     (sp),y
	txa
	iny
	sbc     (sp),y
	bcc     L028A
	ldy     #$44
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$46
	cmp     (sp),y
	bne     L0561
	txa
	iny
	cmp     (sp),y
	beq     L029C
L0561:	ldy     #$01
	lda     (sp),y
	bne     L0563
	lda     (sp)
	cmp     #$0C
	bne     L0563
L029C:	ldy     #$02
	ldx     #$00
	lda     (sp),y
	sec
	ldy     #$45
	sbc     (sp),y
	sec
	sbc     #$01
	and     #$1F
	asl     a
	bcc     L055F
	inx
	clc
L055F:	adc     #$03
	bcc     L02A3
	inx
	clc
L02A3:	adc     sp
	sta     ptr1
	txa
	adc     sp+1
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	bra     L0282
L0563:	ldx     #$00
	tya
	jsr     addeq0sp
	jmp     L0281
L0282:	ldy     #$48
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ UpdateAsm (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateAsm: near

.segment	"CODE"

	ldy     #$2A
	jsr     subysp
	lda     _AsmFrame+8
	jsr     pusha
	lda     _AsmFrame+4
	ina
	jsr     pusha
	jsr     decsp3
	lda     _AsmAddr
	ldy     #$01
	sta     (sp),y
	iny
	lda     _AsmAddr+1
	sta     (sp),y
	tya
	sta     (sp)
	jsr     _AsmBack
	jsr     pushax
	lda     _AsmFrame+5
	ina
	ldy     #$04
L0566:	sta     (sp),y
	cmp     _AsmFrame+7
	jcs     L02AF
	jsr     decsp4
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     sp
	ldx     sp+1
	clc
	adc     #$0A
	bcc     L02BB
	inx
L02BB:	sta     (sp)
	ldy     #$01
	txa
	sta     (sp),y
	ldy     #$07
	lda     (sp),y
	jsr     _DbgDisAsm
	ldy     #$05
	sta     (sp),y
	ldy     #$01
	lda     (sp),y
	tax
	lda     (sp)
	cpx     _brk_pc+1
	bne     L02BD
	cmp     _brk_pc
	bne     L02BD
	lda     #$2D
	ldy     #$0A
	sta     (sp),y
	lda     #$3E
	iny
	sta     (sp),y
L02BD:	jsr     pushw0sp
	jsr     _DbgIsBreak
	stx     tmp1
	ora     tmp1
	beq     L02C7
	lda     #$2A
	ldy     #$0B
	sta     (sp),y
L02C7:	ldy     #$01
	lda     (sp),y
	tax
	lda     (sp)
	cpx     _AsmAddr+1
	bne     L02CE
	cmp     _AsmAddr
	bne     L02CE
	tya
	jsr     _revers
	jsr     decsp2
	lda     #$01
	tay
	sta     (sp),y
	ldy     #$06
	lda     (sp),y
	sta     (sp)
	lda     sp
	ldx     sp+1
	clc
	adc     #$08
	bcc     L02D6
	inx
L02D6:	jsr     _cputsxy
	lda     #$00
	jsr     _revers
	bra     L02D9
L02CE:	jsr     decsp2
	tya
	tay
	sta     (sp),y
	ldy     #$06
	lda     (sp),y
	sta     (sp)
	lda     sp
	ldx     sp+1
	clc
	adc     #$08
	bcc     L02DE
	inx
L02DE:	jsr     _cputsxy
L02D9:	ldy     #$05
	lda     (sp),y
	ldx     #$00
	jsr     addeq0sp
	ldy     #$04
	clc
	lda     #$01
	adc     (sp),y
	jmp     L0566
L02AF:	ldy     #$01
	lda     (sp),y
	tax
	lda     (sp)
	ldy     #$2E
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ AsmArg16 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AsmArg16: near

.segment	"CODE"

	lda     _AsmAddr
	ldx     _AsmAddr+1
	ina
	bne     L02E5
	inx
L02E5:	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ AsmFollow (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AsmFollow: near

.segment	"CODE"

	lda     _AsmAddr
	sta     ptr1
	lda     _AsmAddr+1
	sta     ptr1+1
	ldx     #$00
	lda     (ptr1)
	cmp     #$10
	beq     L02F5
	cmp     #$20
	beq     L02EB
	cmp     #$30
	beq     L02F5
	cmp     #$40
	beq     L0569
	cmp     #$4C
	beq     L02EB
	cmp     #$50
	beq     L02F5
	cmp     #$60
	beq     L0568
	cmp     #$6C
	beq     L02F1
	cmp     #$70
	beq     L02F5
	cmp     #$90
	beq     L02F5
	cmp     #$B0
	beq     L02F5
	cmp     #$D0
	beq     L02F5
	cmp     #$F0
	beq     L02F5
	rts
L02EB:	jsr     _AsmArg16
	bra     L056A
L02F1:	jsr     _AsmArg16
	bra     L0571
L02F5:	lda     _AsmAddr
	ldx     _AsmAddr+1
	clc
	adc     #$02
	bcc     L0306
	inx
L0306:	jsr     pushax
	lda     _AsmAddr
	ldx     _AsmAddr+1
	ina
	bne     L0308
	inx
L0308:	ldy     #$00
	jsr     ldaidx
	jsr     tosaddax
	bra     L056A
L0568:	lda     _DbgSP
	clc
	adc     #$01
	bcc     L030F
	inx
L030F:	inx
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	ina
	bne     L056A
	inx
	bra     L056A
L0569:	lda     _DbgSP
	clc
	adc     #$02
	bcc     L0316
	inx
L0316:	inx
L0571:	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
L056A:	sta     _AsmAddr
	stx     _AsmAddr+1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ AsmHome (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AsmHome: near

.segment	"CODE"

	lda     _brk_pc
	sta     _AsmAddr
	lda     _brk_pc+1
	sta     _AsmAddr+1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ InitAsm (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitAsm: near

.segment	"CODE"

	jsr     _AsmHome
	jmp     _UpdateAsm

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ UpdateReg (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateReg: near

.segment	"CODE"

	lda     _RegFrame+4
	clc
	adc     #$05
	jsr     pusha
	lda     (sp)
	clc
	adc     #$02
	jsr     pusha
	lda     _RegFrame+5
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _brk_pc
	ldx     _brk_pc+1
	jsr     _cputhex16
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _brk_sr
	jsr     _cputhex8
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _brk_a
	jsr     _cputhex8
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _brk_x
	jsr     _cputhex8
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _brk_y
	jsr     _cputhex8
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _DbgSP
	jsr     _cputhex8
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _DbgCS
	ldx     _DbgCS+1
	jsr     _cputhex16
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _DbgHI
	ldx     _DbgHI+1
	jsr     _cputhex16
	ldx     #$00
	txa
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ InitReg (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitReg: near

.segment	"CODE"

	jmp     _UpdateReg

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ UpdateStack (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateStack: near

.segment	"CODE"

	lda     _StackAddr
	jsr     pusha
	lda     _StackFrame+4
	ina
	jsr     pusha
	lda     (sp)
	clc
	adc     #$06
	jsr     pusha
	jsr     decsp1
	lda     _StackFrame+7
	sec
	sbc     #$01
L0573:	sta     (sp)
	ldx     #$00
	lda     (sp)
	sec
	sbc     _StackFrame+5
	sta     tmp1
	lda     tmp1
	beq     L038B
	bcc     L038B
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     _gotoxy
	ldy     #$03
	lda     (sp),y
	jsr     _cputhex8
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     _gotoxy
	ldy     #$03
	lda     (sp),y
	sta     ptr1
	lda     #$01
	sta     ptr1+1
	lda     (ptr1)
	jsr     _cputhex8
	ldy     #$03
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	lda     (sp)
	sec
	sbc     #$01
	bra     L0573
L038B:	ldy     #$03
	lda     (sp),y
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ StackHome (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_StackHome: near

.segment	"CODE"

	lda     _DbgSP
	ina
	sta     _StackAddr
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ InitStack (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitStack: near

.segment	"CODE"

	jsr     _StackHome
	jmp     _UpdateStack

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ UpdateCStack (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateCStack: near

.segment	"CODE"

	lda     _CStackAddr
	ldx     _CStackAddr+1
	jsr     pushax
	lda     _CStackFrame+4
	clc
	adc     #$05
	jsr     pusha
	jsr     decsp1
	lda     _CStackFrame+7
L0577:	sec
	sbc     #$01
	sta     (sp)
	sec
	sbc     _CStackFrame+5
	sta     tmp1
	lda     tmp1
	beq     L03CA
	bcc     L03CA
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     _gotoxy
	ldy     #$03
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	dey
	lda     (ptr1),y
	tax
	lda     (ptr1)
	jsr     _cputhex16
	ldy     #$02
	ldx     #$00
	tya
	jsr     addeqysp
	lda     (sp)
	bra     L0577
L03CA:	jsr     decsp2
	lda     _CStackFrame+4
	ina
	ldy     #$01
	sta     (sp),y
	lda     _CStackFrame+7
	sec
	sbc     #$01
	sta     (sp)
	lda     #<(L03DD)
	ldx     #>(L03DD)
	jsr     _cputsxy
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ CStackHome (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_CStackHome: near

.segment	"CODE"

	lda     _DbgCS
	sta     _CStackAddr
	lda     _DbgCS+1
	sta     _CStackAddr+1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ InitCStack (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitCStack: near

.segment	"CODE"

	jsr     _CStackHome
	jmp     _UpdateCStack

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ UpdateDump (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateDump: near

.segment	"CODE"

	ldy     #$29
	jsr     subysp
	lda     _DumpAddr
	ldx     _DumpAddr+1
	jsr     pushax
	lda     _DumpFrame+4
	ina
	jsr     pusha
	ldy     #$04
	jsr     pushwysp
	lda     _DumpFrame+5
	ina
	ldy     #$05
L0578:	sta     (sp),y
	cmp     _DumpFrame+7
	bcs     L0410
	jsr     decsp2
	dey
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	ldy     #$07
	lda     (sp),y
	sta     (sp)
	jsr     decsp5
	ldy     #$0B
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$03
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     sp
	ldx     sp+1
	clc
	adc     #$0D
	bcc     L041E
	inx
L041E:	ldy     #$01
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$08
	sta     (sp)
	jsr     _DbgMemDump
	jsr     _cputsxy
	ldy     #$03
	ldx     #$00
	lda     #$08
	jsr     addeqysp
	ldy     #$05
	clc
	lda     #$01
	adc     (sp),y
	bra     L0578
L0410:	dey
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$2E
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ DumpHome (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DumpHome: near

.segment	"CODE"

	stz     _DumpAddr
	stz     _DumpAddr+1
	rts

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ GetArg16 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_GetArg16: near

.segment	"CODE"

	lda     _brk_pc
	ldx     _brk_pc+1
	ina
	bne     L0459
	inx
L0459:	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	rts

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ GetStack16 (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_GetStack16: near

.segment	"CODE"

	ldx     #$00
	lda     (sp)
	clc
	adc     _DbgSP
	bcc     L057A
	inx
	clc
L057A:	adc     #$01
	bcc     L045D
	inx
L045D:	inx
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ SetRTSBreak (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_SetRTSBreak: near

.segment	"CODE"

	lda     #$00
	jsr     pusha
	jsr     _GetStack16
	ina
	bne     L0462
	inx
L0462:	jsr     pushax
	jmp     _DbgSetTmpBreak

.endproc

; ---------------------------------------------------------------
; void __near__ DbgEntry (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DbgEntry: near

.segment	"DATA"

L04CE:
	.byte	$01

.segment	"CODE"

	jsr     decsp2
	lda     L04CE
	beq     L04D0
	lda     #$00
	stz     L04CE
	jsr     pusha
	jsr     _RedrawStatic
	jsr     _InitAsm
	jsr     _InitReg
	jsr     _InitStack
	jsr     _InitCStack
	jsr     _UpdateDump
L04D0:	jsr     _AsmHome
	jsr     _UpdateReg
	jsr     _StackHome
	jsr     _CStackHome
	lda     #$00
	sta     (sp)
	jmp     L057D
L04E1:	lda     _ActiveFrame
	ldx     _ActiveFrame+1
	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     #<(_Frames)
	sta     ptr1
	lda     tmp1
	adc     #>(_Frames)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	sta     ptr1
	stx     ptr1+1
	ldy     #$0C
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     callax
	ldy     #$01
	sta     (sp),y
	lda     (sp),y
	jeq     L057C
	cmp     #$0A
	jeq     L0512
	cmp     #$20
	jeq     L050A
	cmp     #$31
	beq     L04EC
	cmp     #$32
	beq     L04EC
	cmp     #$33
	beq     L04EC
	cmp     #$34
	beq     L04EC
	cmp     #$35
	beq     L04EC
	cmp     #$3F
	beq     L04FA
	cmp     #$63
	jeq     L057C
	cmp     #$68
	beq     L0502
	cmp     #$71
	jeq     L052A
	cmp     #$72
	jeq     L0526
	cmp     #$73
	jeq     L0520
	cmp     #$75
	beq     L04FD
	jmp     L057D
L04EC:	jsr     decsp3
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	sec
	sbc     #$31
	bcs     L04F7
	dex
L04F7:	ldy     #$01
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$00
	sta     (sp)
	jsr     _ActivateFrame
	jmp     L057D
L04FA:	jsr     _HelpHandler
	jmp     L057D
L04FD:	jsr     _SetRTSBreak
	lda     #$01
	sta     (sp)
	jmp     L057D
L0502:	lda     _brk_pc
	ldx     _brk_pc+1
	cpx     _AsmAddr+1
	bne     L057E
	cmp     _AsmAddr
	beq     L057D
L057E:	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     pushax
	jsr     _DbgSetTmpBreak
	lda     #$01
	sta     (sp)
	bra     L057D
L050A:	tya
	jsr     pusha
	jsr     _SingleStep
	jsr     _DbgTmpBreaksOk
	tax
	beq     L057D
	lda     #$01
	sta     (sp)
	bra     L057D
L0512:	lda     #$00
	jsr     pusha
	jsr     _SingleStep
	jsr     _DbgTmpBreaksOk
	tax
	beq     L057D
	lda     #$01
	sta     (sp)
	bra     L057D
L057C:	tya
	sta     (sp)
	bra     L057D
L0520:	lda     _brk_pc
	ldx     _brk_pc+1
	jsr     _DbgDisAsmLen
	clc
	adc     _brk_pc
	sta     _brk_pc
	txa
	adc     _brk_pc+1
	sta     _brk_pc+1
	jsr     _InitAsm
	bra     L057D
L0526:	lda     _ActiveFrame
	jsr     pusha
	jsr     _Redraw
	bra     L057D
L052A:	jsr     _clrscr
	ldx     #$00
	lda     #$01
	jsr     _exit
L057D:	lda     (sp)
	jeq     L04E1
	jmp     incsp2

.endproc

