;
; File generated by co65 v 2.14.0 using model `cc65-module'
;
.fopt		compiler,"co65 v 2.14.0"
.case		on
.debuginfo	off
.export		_c128_reu_emd

;
; CODE SEGMENT
;
.segment	"CODE"
_c128_reu_emd:
	.byte	$65
	.byte	$6D
	.byte	$64
	.byte	$02
	.byte	$00
	.byte	$00
	.word	_c128_reu_emd+22
	.word	_c128_reu_emd+69
	.word	_c128_reu_emd+70
	.word	_c128_reu_emd+77
	.word	_c128_reu_emd+93
	.word	_c128_reu_emd+104
	.word	_c128_reu_emd+147
	.word	_c128_reu_emd+150
	.byte	$A2
	.byte	$00
	.byte	$A9
	.byte	$55
	.byte	$8D
	.byte	$04
	.byte	$DF
	.byte	$CD
	.byte	$04
	.byte	$DF
	.byte	$D0
	.byte	$21
	.byte	$0A
	.byte	$8D
	.byte	$04
	.byte	$DF
	.byte	$CD
	.byte	$04
	.byte	$DF
	.byte	$D0
	.byte	$18
	.byte	$A0
	.byte	$02
	.byte	$AD
	.byte	$00
	.byte	$DF
	.byte	$29
	.byte	$10
	.byte	$F0
	.byte	$02
	.byte	$A0
	.byte	$04
	.byte	$8C
	.word	BSS+1
	.byte	$A0
	.byte	$FF
	.byte	$8C
	.word	BSS+2
	.byte	$8C
	.word	BSS+3
	.byte	$8A
	.byte	$60
	.byte	$A9
	.byte	$04
	.byte	$60
	.byte	$AD
	.word	BSS+0
	.byte	$AE
	.word	BSS+1
	.byte	$60
	.byte	$8D
	.word	BSS+2
	.byte	$8E
	.word	BSS+3
	.byte	$A0
	.byte	$ED
	.byte	$20
	.word	_c128_reu_emd+114
	.byte	$A9
	.byte	<(BSS+4)
	.byte	$A2
	.byte	>(BSS+4)
	.byte	$60
	.byte	$8D
	.word	BSS+2
	.byte	$8E
	.word	BSS+3
	.byte	$A9
	.byte	<(BSS+4)
	.byte	$A2
	.byte	>(BSS+4)
	.byte	$60
	.byte	$AD
	.word	BSS+2
	.byte	$AE
	.word	BSS+3
	.byte	$30
	.byte	$EC
	.byte	$A0
	.byte	$EC
	.byte	$84
	.byte	<(ZEROPAGE+16)
	.byte	$A0
	.byte	<(BSS+4)
	.byte	$8C
	.byte	$02
	.byte	$DF
	.byte	$A0
	.byte	>(BSS+4)
	.byte	$8C
	.byte	$03
	.byte	$DF
	.byte	$A0
	.byte	$00
	.byte	$8C
	.byte	$04
	.byte	$DF
	.byte	$8D
	.byte	$05
	.byte	$DF
	.byte	$8E
	.byte	$06
	.byte	$DF
	.byte	$8C
	.byte	$07
	.byte	$DF
	.byte	$A0
	.byte	$01
	.byte	$8C
	.byte	$08
	.byte	$DF
	.byte	$D0
	.byte	$18
	.byte	$A0
	.byte	$ED
	.byte	$2C
	.byte	$A0
	.byte	$EC
	.byte	$84
	.byte	<(ZEROPAGE+16)
	.byte	$85
	.byte	<(ZEROPAGE+8)
	.byte	$86
	.byte	<(ZEROPAGE+9)
	.byte	$A0
	.byte	$06
	.byte	$B1
	.byte	<(ZEROPAGE+8)
	.byte	$99
	.byte	$02
	.byte	$DF
	.byte	$88
	.byte	$10
	.byte	$F8
	.byte	$8C
	.word	BSS+3
	.byte	$A4
	.byte	<(ZEROPAGE+16)
	.byte	$8C
	.byte	$01
	.byte	$DF
	.byte	$AC
	.byte	$00
	.byte	$FF
	.byte	$A9
	.byte	$3F
	.byte	$78
	.byte	$8D
	.byte	$00
	.byte	$FF
	.byte	$AD
	.byte	$00
	.byte	$FF
	.byte	$8D
	.byte	$00
	.byte	$FF
	.byte	$8C
	.byte	$00
	.byte	$FF
	.byte	$58
	.byte	$60

;
; DATA SEGMENT
;
.segment	"DATA"
DATA:

;
; BSS SEGMENT
;
.segment	"BSS"
BSS:
	.res	269

;
; ZEROPAGE SEGMENT
;
.import	__ZP_START__		; Linker generated symbol
ZEROPAGE = __ZP_START__

.end
