;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		__cbm_filetype
	.import		_cbm_k_basin
	.import		_cbm_k_chkin
	.import		_cbm_k_clrch
	.import		_cbm_k_readst
	.import		_cbm_open
	.import		_cbm_close
	.export		_cbm_opendir
	.export		_cbm_readdir
	.export		_cbm_closedir
	.import		__oserror

.segment	"RODATA"

L0007:
	.byte	$24,$00

; ---------------------------------------------------------------
; unsigned char __near__ cbm_opendir (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cbm_opendir: near

.segment	"CODE"

	jsr     enter
	jsr     decsp2
	lda     #<(L0007)
	ldx     #>(L0007)
	jsr     pushax
	ldy     #$04
	lda     (sp),y
	cmp     #$04
	bne     L0009
	jsr     leaa0sp
	clc
	adc     #$03
	bcc     L000F
	inx
L000F:	ldy     #$02
	jsr     staxysp
	ldx     #$00
	lda     #$02
	tay
	jsr     subeqysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     stax0sp
L0009:	jsr     decsp3
	ldy     #$07
	lda     (sp),y
	jsr     leaa0sp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	ldy     #$02
	sta     (sp),y
	ldy     #$07
	lda     (sp),y
	jsr     leaa0sp
	dey
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	ldy     #$01
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	ldy     #$04
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _cbm_open
	cmp     #$00
	bne     L0028
	ldy     #$04
	lda     (sp),y
	jsr     leaa0sp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	jsr     _cbm_k_chkin
	sta     __oserror
	cmp     #$00
	bne     L0028
	jsr     _cbm_k_basin
	jsr     _cbm_k_basin
	jsr     _cbm_k_clrch
	jsr     _cbm_k_readst
	tax
	beq     L00B5
	ldy     #$04
	lda     (sp),y
	jsr     leaa0sp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	jsr     _cbm_close
	lda     #$04
	sta     __oserror
L0028:	ldx     #$00
L00B5:	lda     __oserror
	ldy     #$04
	jmp     leavey

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ __fastcall__ cbm_readdir (unsigned char, register __near__ struct cbm_dirent*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cbm_readdir: near

.segment	"CODE"

	jsr     pushax
	ldy     #$00
	ldx     #$04
	jsr     regswap2
	jsr     decsp1
	lda     #$00
	jsr     pusha
	jsr     pusha
	lda     #$01
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     _cbm_k_chkin
	tax
	jne     L0037
	jsr     _cbm_k_readst
	tax
	jne     L0037
	jsr     _cbm_k_basin
	jsr     _cbm_k_basin
	lda     regbank+4
	ldx     regbank+4+1
	jsr     pushax
	jsr     _cbm_k_basin
	jsr     pushax
	jsr     _cbm_k_basin
	tax
	lda     #$00
	jsr     tosorax
	ldy     #$11
	jsr     staxspidx
	jsr     _cbm_k_basin
	ldy     #$03
	sta     (sp),y
	cmp     #$12
	beq     L00BA
	cmp     #$42
	beq     L0047
	jmp     L00BC
L0045:	jsr     _cbm_k_basin
L0047:	jsr     _cbm_k_readst
	tax
	beq     L0045
	lda     #$02
	jmp     L00C1
L00BA:	lda     #$01
	tay
	jmp     L00B9
L0051:	jsr     _cbm_k_readst
	tax
	beq     L0055
	lda     #$03
	jmp     L00C1
L0055:	jsr     _cbm_k_basin
	ldy     #$03
L00B9:	sta     (sp),y
	ldy     #$03
L00BC:	lda     (sp),y
	cmp     #$22
	bne     L0051
	jmp     L005D
L005B:	jsr     _cbm_k_readst
	tax
	beq     L0061
	lda     #$04
	jmp     L00C1
L0061:	ldy     #$02
	lda     (sp),y
	cmp     #$10
	bcs     L005D
	clc
	adc     regbank+4
	ldx     regbank+4+1
	bcc     L00B6
	inx
L00B6:	sta     ptr1
	stx     ptr1+1
	iny
	lda     (sp),y
	ldy     #$00
	sta     (ptr1),y
	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
L005D:	jsr     _cbm_k_basin
	ldy     #$03
	sta     (sp),y
	cmp     #$22
	bne     L005B
	dey
	lda     (sp),y
	clc
	adc     regbank+4
	ldx     regbank+4+1
	bcc     L00B7
	inx
L00B7:	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	iny
	lda     (sp),y
	beq     L007F
	lda     #$05
	ldy     #$13
	sta     (regbank+4),y
	lda     #$06
	ldy     #$02
	sta     (sp),y
L0075:	lda     regbank+4
	ldx     regbank+4+1
	jsr     pushax
	jsr     _cbm_k_basin
	ldy     #$05
	sta     (sp),y
	ldy     #$14
	jsr     staspidx
	ldy     #$02
	lda     (sp),y
	sec
	sbc     #$01
	sta     (sp),y
	cmp     #$00
	bne     L0075
	jmp     L00A6
L007D:	jsr     _cbm_k_readst
	tax
	beq     L007F
	lda     #$05
	jmp     L00C1
L007F:	jsr     _cbm_k_basin
	ldy     #$03
	sta     (sp),y
	cmp     #$20
	beq     L007D
	tya
	ldy     #$14
	sta     (regbank+4),y
	tay
	lda     (sp),y
	cmp     #$2A
	bne     L0089
	lda     #$02
	ldy     #$14
	sta     (regbank+4),y
	jsr     _cbm_k_basin
	ldy     #$03
	sta     (sp),y
L0089:	lda     regbank+4
	ldx     regbank+4+1
	jsr     pushax
	ldy     #$05
	lda     (sp),y
	jsr     __cbm_filetype
	ldy     #$13
	jsr     staspidx
	jsr     _cbm_k_basin
	cmp     #$49
	bne     L0092
	ldy     #$03
	lda     (sp),y
	cmp     #$44
	bne     L0092
	lda     #$02
	ldy     #$13
	sta     (regbank+4),y
L0092:	jsr     _cbm_k_basin
	jsr     _cbm_k_basin
	ldy     #$03
	sta     (sp),y
	cmp     #$3C
	bne     L00C0
	ldy     #$14
	lda     (regbank+4),y
	cmp     #$02
	bne     L00BE
	lda     #$00
	jmp     L00BF
L00BE:	lda     #$01
L00BF:	sta     (regbank+4),y
	jmp     L00A6
L00A4:	jsr     _cbm_k_readst
	tax
	beq     L00A8
	lda     #$06
	jmp     L00C1
L00A8:	jsr     _cbm_k_basin
	ldy     #$03
	sta     (sp),y
L00A6:	ldy     #$03
L00C0:	lda     (sp),y
	bne     L00A4
L00C1:	ldy     #$00
	sta     (sp),y
L0037:	jsr     _cbm_k_clrch
	ldx     #$00
	lda     (sp,x)
	pha
	ldy     #$04
	lda     (sp),y
	sta     regbank+4
	iny
	lda     (sp),y
	sta     regbank+5
	pla
	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; void __near__ __fastcall__ cbm_closedir (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cbm_closedir: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (sp),y
	jsr     _cbm_close
	jmp     incsp1

.endproc

