;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_malloc
	.import		_memcpy
	.import		_open
	.import		__errno
	.export		_opendir
	.import		__dirread

; ---------------------------------------------------------------
; __near__ struct DIR* __near__ __fastcall__ opendir (register __near__ const unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_opendir: near

.segment	"CODE"

	jsr     pushax
	ldy     #$00
	ldx     #$04
	jsr     regswap2
	jsr     decsp2
	jsr     push0
	ldy     #$15
	jsr     subysp
	lda     #$24
	ldy     #$04
	sta     (sp),y
	lda     regbank+4
	ora     regbank+4+1
	beq     L005B
	lda     (regbank+4,x)
	beq     L005B
	cmp     #$2E
	bne     L0063
	ldy     #$01
	lda     (regbank+4),y
	bne     L0063
L005B:	ldy     #$05
	sta     (sp),y
	jmp     L0061
L0063:	lda     (regbank+4,x)
	cmp     #$30
	beq     L005C
	cmp     #$31
	bne     L0060
L005C:	ldy     #$01
	lda     (regbank+4),y
	cmp     #$3A
	bne     L0060
	iny
	lda     (regbank+4),y
	bne     L0060
	lda     (regbank+4,x)
	ldy     #$05
	sta     (sp),y
	lda     #$00
	iny
	sta     (sp),y
	jmp     L0061
L0060:	lda     #$07
	jmp     L0062
L0061:	ldy     #$02
	tya
	sta     (sp),y
	lda     #$00
	iny
	sta     (sp),y
	jsr     decsp4
	lda     sp
	ldx     sp+1
	clc
	adc     #$08
	bcc     L0036
	inx
L0036:	dey
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$01
	ldy     #$00
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	ldy     #$04
	jsr     _open
	jsr     stax0sp
	txa
	bmi     L004F
	jsr     decsp4
	lda     sp
	ldx     sp+1
	clc
	adc     #$04
	bcc     L003D
	inx
L003D:	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     sp
	ldx     sp+1
	clc
	adc     #$1B
	bcc     L003F
	inx
L003F:	ldy     #$00
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$02
	jsr     __dirread
	tax
	beq     L004F
	ldx     #$00
	lda     #$15
	jsr     _malloc
	ldy     #$15
	jsr     staxysp
	ldy     #$16
	lda     (sp),y
	dey
	ora     (sp),y
	beq     L0046
	iny
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	dey
L004E:	lda     (sp),y
	sta     (ptr1),y
	dey
	bpl     L004E
	jmp     L004F
L0046:	tax
	lda     #$02
L0062:	sta     __errno
	stx     __errno+1
L004F:	ldy     #$16
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	pha
	ldy     #$19
	lda     (sp),y
	sta     regbank+4
	iny
	lda     (sp),y
	sta     regbank+5
	pla
	iny
	jmp     addysp

.endproc

