;
; File generated by co65 v 2.14.0 using model `cc65-module'
;
.fopt		compiler,"co65 v 2.14.0"
.case		on
.debuginfo	off
.export		_pet_stdjoy_joy

;
; CODE SEGMENT
;
.segment	"CODE"
_pet_stdjoy_joy:
	.byte	$6A
	.byte	$6F
	.byte	$79
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$04
	.byte	$08
	.byte	$10
	.byte	$00
	.byte	$00
	.byte	$00
	.word	_pet_stdjoy_joy+24
	.word	_pet_stdjoy_joy+28
	.word	_pet_stdjoy_joy+29
	.word	_pet_stdjoy_joy+34
	.byte	$00
	.byte	$00
	.byte	$A9
	.byte	$00
	.byte	$A2
	.byte	$00
	.byte	$60
	.byte	$A9
	.byte	$02
	.byte	$A2
	.byte	$00
	.byte	$60
	.byte	$AA
	.byte	$D0
	.byte	$17
	.byte	$A9
	.byte	$00
	.byte	$8D
	.byte	$43
	.byte	$E8
	.byte	$AD
	.byte	$41
	.byte	$E8
	.byte	$29
	.byte	$0F
	.byte	$C9
	.byte	$0C
	.byte	$D0
	.byte	$04
	.byte	$A9
	.byte	$0F
	.byte	$D0
	.byte	$02
	.byte	$09
	.byte	$10
	.byte	$49
	.byte	$1F
	.byte	$60
	.byte	$A9
	.byte	$00
	.byte	$8D
	.byte	$43
	.byte	$E8
	.byte	$AD
	.byte	$41
	.byte	$E8
	.byte	$4A
	.byte	$4A
	.byte	$4A
	.byte	$4A
	.byte	$C9
	.byte	$0C
	.byte	$D0
	.byte	$04
	.byte	$A9
	.byte	$0F
	.byte	$D0
	.byte	$02
	.byte	$09
	.byte	$10
	.byte	$49
	.byte	$1F
	.byte	$A2
	.byte	$00
	.byte	$60

;
; DATA SEGMENT
;
.segment	"DATA"
DATA:

;
; BSS SEGMENT
;
.segment	"BSS"
BSS:
	.res	0

;
; ZEROPAGE SEGMENT
;
.import	__ZP_START__		; Linker generated symbol
ZEROPAGE = __ZP_START__

.end
