;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		__errno
	.import		__cbm_filetype
	.export		_readdir
	.import		__dirread
	.import		__dirread1

; ---------------------------------------------------------------
; __near__ struct dirent* __near__ __fastcall__ readdir (register __near__ struct DIR*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_readdir: near

.segment	"BSS"

L0005:
	.res	1,$00
L0006:
	.res	1,$00
L0008:
	.res	23,$00

.segment	"CODE"

	jsr     pushax
	ldy     #$00
	ldx     #$04
	jsr     regswap2
	lda     regbank+2
	ldx     regbank+3
	jsr     pushax
	lda     regbank+1
	jsr     pusha
	lda     regbank+0
	jsr     pusha
	ldy     #$40
	jsr     subysp
	ldy     #$03
	lda     (regbank+4),y
	sta     L0008+17+1
	dey
	lda     (regbank+4),y
	sta     L0008+17
	jsr     decsp4
	lda     regbank+4
	sta     (sp),y
	iny
	lda     regbank+4+1
	sta     (sp),y
	lda     sp
	ldx     sp+1
	clc
	adc     #$04
	bcc     L000F
	inx
L000F:	ldy     #$00
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$02
	jsr     __dirread
	tax
	jeq     L0004
	jsr     decsp4
	lda     regbank+4
	ldy     #$02
	sta     (sp),y
	iny
	lda     regbank+4+1
	sta     (sp),y
	lda     #<(L0008+19)
	ldy     #$00
	sta     (sp),y
	iny
	lda     #>(L0008+19)
	sta     (sp),y
	lda     #$02
	jsr     __dirread
	tax
	jeq     L0004
	lda     #$00
	sta     regbank+0
	lda     sp
	sta     regbank+2
	lda     sp+1
	sta     regbank+2+1
L0018:	lda     regbank+0
	cmp     #$40
	bcs     L0019
	lda     regbank+4
	ldx     regbank+4+1
	jsr     pushax
	lda     regbank+2
	ldx     regbank+2+1
	jsr     __dirread1
	tax
	jeq     L0004
	inc     regbank+0
	ldy     #$00
	lda     (regbank+2),y
	beq     L0019
	inc     regbank+2
	bne     L0018
	inc     regbank+2+1
	jmp     L0018
L0019:	ldy     #$03
	lda     (regbank+4),y
	tax
	dey
	lda     (regbank+4),y
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     regbank+0
	clc
	adc     #$04
	bcc     L0085
	inx
	clc
L0085:	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	sta     (regbank+4),y
	iny
	txa
	sta     (regbank+4),y
	ldx     #$00
	lda     (sp,x)
	cmp     #$42
	jeq     L008C
	txa
	sta     regbank+1
	sta     L0006
	sta     L0005
	lda     sp
	sta     regbank+2
	lda     sp+1
	sta     regbank+2+1
	jmp     L008B
L0086:	lda     L0005
	beq     L0041
	cmp     #$01
	beq     L0047
	cmp     #$02
	beq     L0062
	cmp     #$03
	jeq     L006F
	jmp     L008A
L0041:	lda     (regbank+2,x)
	cmp     #$22
	jne     L008A
	lda     #$01
	sta     L0005
	jmp     L008A
L0047:	ldy     #$00
	lda     (regbank+2),y
	cmp     #$22
	bne     L0088
	ldy     L0006
	txa
	sta     L0008,y
	lda     L0006
	sta     L0008+22
	lda     L0008+17
	cmp     #$03
	lda     L0008+17+1
	sbc     #$00
	bcc     L0087
	lda     #$02
	sta     L0005
	jmp     L008A
L0087:	lda     #$05
	sta     L0008+21
	lda     #<(L0008)
	ldx     #>(L0008)
	jmp     L0004
L0088:	lda     L0006
	cmp     #$10
	bcs     L008A
	lda     #<(L0008)
	ldx     #>(L0008)
	clc
	adc     L0006
	bcc     L005E
	inx
L005E:	sta     ptr1
	stx     ptr1+1
	lda     (regbank+2),y
	sta     (ptr1),y
	inc     L0006
	jmp     L008A
L0062:	lda     (regbank+2,x)
	cmp     #$20
	beq     L008A
	jsr     __cbm_filetype
	sta     L0008+21
	ldy     #$00
	lda     (regbank+2),y
	cmp     #$44
	bne     L0068
	lda     #$03
	sta     L0005
	jmp     L008A
L0068:	lda     #<(L0008)
	ldx     #>(L0008)
	jmp     L0004
L006F:	lda     (regbank+2,x)
	cmp     #$45
	beq     L0072
	cmp     #$49
	bne     L0089
	lda     #$02
	jmp     L0084
L0089:	lda     #$04
L0084:	sta     L0008+21
L0072:	lda     #<(L0008)
	ldx     #>(L0008)
	jmp     L0004
L008A:	inc     regbank+1
	inc     regbank+2
	bne     L007F
	inc     regbank+2+1
L007F:	ldx     #$00
L008B:	lda     regbank+1
	cmp     regbank+0
	jcc     L0086
	lda     #$0B
	sta     __errno
	stx     __errno+1
L008C:	txa
L0004:	pha
	stx     tmp1
	ldy     #$45
	ldx     #$05
L0083:	lda     (sp),y
	sta     regbank+0,x
	dey
	dex
	bpl     L0083
	ldx     tmp1
	pla
	ldy     #$46
	jmp     addysp

.endproc

