;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_exit
	.import		_ExitTurbo
	.import		_SetPattern
	.import		_Rectangle
	.import		_FrameRectangle
	.import		_PutString
	.import		_PutDecimal
	.import		_DlgBoxOk
	.export		__afailed

.segment	"RODATA"

L0044:
	.byte	$50,$52,$4F,$47,$52,$41,$4D,$20,$54,$45,$52,$4D,$49,$4E,$41,$54
	.byte	$45,$44,$1B,$00
L0042:
	.byte	$18,$41,$53,$53,$45,$52,$54,$49,$4F,$4E,$20,$46,$41,$49,$4C,$45
	.byte	$44,$00
L0034:
	.byte	$18,$20,$20,$6C,$69,$6E,$65,$3A,$20,$00
L0029:
	.byte	$18,$66,$69,$6C,$65,$3A,$20,$00

; ---------------------------------------------------------------
; void __near__ _afailed (__near__ unsigned char*, unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	__afailed: near

.segment	"CODE"

	jsr     _ExitTurbo
	stz     $0004
	stz     $0006
	stz     $0006+1
	lda     #$0F
	sta     $0005
	lda     #$96
	sta     $0008
	stz     $0008+1
	lda     #$C0
	sta     $021D
	lda     #$00
	jsr     _SetPattern
	jsr     _Rectangle
	lda     #$FF
	jsr     _FrameRectangle
	jsr     decsp3
	lda     #<(L0029)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0029)
	sta     (sp),y
	lda     #$0A
	sta     (sp)
	ldx     #$00
	jsr     _PutString
	jsr     decsp3
	ldy     #$06
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$0A
	sta     (sp)
	lda     $0016
	ldx     $0016+1
	jsr     _PutString
	jsr     decsp3
	lda     #<(L0034)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0034)
	sta     (sp),y
	lda     #$0A
	sta     (sp)
	lda     $0016
	ldx     $0016+1
	jsr     _PutString
	jsr     decsp4
	lda     #$00
	ldy     #$03
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$0A
	sta     (sp)
	lda     $0016
	ldx     $0016+1
	jsr     _PutDecimal
	lda     #<(L0042)
	ldx     #>(L0042)
	jsr     pushax
	lda     #<(L0044)
	ldx     #>(L0044)
	jsr     _DlgBoxOk
	ldx     #$00
	lda     #$02
	jsr     _exit
	jmp     incsp4

.endproc

