;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_abort
	.import		_exit
	.import		_ExitTurbo
	.import		_DlgBoxOk

.segment	"RODATA"

L0011:
	.byte	$18,$41,$42,$4E,$4F,$52,$4D,$41,$4C,$20,$50,$52,$4F,$47,$52,$41
	.byte	$4D,$00
L0013:
	.byte	$54,$45,$52,$4D,$49,$4E,$41,$54,$49,$4F,$4E,$2E,$1B,$00

; ---------------------------------------------------------------
; void __near__ abort (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_abort: near

.segment	"CODE"

	jsr     _ExitTurbo
	lda     #<(L0011)
	ldx     #>(L0011)
	jsr     pushax
	lda     #<(L0013)
	ldx     #>(L0013)
	jsr     _DlgBoxOk
	ldx     #$00
	lda     #$03
	jmp     _exit

.endproc

