;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_Sleep
	.import		_get_tv
	.export		_sleep

; ---------------------------------------------------------------
; unsigned int __near__ __fastcall__ sleep (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sleep: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp1
	jsr     _get_tv
	and     #$80
	beq     L001B
	lda     #$3C
	bra     L001C
L001B:	lda     #$32
L001C:	sta     (sp)
	ldy     #$04
	jsr     pushwysp
	ldy     #$02
	lda     (sp),y
	jsr     tosumula0
	jsr     _Sleep
	ldx     #$00
	txa
	jmp     incsp3

.endproc

