;
; File generated by co65 v 2.14.0 using model `cc65-module'
;
.fopt		compiler,"co65 v 2.14.0"
.case		on
.debuginfo	off
.export		_atmos_pase_joy

;
; CODE SEGMENT
;
.segment	"CODE"
_atmos_pase_joy:
	.byte	$6A
	.byte	$6F
	.byte	$79
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$08
	.byte	$01
	.byte	$02
	.byte	$20
	.byte	$00
	.byte	$00
	.byte	$00
	.word	_atmos_pase_joy+24
	.word	_atmos_pase_joy+28
	.word	_atmos_pase_joy+29
	.word	_atmos_pase_joy+34
	.byte	$00
	.byte	$00
	.byte	$A9
	.byte	$00
	.byte	$A2
	.byte	$00
	.byte	$60
	.byte	$A9
	.byte	$02
	.byte	$A2
	.byte	$00
	.byte	$60
	.byte	$A8
	.byte	$AD
	.byte	$01
	.byte	$03
	.byte	$48
	.byte	$AD
	.byte	$03
	.byte	$03
	.byte	$48
	.byte	$A9
	.byte	$C0
	.byte	$8D
	.byte	$03
	.byte	$03
	.byte	$A9
	.byte	$80
	.byte	$8D
	.byte	$0F
	.byte	$03
	.byte	$AD
	.byte	$0F
	.byte	$03
	.byte	$8D
	.word	BSS+0
	.byte	$A9
	.byte	$40
	.byte	$8D
	.byte	$0F
	.byte	$03
	.byte	$AD
	.byte	$01
	.byte	$03
	.byte	$8D
	.word	BSS+1
	.byte	$68
	.byte	$8D
	.byte	$03
	.byte	$03
	.byte	$68
	.byte	$8D
	.byte	$0F
	.byte	$03
	.byte	$A2
	.byte	$00
	.byte	$98
	.byte	$D0
	.byte	$06
	.byte	$AD
	.word	BSS+0
	.byte	$49
	.byte	$FF
	.byte	$60
	.byte	$AD
	.word	BSS+1
	.byte	$49
	.byte	$FF
	.byte	$60

;
; DATA SEGMENT
;
.segment	"DATA"
DATA:

;
; BSS SEGMENT
;
.segment	"BSS"
BSS:
	.res	2

;
; ZEROPAGE SEGMENT
;
.import	__ZP_START__		; Linker generated symbol
ZEROPAGE = __ZP_START__

.end
