;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_exit
	.import		_strlen
	.import		_clrscr
	.import		_kbhit
	.import		_gotoxy
	.import		_wherex
	.import		_cputc
	.import		_cputcxy
	.import		_cputsxy
	.import		_cgetc
	.import		_cursor
	.import		_revers
	.import		_textcolor
	.import		_bgcolor
	.import		_bordercolor
	.import		_chline
	.import		_chlinexy
	.import		_cvlinexy
	.import		_cclearxy
	.import		_cputhex8
	.import		_cputhex16
	.import		__ctype
	.import		_toupper
	.import		_brk_a
	.import		_brk_x
	.import		_brk_y
	.import		_brk_sr
	.import		_brk_pc
	.import		_DbgDisAsm
	.import		_DbgDisAsmLen
	.import		_DbgIsRAM
	.import		_DbgMemDump
	.import		_DbgSP
	.import		_DbgCS
	.import		_DbgHI
	.export		_DbgBreakCount
	.export		_DbgBreaks
	.import		_DbgGetBreakSlot
	.import		_DbgIsBreak
	.export		_DbgEntry

.segment	"DATA"

_RegText:
	.byte	$01
	.byte	$00
	.addr	L0004
	.byte	$01
	.byte	$01
	.addr	L0008
	.byte	$01
	.byte	$02
	.addr	L000C
	.byte	$01
	.byte	$03
	.addr	L0010
	.byte	$01
	.byte	$04
	.addr	L0014
	.byte	$01
	.byte	$05
	.addr	L0018
	.byte	$01
	.byte	$06
	.addr	L001C
	.byte	$01
	.byte	$07
	.addr	L0020
_HelpText:
	.byte	$01
	.byte	$00
	.addr	L0024
	.byte	$01
	.byte	$01
	.addr	L0028
	.byte	$01
	.byte	$02
	.addr	L002C
	.byte	$01
	.byte	$03
	.addr	L0030
	.byte	$01
	.byte	$04
	.addr	L0034
	.byte	$01
	.byte	$05
	.addr	L0038
	.byte	$01
	.byte	$06
	.addr	L003C
	.byte	$01
	.byte	$07
	.addr	L0040
	.byte	$01
	.byte	$08
	.addr	L0044
	.byte	$01
	.byte	$09
	.addr	L0048
	.byte	$01
	.byte	$0A
	.addr	L004C
	.byte	$01
	.byte	$0B
	.addr	L0050
	.byte	$01
	.byte	$0C
	.addr	L0054
	.byte	$01
	.byte	$0D
	.addr	L0058
	.byte	$01
	.byte	$0E
	.addr	L005C
	.byte	$01
	.byte	$0F
	.addr	L0060
	.byte	$01
	.byte	$10
	.addr	L0064
	.byte	$01
	.byte	$11
	.addr	L0068
_AsmFrame:
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$00
	.byte	$00
	.byte	$1E
	.byte	$0F
	.byte	$1D
	.byte	$0E
	.byte	$01
	.addr	_AsmHandler
	.byte	$00
	.word	$0000
_RegFrame:
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$1E
	.byte	$00
	.byte	$27
	.byte	$09
	.byte	$08
	.byte	$08
	.byte	$01
	.addr	_RegHandler
	.byte	$08
	.addr	_RegText
_StackFrame:
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$1E
	.byte	$09
	.byte	$27
	.byte	$0F
	.byte	$08
	.byte	$05
	.byte	$01
	.addr	_StackHandler
	.byte	$00
	.word	$0000
_CStackFrame:
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$1E
	.byte	$0F
	.byte	$27
	.byte	$18
	.byte	$08
	.byte	$08
	.byte	$01
	.addr	_CStackHandler
	.byte	$00
	.word	$0000
_DumpFrame:
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$00
	.byte	$0F
	.byte	$1E
	.byte	$18
	.byte	$1D
	.byte	$08
	.byte	$01
	.addr	_DumpHandler
	.byte	$00
	.word	$0000
_HelpFrame:
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$00
	.byte	$00
	.byte	$27
	.byte	$18
	.byte	$26
	.byte	$17
	.byte	$00
	.addr	_HelpHandler
	.byte	$12
	.addr	_HelpText
_Frames:
	.addr	_AsmFrame
	.addr	_RegFrame
	.addr	_StackFrame
	.addr	_CStackFrame
	.addr	_DumpFrame
	.addr	_HelpFrame
_ActiveFrame:
	.word	$FFFF
_ActivePrompt:
	.word	$0000
_DbgBreakCount:
	.byte	$00

.segment	"RODATA"

L002C:
	.byte	$46,$33,$2C,$20,$75,$20,$20,$20,$20,$20,$52,$75,$6E,$20,$75,$6E
	.byte	$74,$69,$6C,$20,$73,$75,$62,$72,$6F,$75,$74,$69,$6E,$65,$20,$72
	.byte	$65,$74,$75,$72,$6E,$73,$00
L023C:
	.byte	$43,$61,$6E,$6E,$6F,$74,$20,$73,$65,$74,$20,$62,$72,$65,$61,$6B
	.byte	$70,$6F,$69,$6E,$74,$20,$2D,$20,$70,$72,$65,$73,$73,$20,$61,$20
	.byte	$6B,$65,$79,$00
L0250:
	.byte	$54,$6F,$6F,$20,$6D,$61,$6E,$79,$20,$62,$72,$65,$61,$6B,$70,$6F
	.byte	$69,$6E,$74,$73,$20,$2D,$20,$70,$72,$65,$73,$73,$20,$61,$20,$6B
	.byte	$65,$79,$00
L0068:
	.byte	$73,$20,$20,$20,$20,$20,$20,$20,$20,$20,$53,$6B,$69,$70,$20,$6E
	.byte	$65,$78,$74,$20,$69,$6E,$73,$74,$72,$75,$63,$74,$69,$6F,$6E,$00
L003C:
	.byte	$31,$2D,$35,$20,$20,$20,$20,$20,$20,$20,$53,$65,$6C,$65,$63,$74
	.byte	$20,$61,$63,$74,$69,$76,$65,$20,$77,$69,$6E,$64,$6F,$77,$00
L005C:
	.byte	$70,$20,$20,$20,$20,$20,$20,$20,$20,$20,$55,$73,$65,$20,$61,$73
	.byte	$20,$6E,$65,$77,$20,$50,$43,$20,$76,$61,$6C,$75,$65,$00
L0054:
	.byte	$66,$20,$20,$20,$20,$20,$20,$20,$20,$20,$46,$6F,$6C,$6C,$6F,$77
	.byte	$20,$69,$6E,$73,$74,$72,$75,$63,$74,$69,$6F,$6E,$00
L0028:
	.byte	$46,$32,$2C,$20,$74,$20,$20,$20,$20,$20,$54,$6F,$67,$67,$6C,$65
	.byte	$20,$62,$72,$65,$61,$6B,$70,$6F,$69,$6E,$74,$00
L0237:
	.byte	$49,$6E,$76,$61,$6C,$69,$64,$20,$69,$6E,$70,$75,$74,$20,$2D,$20
	.byte	$70,$72,$65,$73,$73,$20,$61,$20,$6B,$65,$79,$00
L0171:
	.byte	$50,$72,$65,$73,$73,$20,$61,$6E,$79,$20,$6B,$65,$79,$20,$74,$6F
	.byte	$20,$63,$6F,$6E,$74,$69,$6E,$75,$65,$00
L0030:
	.byte	$46,$34,$2C,$20,$68,$20,$20,$20,$20,$20,$52,$75,$6E,$20,$74,$6F
	.byte	$20,$63,$75,$72,$73,$6F,$72,$00
L0064:
	.byte	$72,$20,$20,$20,$20,$20,$20,$20,$20,$20,$52,$65,$64,$72,$61,$77
	.byte	$20,$73,$63,$72,$65,$65,$6E,$00
L004C:
	.byte	$61,$2F,$7A,$20,$20,$20,$20,$20,$20,$20,$4D,$6F,$76,$65,$20,$75
	.byte	$70,$2F,$64,$6F,$77,$6E,$00
L0048:
	.byte	$43,$75,$72,$73,$6F,$72,$20,$20,$20,$20,$4D,$6F,$76,$65,$20,$75
	.byte	$70,$2F,$64,$6F,$77,$6E,$00
L0058:
	.byte	$6F,$20,$20,$20,$20,$20,$20,$20,$20,$20,$47,$6F,$74,$6F,$20,$6F
	.byte	$72,$69,$67,$69,$6E,$00
L0034:
	.byte	$46,$37,$2C,$20,$73,$70,$61,$63,$65,$20,$53,$74,$65,$70,$20,$69
	.byte	$6E,$74,$6F,$00
L0038:
	.byte	$46,$38,$2C,$20,$65,$6E,$74,$65,$72,$20,$53,$74,$65,$70,$20,$6F
	.byte	$76,$65,$72,$00
L0040:
	.byte	$2B,$20,$20,$20,$20,$20,$20,$20,$20,$20,$50,$61,$67,$65,$20,$64
	.byte	$6F,$77,$6E,$00
L0050:
	.byte	$63,$20,$20,$20,$20,$20,$20,$20,$20,$20,$43,$6F,$6E,$74,$69,$6E
	.byte	$75,$65,$00
L0044:
	.byte	$2D,$20,$20,$20,$20,$20,$20,$20,$20,$20,$50,$61,$67,$65,$20,$75
	.byte	$70,$00
L016D:
	.byte	$50,$72,$65,$73,$73,$20,$46,$31,$20,$66,$6F,$72,$20,$68,$65,$6C
	.byte	$70,$00
L0060:
	.byte	$71,$20,$20,$20,$20,$20,$20,$20,$20,$20,$51,$75,$69,$74,$00
L0024:
	.byte	$46,$31,$2C,$20,$3F,$20,$20,$20,$20,$20,$48,$65,$6C,$70,$00
L0231:
	.byte	$47,$6F,$74,$6F,$3A,$20,$00
L0008:
	.byte	$53,$52,$00
L001C:
	.byte	$43,$53,$00
L0020:
	.byte	$48,$49,$00
L0018:
	.byte	$53,$50,$00
L03EB:
	.byte	$2D,$3E,$00
L0004:
	.byte	$50,$43,$00
L0010:
	.byte	$58,$00
L000C:
	.byte	$41,$00
L0014:
	.byte	$59,$00

.segment	"BSS"

_AsmAddr:
	.res	2,$00
_DumpAddr:
	.res	2,$00
_CStackAddr:
	.res	2,$00
_StackAddr:
	.res	1,$00
_PromptColor:
	.res	1,$00
_PromptLength:
	.res	1,$00
_DbgBreaks:
	.res	48,$00

; ---------------------------------------------------------------
; unsigned char __near__ AsmHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AsmHandler: near

.segment	"CODE"

	jsr     decsp3
L0322:	jsr     _UpdateAsm
	jsr     stax0sp
	jsr     _GetKeyUpdate
	ldy     #$02
	sta     (sp),y
	cmp     #$0A
	jeq     L0353
	cmp     #$0B
	jeq     L034B
	cmp     #$2B
	beq     L032D
	cmp     #$2D
	beq     L0331
	cmp     #$61
	jeq     L034B
	cmp     #$66
	beq     L033D
	cmp     #$67
	beq     L0340
	cmp     #$6F
	beq     L0344
	cmp     #$70
	beq     L0347
	cmp     #$74
	beq     L0337
	cmp     #$7A
	jeq     L0353
	cmp     #$B2
	beq     L0337
	jmp     L054E
L032D:	dey
	lda     (sp),y
	sta     _AsmAddr+1
	dey
	lda     (sp),y
	sta     _AsmAddr
	jmp     L0322
L0331:	jsr     decsp3
	lda     _AsmAddr
	dey
	sta     (sp),y
	iny
	lda     _AsmAddr+1
	sta     (sp),y
	lda     _AsmFrame+9
	ldy     #$00
	sta     (sp),y
	jsr     _AsmBack
	sta     _AsmAddr
	stx     _AsmAddr+1
	jmp     L0322
L0337:	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     pushax
	jsr     _DbgToggleUserBreak
	jmp     L0322
L033D:	jsr     _AsmFollow
	jmp     L0322
L0340:	lda     #<(_AsmAddr)
	ldx     #>(_AsmAddr)
	jsr     pushax
	jsr     _InputGoto
	jmp     L0322
L0344:	jsr     _AsmHome
	jmp     L0322
L0347:	lda     _AsmAddr
	sta     _brk_pc
	lda     _AsmAddr+1
	sta     _brk_pc+1
	jmp     L0322
L034B:	jsr     decsp3
	lda     _AsmAddr
	dey
	sta     (sp),y
	iny
	lda     _AsmAddr+1
	sta     (sp),y
	lda     #$01
	ldy     #$00
	sta     (sp),y
	jsr     _AsmBack
	sta     _AsmAddr
	stx     _AsmAddr+1
	jmp     L0322
L0353:	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     _DbgDisAsmLen
	clc
	adc     _AsmAddr
	sta     _AsmAddr
	txa
	adc     _AsmAddr+1
	sta     _AsmAddr+1
	jmp     L0322
L054E:	ldx     #$00
	lda     (sp),y
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ RegHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_RegHandler: near

.segment	"CODE"

	jmp     _GetKeyUpdate

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ StackHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_StackHandler: near

.segment	"CODE"

	jsr     decsp1
	lda     _StackFrame+9
	jsr     pusha
L03B3:	jsr     _GetKeyUpdate
	ldy     #$01
	sta     (sp),y
	cmp     #$0A
	beq     L03CC
	cmp     #$0B
	beq     L03C7
	cmp     #$2B
	beq     L03BC
	cmp     #$2D
	beq     L03C0
	cmp     #$61
	beq     L03C7
	cmp     #$6F
	beq     L03C4
	cmp     #$7A
	beq     L03CC
	jmp     L054F
L03BC:	dey
	lda     (sp),y
	clc
	adc     _StackAddr
	sta     _StackAddr
	jmp     L03BA
L03C0:	dey
	lda     (sp),y
	eor     #$FF
	sec
	adc     _StackAddr
	sta     _StackAddr
	jmp     L03BA
L03C4:	jsr     _StackHome
	jmp     L03BA
L03C7:	dec     _StackAddr
	jmp     L03BA
L03CC:	inc     _StackAddr
	jmp     L03BA
L054F:	ldx     #$00
	lda     (sp),y
	jmp     incsp2
L03BA:	jsr     _UpdateStack
	jmp     L03B3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ CStackHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_CStackHandler: near

.segment	"CODE"

	jsr     decsp1
	lda     _CStackFrame+9
	asl     a
	jsr     pusha
L03F7:	jsr     _GetKeyUpdate
	ldy     #$01
	sta     (sp),y
	cmp     #$0A
	beq     L0412
	cmp     #$0B
	beq     L040B
	cmp     #$2B
	beq     L0400
	cmp     #$2D
	beq     L0404
	cmp     #$61
	beq     L040B
	cmp     #$6F
	beq     L0408
	cmp     #$7A
	beq     L0412
	jmp     L0550
L0400:	dey
	lda     (sp),y
	clc
	adc     _CStackAddr
	sta     _CStackAddr
	tya
	adc     _CStackAddr+1
	sta     _CStackAddr+1
	jmp     L03FE
L0404:	dey
	lda     (sp),y
	eor     #$FF
	sec
	adc     _CStackAddr
	sta     _CStackAddr
	lda     #$FF
	adc     _CStackAddr+1
	sta     _CStackAddr+1
	jmp     L03FE
L0408:	jsr     _CStackHome
	jmp     L03FE
L040B:	lda     _CStackAddr
	sec
	sbc     #$02
	sta     _CStackAddr
	bcs     L03FE
	dec     _CStackAddr+1
	jmp     L03FE
L0412:	lda     #$02
	clc
	adc     _CStackAddr
	sta     _CStackAddr
	bcc     L03FE
	inc     _CStackAddr+1
	jmp     L03FE
L0550:	ldx     #$00
	lda     (sp),y
	jmp     incsp2
L03FE:	jsr     _UpdateCStack
	jmp     L03F7

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ DumpHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DumpHandler: near

.segment	"CODE"

	jsr     decsp1
	ldx     #$00
	lda     _DumpFrame+9
	jsr     shlax3
	jsr     pushax
L043A:	jsr     _GetKeyUpdate
	ldy     #$02
	sta     (sp),y
	cmp     #$0A
	beq     L0459
	cmp     #$0B
	beq     L0452
	cmp     #$2B
	beq     L0443
	cmp     #$2D
	beq     L0447
	cmp     #$61
	beq     L0452
	cmp     #$67
	beq     L044B
	cmp     #$6F
	beq     L044F
	cmp     #$7A
	beq     L0459
	jmp     L0551
L0443:	dey
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     _DumpAddr
	sta     _DumpAddr
	txa
	adc     _DumpAddr+1
	sta     _DumpAddr+1
	jmp     L0441
L0447:	dey
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	eor     #$FF
	sec
	adc     _DumpAddr
	sta     _DumpAddr
	txa
	eor     #$FF
	adc     _DumpAddr+1
	sta     _DumpAddr+1
	jmp     L0441
L044B:	lda     #<(_DumpAddr)
	ldx     #>(_DumpAddr)
	jsr     pushax
	jsr     _InputGoto
	jmp     L0441
L044F:	jsr     _DumpHome
	jmp     L0441
L0452:	lda     _DumpAddr
	sec
	sbc     #$08
	sta     _DumpAddr
	bcs     L0441
	dec     _DumpAddr+1
	jmp     L0441
L0459:	lda     #$08
	clc
	adc     _DumpAddr
	sta     _DumpAddr
	bcc     L0441
	inc     _DumpAddr+1
	jmp     L0441
L0551:	ldx     #$00
	lda     (sp),y
	jmp     incsp3
L0441:	jsr     _UpdateDump
	jmp     L043A

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ HelpHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_HelpHandler: near

.segment	"CODE"

	lda     _ActiveFrame
	ldx     _ActiveFrame+1
	jsr     pushax
	jsr     decsp3
	lda     #$05
	ldy     #$01
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #$01
	ldy     #$00
	sta     (sp),y
	jsr     _ActivateFrame
	jsr     _AnyKeyPrompt
	jsr     _cgetc
	ldy     #$00
	lda     (sp),y
	jsr     pusha
	jsr     _Redraw
	ldx     #$00
	txa
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ DisplayPrompt (__near__ unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DisplayPrompt: near

.segment	"CODE"

	jsr     decsp1
	lda     #$07
	jsr     _textcolor
	ldy     #$00
	sta     (sp),y
	lda     _ActivePrompt
	ora     _ActivePrompt+1
	beq     L0152
	lda     _PromptColor
	jsr     _textcolor
	jsr     decsp2
	lda     #$28
	sec
	sbc     _PromptLength
	lsr     a
	ldy     #$01
	sta     (sp),y
	lda     #$18
	dey
	sta     (sp),y
	lda     _PromptLength
	jsr     _chlinexy
L0152:	ldy     #$02
	lda     (sp),y
	sta     _ActivePrompt+1
	dey
	lda     (sp),y
	sta     _ActivePrompt
	dey
	lda     (sp),y
	sta     _PromptColor
	lda     _ActivePrompt
	ldx     _ActivePrompt+1
	jsr     _strlen
	sta     _PromptLength
	lda     #$07
	jsr     _textcolor
	jsr     decsp2
	lda     #$28
	sec
	sbc     _PromptLength
	lsr     a
	ldy     #$01
	sta     (sp),y
	lda     #$18
	dey
	sta     (sp),y
	lda     _ActivePrompt
	ldx     _ActivePrompt+1
	jsr     _cputsxy
	lda     _PromptColor
	jsr     _textcolor
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ SingleStep (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_SingleStep: near

.segment	"CODE"

	jsr     decsp1
	lda     _brk_pc
	sta     ptr1
	lda     _brk_pc+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	cmp     #$10
	beq     L0494
	cmp     #$20
	jeq     L04A8
	cmp     #$30
	beq     L0494
	cmp     #$40
	beq     L04A3
	cmp     #$4C
	beq     L047E
	cmp     #$50
	beq     L0494
	cmp     #$60
	beq     L04A0
	cmp     #$6C
	beq     L0482
	cmp     #$70
	beq     L0494
	cmp     #$90
	beq     L0494
	cmp     #$B0
	beq     L0494
	cmp     #$D0
	beq     L0494
	cmp     #$F0
	beq     L0494
	jmp     L047C
L047E:	jsr     _GetArg16
	jmp     L0553
L0482:	jsr     _GetArg16
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jmp     L0553
L0494:	lda     _brk_pc
	ldx     _brk_pc+1
	iny
	jsr     ldaidx
	dey
	sta     (sp),y
	lda     (sp),y
	beq     L047C
	ldx     #$00
	lda     (sp),y
	bpl     L049D
	dex
L049D:	clc
	adc     _brk_pc
	pha
	txa
	adc     _brk_pc+1
	tax
	pla
	clc
	adc     #$02
	bcc     L049E
	inx
L049E:	jsr     pushax
	jsr     _DbgSetTmpBreak
	jmp     L047C
L04A0:	jsr     _SetRTSBreak
	jmp     incsp2
L04A3:	lda     #$01
	jsr     pusha
	jsr     _GetStack16
	jmp     L0553
L04A8:	iny
	lda     (sp),y
	beq     L047C
	jsr     _GetArg16
	jmp     L0553
L047C:	lda     _brk_pc
	ldx     _brk_pc+1
	jsr     pushax
	lda     _brk_pc
	ldx     _brk_pc+1
	jsr     _DbgDisAsmLen
	jsr     tosaddax
L0553:	jsr     pushax
	jsr     _DbgSetTmpBreak
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ RedrawStatic (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_RedrawStatic: near

.segment	"CODE"

	lda     #$FF
	sta     _ActiveFrame
	sta     _ActiveFrame+1
	lda     #$00
	jsr     _bordercolor
	lda     #$00
	jsr     _bgcolor
	jsr     _clrscr
	lda     #$00
	jsr     _cursor
	lda     #$07
	jsr     _textcolor
	jsr     _DrawFrames
	jsr     _HelpPrompt
	jsr     decsp3
	ldy     #$03
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	tay
	sta     (sp),y
	jsr     _ActivateFrame
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ Redraw (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Redraw: near

.segment	"CODE"

	ldy     #$00
	lda     (sp),y
	jsr     pusha
	jsr     _RedrawStatic
	jsr     _UpdateAsm
	jsr     _UpdateReg
	jsr     _UpdateStack
	jsr     _UpdateCStack
	jsr     _UpdateDump
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ GetKeyUpdate (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_GetKeyUpdate: near

.segment	"BSS"

L04CA:
	.res	1,$00

.segment	"CODE"

	jmp     L04CD
L0554:	lda     L04CA
	beq     L04D3
	cmp     #$01
	beq     L04D6
	cmp     #$02
	beq     L04D9
	cmp     #$03
	beq     L04DC
	jmp     L0555
L04D3:	jsr     _UpdateAsm
	jmp     L0555
L04D6:	jsr     _UpdateStack
	jmp     L0555
L04D9:	jsr     _UpdateCStack
	jmp     L0555
L04DC:	jsr     _UpdateDump
L0555:	lda     L04CA
	clc
	adc     #$01
	and     #$03
	sta     L04CA
L04CD:	jsr     _kbhit
	tax
	beq     L0554
	jmp     _cgetc

.endproc

; ---------------------------------------------------------------
; void __near__ DrawFrame (register __near__ struct $anon-struct-0008*, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DrawFrame: near

.segment	"CODE"

	ldy     #$01
	ldx     #$04
	jsr     regswap2
	ldy     #$0B
	jsr     subysp
	ldy     #$0B
	lda     (sp),y
	beq     L00CF
	lda     #$07
	jsr     _textcolor
	ldy     #$00
	sta     (sp),y
	lda     #$2B
	ldy     #$07
	sta     (sp),y
	dey
	sta     (sp),y
	dey
	sta     (sp),y
	jmp     L0557
L00CF:	lda     #$07
	jsr     _textcolor
	ldy     #$00
	sta     (sp),y
	lda     (regbank+4),y
	ldy     #$07
	sta     (sp),y
	ldy     #$01
	lda     (regbank+4),y
	ldy     #$06
	sta     (sp),y
	ldy     #$02
	lda     (regbank+4),y
	ldy     #$05
	sta     (sp),y
	ldy     #$03
	lda     (regbank+4),y
L0557:	ldy     #$04
	sta     (sp),y
	lda     (regbank+4),y
	dey
	sta     (sp),y
	ldy     #$05
	lda     (regbank+4),y
	ldy     #$02
	sta     (sp),y
	ldy     #$08
	lda     (regbank+4),y
	ldy     #$01
	sta     (sp),y
	jsr     decsp2
	ldy     #$05
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	ldy     #$04
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	ldy     #$09
	lda     (sp),y
	jsr     _cputcxy
	ldy     #$01
	lda     (sp),y
	jsr     _chline
	ldy     #$06
	lda     (sp),y
	jsr     _cputc
	jsr     decsp2
	ldy     #$05
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	ldy     #$04
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	ldy     #$00
	sta     (sp),y
	ldy     #$09
	lda     (regbank+4),y
	jsr     _cvlinexy
	ldy     #$05
	lda     (sp),y
	jsr     _cputc
	ldy     #$01
	lda     (sp),y
	jsr     _chline
	ldy     #$04
	lda     (sp),y
	jsr     _cputc
	jsr     decsp2
	ldy     #$06
	lda     (regbank+4),y
	ldy     #$01
	sta     (sp),y
	ldy     #$04
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	ldy     #$09
	lda     (regbank+4),y
	jsr     _cvlinexy
	lda     #$07
	jsr     _textcolor
	ldy     #$0D
	lda     (regbank+4),y
	ldy     #$08
	sta     (sp),y
	ldy     #$0F
	lda     (regbank+4),y
	tax
	dey
	lda     (regbank+4),y
	ldy     #$09
	jsr     staxysp
	jmp     L010C
L010A:	jsr     decsp2
	ldy     #$05
	lda     (sp),y
	jsr     pusha0
	ldy     #$0E
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     (ptr1,x)
	jsr     tosadda0
	ldy     #$01
	sta     (sp),y
	ldy     #$04
	lda     (sp),y
	jsr     pusha0
	ldy     #$0E
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$01
	lda     (ptr1),y
	jsr     tosadda0
	ldy     #$00
	sta     (sp),y
	ldy     #$0C
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$03
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _cputsxy
	ldy     #$09
	ldx     #$00
	lda     #$04
	jsr     addeqysp
L010C:	ldy     #$08
	lda     (sp),y
	pha
	sec
	sbc     #$01
	sta     (sp),y
	pla
	tax
	bne     L010A
	lda     (sp,x)
	jsr     _textcolor
	ldy     #$0C
	lda     (sp),y
	sta     regbank+4
	iny
	lda     (sp),y
	sta     regbank+5
	iny
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ DrawFrames (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DrawFrames: near

.segment	"CODE"

	jsr     decsp3
	lda     #$00
	ldy     #$02
L0559:	sta     (sp),y
	cmp     #$06
	bcs     L0117
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L055A
	inx
	clc
L055A:	adc     #<(_Frames)
	sta     ptr1
	txa
	adc     #>(_Frames)
	sta     ptr1+1
	dey
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     stax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0A
	lda     (ptr1),y
	beq     L0118
	jsr     decsp3
	ldy     #$04
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$00
	tay
	sta     (sp),y
	jsr     _DrawFrame
L0118:	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	jmp     L0559
L0117:	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ ActivateFrame (int, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ActivateFrame: near

.segment	"CODE"

	jsr     decsp1
	lda     regbank+4
	ldx     regbank+5
	jsr     pushax
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	cpx     _ActiveFrame+1
	bne     L055D
	cmp     _ActiveFrame
	jeq     L012A
L055D:	ldx     _ActiveFrame+1
	bmi     L012C
	jsr     decsp3
	lda     _ActiveFrame
	ldx     _ActiveFrame+1
	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     #<(_Frames)
	sta     ptr1
	lda     tmp1
	adc     #>(_Frames)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	iny
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$00
	tay
	sta     (sp),y
	jsr     _DrawFrame
L012C:	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     _ActiveFrame
	stx     _ActiveFrame+1
	txa
	jmi     L0132
	lda     _ActiveFrame
	ldx     _ActiveFrame+1
	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     #<(_Frames)
	sta     ptr1
	lda     tmp1
	adc     #>(_Frames)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	sta     regbank+4
	stx     regbank+4+1
	ldy     #$03
	lda     (sp),y
	beq     L013C
	ldy     #$05
	lda     (regbank+4),y
	clc
	adc     #$01
	ldy     #$02
L055C:	sta     (sp),y
	lda     (sp),y
	jsr     pusha0
	ldy     #$07
	lda     (regbank+4),y
	jsr     tosicmp0
	bcs     L013C
	jsr     decsp2
	ldy     #$04
	lda     (regbank+4),y
	clc
	adc     #$01
	ldy     #$01
	sta     (sp),y
	ldy     #$04
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	ldy     #$08
	lda     (regbank+4),y
	jsr     _cclearxy
	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	jmp     L055C
L013C:	jsr     decsp3
	lda     regbank+4
	ldy     #$01
	sta     (sp),y
	iny
	lda     regbank+4+1
	sta     (sp),y
	lda     #$01
	ldy     #$00
	sta     (sp),y
	jsr     _DrawFrame
L0132:	lda     _ActivePrompt
	ldx     _ActivePrompt+1
	jsr     pushax
	jsr     _DisplayPrompt
L012A:	ldy     #$00
	lda     (sp),y
	sta     regbank+4
	iny
	lda     (sp),y
	sta     regbank+5
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; void __near__ HelpPrompt (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_HelpPrompt: near

.segment	"CODE"

	lda     #<(L016D)
	ldx     #>(L016D)
	jsr     pushax
	jmp     _DisplayPrompt

.endproc

; ---------------------------------------------------------------
; void __near__ AnyKeyPrompt (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AnyKeyPrompt: near

.segment	"CODE"

	lda     #<(L0171)
	ldx     #>(L0171)
	jsr     pushax
	jmp     _DisplayPrompt

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ IsAbortKey (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_IsAbortKey: near

.segment	"CODE"

	ldx     #$00
	lda     (sp,x)
	cmp     #$1B
	bne     L055F
	lda     #$01
	jmp     incsp1
L055F:	lda     (sp,x)
	cmp     #$03
	bne     L0560
	lda     #$01
	jmp     incsp1
L0560:	txa
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Input (__near__ unsigned char*, __near__ unsigned char*, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Input: near

.segment	"CODE"

	ldy     #$0A
	jsr     subysp
	lda     #$00
	ldy     #$01
	sta     (sp),y
	lda     #$18
	dey
	sta     (sp),y
	lda     #$28
	jsr     _cclearxy
	lda     #$07
	jsr     _textcolor
	ldy     #$05
	sta     (sp),y
	jsr     decsp2
	lda     #$00
	ldy     #$01
	sta     (sp),y
	lda     #$18
	dey
	sta     (sp),y
	ldy     #$0E
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _cputsxy
	lda     #$07
	jsr     _textcolor
	jsr     _wherex
	ldy     #$03
	sta     (sp),y
	lda     #$01
	jsr     _cursor
	ldy     #$04
	sta     (sp),y
	lda     #$00
	ldy     #$01
	sta     (sp),y
	iny
	sta     (sp),y
L0191:	jsr     _cgetc
	ldy     #$00
	sta     (sp),y
	tay
	lda     __ctype,y
	and     #$07
	beq     L0196
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	ldy     #$08
	cmp     (sp),y
	bcs     L0196
	ldy     #$02
	lda     (sp),y
	clc
	ldy     #$09
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$00
	lda     (sp),y
	sta     (ptr1),y
	jsr     decsp2
	ldy     #$04
	lda     (sp),y
	clc
	iny
	adc     (sp),y
	ldy     #$01
	sta     (sp),y
	lda     #$18
	dey
	sta     (sp),y
	ldy     #$02
	lda     (sp),y
	jsr     _cputcxy
	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	jmp     L0564
L0196:	ldy     #$02
	lda     (sp),y
	beq     L01AF
	ldy     #$00
	lda     (sp),y
	cmp     #$7F
	bne     L056D
	ldy     #$02
	lda     (sp),y
	sec
	sbc     #$01
	sta     (sp),y
	jsr     decsp2
	ldy     #$04
	lda     (sp),y
	clc
	iny
	adc     (sp),y
	ldy     #$01
	sta     (sp),y
	lda     #$18
	dey
	sta     (sp),y
	lda     #$20
	jsr     _cputcxy
	ldy     #$02
	lda     (sp),y
	clc
	iny
	adc     (sp),y
	jsr     pusha
	lda     #$18
	jsr     _gotoxy
	jmp     L01C4
L01AF:	tay
L056D:	lda     (sp),y
	cmp     #$0A
	bne     L056B
	ldy     #$02
	lda     (sp),y
	clc
	ldy     #$09
	adc     (sp),y
	sta     ptr1
	lda     #$00
	iny
	adc     (sp),y
	sta     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	lda     #$01
	jmp     L056C
L056B:	lda     (sp),y
	jsr     pusha
	jsr     _IsAbortKey
	tax
	beq     L01C4
	lda     #$02
L056C:	ldy     #$01
L0564:	sta     (sp),y
L01C4:	ldy     #$01
	lda     (sp),y
	jeq     L0191
	ldy     #$04
	lda     (sp),y
	jsr     _cursor
	ldy     #$05
	lda     (sp),y
	jsr     _textcolor
	jsr     _DrawFrames
	lda     _ActiveFrame
	ldx     _ActiveFrame+1
	ldy     #$06
	jsr     staxysp
	lda     #$FF
	sta     _ActiveFrame
	sta     _ActiveFrame+1
	jsr     decsp3
	ldy     #$0A
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$00
	tay
	sta     (sp),y
	jsr     _ActivateFrame
	ldy     #$01
	lda     (sp),y
	cmp     #$01
	jsr     booleq
	ldy     #$0D
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ InputHex (__near__ unsigned char*, __near__ unsigned int*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InputHex: near

.segment	"CODE"

	ldy     #$0F
	jsr     subysp
	ldy     #$12
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$03
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     sp
	ldx     sp+1
	clc
	adc     #$0A
	bcc     L01DE
	inx
L01DE:	ldy     #$01
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$04
	ldy     #$00
	sta     (sp),y
	jsr     _Input
	tax
	jeq     L0225
	ldy     #$05
	lda     (sp),y
	tay
	lda     __ctype,y
	and     #$08
	bne     L0572
	tax
	jmp     L0225
L0572:	lda     sp
	ldx     sp+1
	clc
	adc     #$05
	bcc     L01F2
	inx
L01F2:	ldy     #$03
	jsr     staxysp
	ldy     #$00
	tya
	sta     (sp),y
	iny
	sta     (sp),y
	jmp     L01F7
L01F5:	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     shlax4
	jsr     stax0sp
	ldy     #$02
	lda     (sp),y
	tay
	lda     __ctype,y
	and     #$04
	beq     L020A
	ldy     #$02
	lda     (sp),y
	sec
	sbc     #$30
	jmp     L056F
L020A:	ldy     #$02
	lda     (sp),y
	ldx     #$00
	jsr     _toupper
	sec
	sbc     #$37
	ldy     #$02
L056F:	sta     (sp),y
	ldx     #$00
	jsr     addeq0sp
	ldy     #$03
	ldx     #$00
	lda     #$01
	jsr     addeqysp
L01F7:	ldy     #$04
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$00
	lda     (ptr1),y
	ldy     #$02
	sta     (sp),y
	tax
	beq     L056E
	lda     (sp),y
	tay
	lda     __ctype,y
	and     #$08
	bne     L01F5
L056E:	ldy     #$0B
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	ldx     #$00
	tya
L0225:	ldy     #$0E
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ ErrorPrompt (__near__ unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ErrorPrompt: near

.segment	"CODE"

	lda     _ActivePrompt
	ldx     _ActivePrompt+1
	jsr     pushax
	ldy     #$05
	jsr     pushwysp
	jsr     _DisplayPrompt
	jsr     _cgetc
	jsr     pushw0sp
	jsr     _DisplayPrompt
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ InputGoto (__near__ unsigned int*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InputGoto: near

.segment	"CODE"

	jsr     decsp5
	lda     #<(L0231)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L0231)
	sta     (sp),y
	ldy     #$06
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	jsr     _InputHex
	ldy     #$00
	sta     (sp),y
	lda     (sp),y
	bne     L0577
	lda     #<(L0237)
	ldx     #>(L0237)
	jsr     pushax
	jsr     _ErrorPrompt
L0577:	ldx     #$00
	lda     (sp,x)
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ BreakInRomError (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_BreakInRomError: near

.segment	"CODE"

	lda     #<(L023C)
	ldx     #>(L023C)
	jsr     pushax
	jmp     _ErrorPrompt

.endproc

; ---------------------------------------------------------------
; void __near__ DbgSetTmpBreak (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DbgSetTmpBreak: near

.segment	"CODE"

	jsr     _DbgGetBreakSlot
	jsr     pushax
	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$00
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     #$80
	ldy     #$03
	sta     (ptr1),y
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ DbgToggleUserBreak (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DbgToggleUserBreak: near

.segment	"CODE"

	lda     regbank+4
	ldx     regbank+5
	jsr     pushax
	ldy     #$05
	jsr     pushwysp
	jsr     _DbgIsBreak
	sta     regbank+4
	stx     regbank+4+1
	lda     regbank+4
	ora     regbank+4+1
	beq     L0247
	lda     #$00
	ldy     #$03
	sta     (regbank+4),y
	dec     _DbgBreakCount
	jmp     L0257
L0247:	lda     _DbgBreakCount
	cmp     #$0A
	bcc     L024D
	lda     #<(L0250)
	ldx     #>(L0250)
	jsr     pushax
	jsr     _ErrorPrompt
	jmp     L0257
L024D:	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _DbgIsRAM
	stx     tmp1
	ora     tmp1
	bne     L0253
	jsr     _BreakInRomError
	jmp     L0257
L0253:	jsr     _DbgGetBreakSlot
	sta     regbank+4
	stx     regbank+4+1
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$00
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	tya
	ldy     #$03
	sta     (regbank+4),y
	inc     _DbgBreakCount
L0257:	ldy     #$00
	lda     (sp),y
	sta     regbank+4
	iny
	lda     (sp),y
	sta     regbank+5
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ DbgResetTmpBreaks (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DbgResetTmpBreaks: near

.segment	"CODE"

	jsr     decsp1
	lda     #<(_DbgBreaks)
	ldx     #>(_DbgBreaks)
	jsr     pushax
	lda     #$00
	ldy     #$02
L0579:	sta     (sp),y
	cmp     #$0A
	bcs     L0262
	dey
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$03
	lda     (ptr1),y
	cmp     #$80
	bne     L0269
	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	tya
	ldy     #$03
	sta     (ptr1),y
L0269:	ldx     #$00
	lda     #$04
	jsr     addeq0sp
	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	jmp     L0579
L0262:	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ DbgTmpBreaksOk (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DbgTmpBreaksOk: near

.segment	"CODE"

	jsr     decsp1
	lda     #<(_DbgBreaks)
	ldx     #>(_DbgBreaks)
	jsr     pushax
	lda     #$00
	ldy     #$02
L057A:	sta     (sp),y
	ldx     #$00
	lda     (sp),y
	cmp     #$0A
	bcs     L057C
	dey
	lda     (sp),y
	sta     ptr1+1
	lda     (sp,x)
	sta     ptr1
	ldy     #$03
	lda     (ptr1),y
	cmp     #$80
	bne     L0278
	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	lda     (sp,x)
	sta     ptr1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _DbgIsRAM
	stx     tmp1
	ora     tmp1
	bne     L0278
	jsr     _BreakInRomError
	jsr     _DbgResetTmpBreaks
	ldx     #$00
	txa
	jmp     incsp3
L0278:	ldx     #$00
	lda     #$04
	jsr     addeq0sp
	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	jmp     L057A
L057C:	lda     #$01
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ AsmBack (unsigned int, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AsmBack: near

.segment	"CODE"

	ldy     #$43
	jsr     subysp
	lda     #$06
	jsr     pusha0
L0285:	lda     #$00
	ldy     #$02
	sta     (sp),y
	ldy     #$49
	jsr     pushwysp
	ldy     #$47
	ldx     #$00
	lda     (sp),y
	jsr     mulax3
	jsr     tossubax
	sec
	ldy     #$00
	sbc     (sp),y
	pha
	txa
	iny
	sbc     (sp),y
	tax
	pla
	ldy     #$43
	jsr     staxysp
L028E:	ldy     #$44
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _DbgDisAsmLen
	ldy     #$43
	jsr     addeqysp
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L0580
	inx
	clc
L0580:	adc     #$03
	bcc     L0297
	inx
	clc
L0297:	adc     sp
	sta     ptr1
	txa
	adc     sp+1
	sta     ptr1+1
	ldy     #$44
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$00
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	iny
	lda     (sp),y
	clc
	adc     #$01
	and     #$1F
	sta     (sp),y
	ldy     #$44
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$46
	cmp     (sp),y
	txa
	iny
	sbc     (sp),y
	bcc     L028E
	ldy     #$44
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$46
	cmp     (sp),y
	bne     L0582
	txa
	iny
	cmp     (sp),y
	beq     L02A0
L0582:	ldy     #$01
	lda     (sp),y
	bne     L0584
	dey
	lda     (sp),y
	cmp     #$0C
	bne     L0584
L02A0:	ldy     #$02
	ldx     #$00
	lda     (sp),y
	sec
	ldy     #$45
	sbc     (sp),y
	sec
	sbc     #$01
	and     #$1F
	asl     a
	bcc     L0581
	inx
	clc
L0581:	adc     #$03
	bcc     L02A7
	inx
	clc
L02A7:	adc     sp
	sta     ptr1
	txa
	adc     sp+1
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jmp     L0286
L0584:	ldx     #$00
	lda     #$01
	jsr     addeq0sp
	jmp     L0285
L0286:	ldy     #$48
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ UpdateAsm (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateAsm: near

.segment	"CODE"

	ldy     #$2A
	jsr     subysp
	lda     _AsmFrame+8
	jsr     pusha
	lda     _AsmFrame+4
	clc
	adc     #$01
	jsr     pusha
	jsr     decsp3
	lda     _AsmAddr
	ldy     #$01
	sta     (sp),y
	iny
	lda     _AsmAddr+1
	sta     (sp),y
	tya
	ldy     #$00
	sta     (sp),y
	jsr     _AsmBack
	jsr     pushax
	lda     _AsmFrame+5
	clc
	adc     #$01
	ldy     #$04
L0587:	sta     (sp),y
	cmp     _AsmFrame+7
	jcs     L02B3
	jsr     decsp4
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     sp
	ldx     sp+1
	clc
	adc     #$0A
	bcc     L02BF
	inx
L02BF:	ldy     #$00
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$07
	lda     (sp),y
	jsr     _DbgDisAsm
	ldy     #$05
	sta     (sp),y
	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	cpx     _brk_pc+1
	bne     L02C1
	cmp     _brk_pc
	bne     L02C1
	lda     #$2D
	ldy     #$0A
	sta     (sp),y
	lda     #$3E
	iny
	sta     (sp),y
L02C1:	jsr     pushw0sp
	jsr     _DbgIsBreak
	stx     tmp1
	ora     tmp1
	beq     L02CB
	lda     #$2A
	ldy     #$0B
	sta     (sp),y
L02CB:	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	cpx     _AsmAddr+1
	bne     L02D2
	cmp     _AsmAddr
	bne     L02D2
	lda     #$01
	jsr     _revers
	jsr     decsp2
	lda     #$01
	tay
	sta     (sp),y
	ldy     #$06
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	lda     sp
	ldx     sp+1
	clc
	adc     #$08
	bcc     L02DA
	inx
L02DA:	jsr     _cputsxy
	lda     #$00
	jsr     _revers
	jmp     L02DD
L02D2:	jsr     decsp2
	lda     #$01
	iny
	sta     (sp),y
	ldy     #$06
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	lda     sp
	ldx     sp+1
	clc
	adc     #$08
	bcc     L02E2
	inx
L02E2:	jsr     _cputsxy
L02DD:	ldy     #$05
	lda     (sp),y
	ldx     #$00
	jsr     addeq0sp
	ldy     #$04
	clc
	lda     #$01
	adc     (sp),y
	jmp     L0587
L02B3:	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$2E
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ AsmArg16 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AsmArg16: near

.segment	"CODE"

	lda     _AsmAddr
	ldx     _AsmAddr+1
	clc
	adc     #$01
	bcc     L02E9
	inx
L02E9:	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ AsmFollow (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AsmFollow: near

.segment	"CODE"

	lda     _AsmAddr
	sta     ptr1
	lda     _AsmAddr+1
	sta     ptr1+1
	ldx     #$00
	lda     (ptr1,x)
	cmp     #$10
	beq     L02F9
	cmp     #$20
	beq     L02EF
	cmp     #$30
	beq     L02F9
	cmp     #$40
	beq     L058A
	cmp     #$4C
	beq     L02EF
	cmp     #$50
	beq     L02F9
	cmp     #$60
	beq     L0589
	cmp     #$6C
	beq     L02F5
	cmp     #$70
	beq     L02F9
	cmp     #$90
	beq     L02F9
	cmp     #$B0
	beq     L02F9
	cmp     #$D0
	beq     L02F9
	cmp     #$F0
	beq     L02F9
	rts
L02EF:	jsr     _AsmArg16
	jmp     L058B
L02F5:	jsr     _AsmArg16
	jmp     L0592
L02F9:	lda     _AsmAddr
	ldx     _AsmAddr+1
	clc
	adc     #$02
	bcc     L030A
	inx
L030A:	jsr     pushax
	lda     _AsmAddr
	ldx     _AsmAddr+1
	clc
	adc     #$01
	bcc     L030C
	inx
L030C:	ldy     #$00
	jsr     ldaidx
	jsr     tosaddax
	jmp     L058B
L0589:	lda     _DbgSP
	clc
	adc     #$01
	bcc     L0313
	inx
L0313:	inx
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	clc
	adc     #$01
	bcc     L058B
	inx
	jmp     L058B
L058A:	lda     _DbgSP
	clc
	adc     #$02
	bcc     L031A
	inx
L031A:	inx
L0592:	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
L058B:	sta     _AsmAddr
	stx     _AsmAddr+1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ AsmHome (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AsmHome: near

.segment	"CODE"

	lda     _brk_pc
	sta     _AsmAddr
	lda     _brk_pc+1
	sta     _AsmAddr+1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ InitAsm (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitAsm: near

.segment	"CODE"

	jsr     _AsmHome
	jmp     _UpdateAsm

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ UpdateReg (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateReg: near

.segment	"CODE"

	lda     _RegFrame+4
	clc
	adc     #$05
	jsr     pusha
	ldy     #$00
	lda     (sp),y
	clc
	adc     #$02
	jsr     pusha
	lda     _RegFrame+5
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _brk_pc
	ldx     _brk_pc+1
	jsr     _cputhex16
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _brk_sr
	jsr     _cputhex8
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _brk_a
	jsr     _cputhex8
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _brk_x
	jsr     _cputhex8
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _brk_y
	jsr     _cputhex8
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _DbgSP
	jsr     _cputhex8
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _DbgCS
	ldx     _DbgCS+1
	jsr     _cputhex16
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _DbgHI
	ldx     _DbgHI+1
	jsr     _cputhex16
	ldx     #$00
	txa
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ InitReg (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitReg: near

.segment	"CODE"

	jmp     _UpdateReg

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ UpdateStack (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateStack: near

.segment	"CODE"

	lda     _StackAddr
	jsr     pusha
	lda     _StackFrame+4
	clc
	adc     #$01
	jsr     pusha
	ldy     #$00
	lda     (sp),y
	clc
	adc     #$06
	jsr     pusha
	jsr     decsp1
	lda     _StackFrame+7
	sec
	sbc     #$01
	ldy     #$00
L0594:	sta     (sp),y
	ldx     #$00
	lda     (sp),y
	sec
	sbc     _StackFrame+5
	sta     tmp1
	lda     tmp1
	beq     L0395
	bcc     L0395
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     _gotoxy
	ldy     #$03
	lda     (sp),y
	jsr     _cputhex8
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     _gotoxy
	ldy     #$03
	lda     (sp),y
	sta     ptr1
	lda     #$01
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     _cputhex8
	ldy     #$03
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	ldy     #$00
	lda     (sp),y
	sec
	sbc     #$01
	jmp     L0594
L0395:	ldy     #$03
	lda     (sp),y
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ StackHome (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_StackHome: near

.segment	"CODE"

	lda     _DbgSP
	clc
	adc     #$01
	sta     _StackAddr
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ InitStack (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitStack: near

.segment	"CODE"

	jsr     _StackHome
	jmp     _UpdateStack

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ UpdateCStack (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateCStack: near

.segment	"CODE"

	lda     _CStackAddr
	ldx     _CStackAddr+1
	jsr     pushax
	lda     _CStackFrame+4
	clc
	adc     #$05
	jsr     pusha
	jsr     decsp1
	lda     _CStackFrame+7
	sec
	sbc     #$01
	ldy     #$00
L0596:	sta     (sp),y
	sec
	sbc     _CStackFrame+5
	sta     tmp1
	lda     tmp1
	beq     L03D8
	bcc     L03D8
	iny
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     _gotoxy
	ldy     #$03
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	dey
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _cputhex16
	ldy     #$02
	ldx     #$00
	tya
	jsr     addeqysp
	ldy     #$00
	lda     (sp),y
	sec
	sbc     #$01
	jmp     L0596
L03D8:	jsr     decsp2
	lda     _CStackFrame+4
	clc
	adc     #$01
	iny
	sta     (sp),y
	lda     _CStackFrame+7
	sec
	sbc     #$01
	dey
	sta     (sp),y
	lda     #<(L03EB)
	ldx     #>(L03EB)
	jsr     _cputsxy
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ CStackHome (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_CStackHome: near

.segment	"CODE"

	lda     _DbgCS
	sta     _CStackAddr
	lda     _DbgCS+1
	sta     _CStackAddr+1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ InitCStack (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitCStack: near

.segment	"CODE"

	jsr     _CStackHome
	jmp     _UpdateCStack

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ UpdateDump (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateDump: near

.segment	"CODE"

	ldy     #$29
	jsr     subysp
	lda     _DumpAddr
	ldx     _DumpAddr+1
	jsr     pushax
	lda     _DumpFrame+4
	clc
	adc     #$01
	jsr     pusha
	ldy     #$04
	jsr     pushwysp
	lda     _DumpFrame+5
	clc
	adc     #$01
	ldy     #$05
L0597:	sta     (sp),y
	cmp     _DumpFrame+7
	bcs     L0422
	jsr     decsp2
	dey
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	ldy     #$07
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	jsr     decsp5
	ldy     #$0B
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$03
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     sp
	ldx     sp+1
	clc
	adc     #$0D
	bcc     L0430
	inx
L0430:	ldy     #$01
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$08
	ldy     #$00
	sta     (sp),y
	jsr     _DbgMemDump
	jsr     _cputsxy
	ldy     #$03
	ldx     #$00
	lda     #$08
	jsr     addeqysp
	ldy     #$05
	clc
	lda     #$01
	adc     (sp),y
	jmp     L0597
L0422:	dey
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$2E
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ DumpHome (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DumpHome: near

.segment	"CODE"

	lda     #$00
	sta     _DumpAddr
	sta     _DumpAddr+1
	rts

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ GetArg16 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_GetArg16: near

.segment	"CODE"

	lda     _brk_pc
	ldx     _brk_pc+1
	clc
	adc     #$01
	bcc     L046F
	inx
L046F:	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	rts

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ GetStack16 (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_GetStack16: near

.segment	"CODE"

	ldx     #$00
	lda     (sp,x)
	clc
	adc     _DbgSP
	bcc     L0599
	inx
	clc
L0599:	adc     #$01
	bcc     L0473
	inx
L0473:	inx
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ SetRTSBreak (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_SetRTSBreak: near

.segment	"CODE"

	lda     #$00
	jsr     pusha
	jsr     _GetStack16
	clc
	adc     #$01
	bcc     L0478
	inx
L0478:	jsr     pushax
	jmp     _DbgSetTmpBreak

.endproc

; ---------------------------------------------------------------
; void __near__ DbgEntry (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DbgEntry: near

.segment	"DATA"

L04E4:
	.byte	$01

.segment	"CODE"

	jsr     decsp2
	lda     L04E4
	beq     L04E6
	lda     #$00
	sta     L04E4
	jsr     pusha
	jsr     _RedrawStatic
	jsr     _InitAsm
	jsr     _InitReg
	jsr     _InitStack
	jsr     _InitCStack
	jsr     _UpdateDump
L04E6:	jsr     _AsmHome
	jsr     _UpdateReg
	jsr     _StackHome
	jsr     _CStackHome
	lda     #$00
	tay
	sta     (sp),y
	jmp     L059C
L04F7:	lda     _ActiveFrame
	ldx     _ActiveFrame+1
	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     #<(_Frames)
	sta     ptr1
	lda     tmp1
	adc     #>(_Frames)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	sta     ptr1
	stx     ptr1+1
	ldy     #$0C
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     callax
	ldy     #$01
	sta     (sp),y
	lda     (sp),y
	jeq     L059B
	cmp     #$0A
	jeq     L0530
	cmp     #$20
	jeq     L0526
	cmp     #$31
	beq     L0502
	cmp     #$32
	beq     L0502
	cmp     #$33
	beq     L0502
	cmp     #$34
	beq     L0502
	cmp     #$35
	beq     L0502
	cmp     #$3F
	beq     L0510
	cmp     #$63
	jeq     L059B
	cmp     #$68
	beq     L051C
	cmp     #$71
	jeq     L054A
	cmp     #$72
	jeq     L0546
	cmp     #$73
	jeq     L0540
	cmp     #$75
	beq     L0515
	cmp     #$B1
	beq     L0510
	cmp     #$B3
	beq     L0515
	cmp     #$B4
	beq     L051C
	cmp     #$B7
	beq     L0526
	cmp     #$B8
	beq     L0530
	jmp     L04F9
L0502:	jsr     decsp3
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	sec
	sbc     #$31
	bcs     L050D
	dex
L050D:	ldy     #$01
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$00
	tay
	sta     (sp),y
	jsr     _ActivateFrame
	jmp     L04F9
L0510:	jsr     _HelpHandler
	jmp     L04F9
L0515:	jsr     _SetRTSBreak
	lda     #$01
	ldy     #$00
	sta     (sp),y
	jmp     L059C
L051C:	lda     _brk_pc
	ldx     _brk_pc+1
	cpx     _AsmAddr+1
	bne     L059D
	cmp     _AsmAddr
	beq     L04F9
L059D:	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     pushax
	jsr     _DbgSetTmpBreak
	lda     #$01
	ldy     #$00
	sta     (sp),y
	jmp     L059C
L0526:	tya
	jsr     pusha
	jsr     _SingleStep
	jsr     _DbgTmpBreaksOk
	tax
	beq     L04F9
	lda     #$01
	ldy     #$00
	sta     (sp),y
	jmp     L059C
L0530:	lda     #$00
	jsr     pusha
	jsr     _SingleStep
	jsr     _DbgTmpBreaksOk
	tax
	beq     L04F9
	lda     #$01
	ldy     #$00
	sta     (sp),y
	jmp     L059C
L059B:	tya
	dey
	sta     (sp),y
	jmp     L059C
L0540:	lda     _brk_pc
	ldx     _brk_pc+1
	jsr     _DbgDisAsmLen
	clc
	adc     _brk_pc
	sta     _brk_pc
	txa
	adc     _brk_pc+1
	sta     _brk_pc+1
	jsr     _InitAsm
	jmp     L04F9
L0546:	lda     _ActiveFrame
	jsr     pusha
	jsr     _Redraw
	jmp     L04F9
L054A:	jsr     _clrscr
	ldx     #$00
	lda     #$01
	jsr     _exit
L04F9:	ldy     #$00
L059C:	lda     (sp),y
	jeq     L04F7
	jmp     incsp2

.endproc

