;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_fputc
	.import		_write

; ---------------------------------------------------------------
; int __near__ __fastcall__ fputc (int, register __near__ struct _FILE*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fputc: near

.segment	"CODE"

	jsr     pushax
	ldy     #$00
	ldx     #$04
	jsr     regswap2
	ldy     #$01
	lda     (regbank+4),y
	and     #$01
	beq     L000B
	lda     (regbank+4),y
	and     #$06
	bne     L000B
	jsr     decsp4
	dey
	lda     (regbank+4),y
	ldy     #$02
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     sp
	ldx     sp+1
	clc
	adc     #$06
	bcc     L0010
	inx
L0010:	ldy     #$00
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldx     #$00
	tya
	jsr     _write
	cpx     #$00
	bne     L0018
	cmp     #$01
	beq     L000C
L0018:	ldy     #$01
	lda     (regbank+4),y
	ora     #$04
	sta     (regbank+4),y
L000B:	ldx     #$FF
	txa
	jmp     L0002
L000C:	ldy     #$02
	lda     (sp),y
L0002:	pha
	ldy     #$00
	lda     (sp),y
	sta     regbank+4
	iny
	lda     (sp),y
	sta     regbank+5
	pla
	jmp     incsp4

.endproc

