;
; File generated by co65 v 2.14.0 using model `cc65-module'
;
.fopt		compiler,"co65 v 2.14.0"
.case		on
.debuginfo	off
.export		_a2e_stdjoy_joy

;
; CODE SEGMENT
;
.segment	"CODE"
_a2e_stdjoy_joy:
	.byte	$6A
	.byte	$6F
	.byte	$79
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$20
	.byte	$04
	.byte	$08
	.byte	$40
	.byte	$80
	.byte	$00
	.byte	$00
	.word	_a2e_stdjoy_joy+24
	.word	_a2e_stdjoy_joy+28
	.word	_a2e_stdjoy_joy+29
	.word	_a2e_stdjoy_joy+34
	.byte	$00
	.byte	$00
	.byte	$A9
	.byte	$00
	.byte	$A2
	.byte	$00
	.byte	$60
	.byte	$A9
	.byte	$02
	.byte	$A2
	.byte	$00
	.byte	$60
	.byte	$2C
	.byte	$82
	.byte	$C0
	.byte	$29
	.byte	$01
	.byte	$0A
	.byte	$AA
	.byte	$20
	.byte	$1E
	.byte	$FB
	.byte	$A9
	.byte	$00
	.byte	$C0
	.byte	$6B
	.byte	$6A
	.byte	$C0
	.byte	$93
	.byte	$6A
	.byte	$48
	.byte	$E8
	.byte	$20
	.byte	$1E
	.byte	$FB
	.byte	$68
	.byte	$C0
	.byte	$6B
	.byte	$6A
	.byte	$C0
	.byte	$93
	.byte	$6A
	.byte	$A8
	.byte	$BD
	.byte	$60
	.byte	$C0
	.byte	$0A
	.byte	$98
	.byte	$6A
	.byte	$A8
	.byte	$E8
	.byte	$8A
	.byte	$29
	.byte	$03
	.byte	$AA
	.byte	$BD
	.byte	$60
	.byte	$C0
	.byte	$0A
	.byte	$98
	.byte	$6A
	.byte	$49
	.byte	$14
	.byte	$A2
	.byte	$00
	.byte	$2C
	.byte	$80
	.byte	$C0
	.byte	$60

;
; DATA SEGMENT
;
.segment	"DATA"
DATA:

;
; BSS SEGMENT
;
.segment	"BSS"
BSS:
	.res	0

;
; ZEROPAGE SEGMENT
;
.import	__ZP_START__		; Linker generated symbol
ZEROPAGE = __ZP_START__

.end
