;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_free
	.import		_close
	.export		_closedir

; ---------------------------------------------------------------
; int __near__ __fastcall__ closedir (__near__ struct DIR*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_closedir: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp2
	ldy     #$03
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	dey
	lda     (ptr1),y
	tax
	lda     (ptr1)
	jsr     _close
	jsr     stax0sp
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _free
	ldy     #$01
	lda     (sp),y
	tax
	lda     (sp)
	jmp     incsp4

.endproc

