;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_cbm_k_save
	.import		_cbm_k_setlfs
	.import		_cbm_k_setnam
	.export		_cbm_save
	.import		__oserror

; ---------------------------------------------------------------
; unsigned char __near__ __fastcall__ cbm_save (__near__ const unsigned char*, unsigned char, __near__ const void*, unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cbm_save: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp2
	lda     #$00
	ldy     #$01
	sta     (sp),y
	ldy     #$06
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	tya
	jsr     _cbm_k_setlfs
	ldy     #$06
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _cbm_k_setnam
	ldy     #$05
	jsr     pushwysp
	ldy     #$04
	lda     (sp),y
	ldy     #$02
	clc
	adc     (sp),y
	pha
	ldy     #$05
	lda     (sp),y
	ldy     #$03
	adc     (sp),y
	tax
	pla
	jsr     _cbm_k_save
	sta     __oserror
	jmp     incsp7

.endproc

