;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_exit
	.import		_strlen
	.import		_clrscr
	.import		_kbhit
	.import		_gotoxy
	.import		_wherex
	.import		_cputc
	.import		_cputcxy
	.import		_cputsxy
	.import		_cgetc
	.import		_cursor
	.import		_revers
	.import		_textcolor
	.import		_bgcolor
	.import		_bordercolor
	.import		_chline
	.import		_chlinexy
	.import		_cvlinexy
	.import		_cclearxy
	.import		_cputhex8
	.import		_cputhex16
	.import		__ctype
	.import		_toupper
	.import		_brk_a
	.import		_brk_x
	.import		_brk_y
	.import		_brk_sr
	.import		_brk_pc
	.import		_DbgDisAsm
	.import		_DbgDisAsmLen
	.import		_DbgIsRAM
	.import		_DbgMemDump
	.import		_DbgSP
	.import		_DbgCS
	.import		_DbgHI
	.export		_DbgBreakCount
	.export		_DbgBreaks
	.import		_DbgGetBreakSlot
	.import		_DbgIsBreak
	.export		_DbgEntry

.segment	"DATA"

_RegText:
	.byte	$01
	.byte	$00
	.addr	L0005
	.byte	$01
	.byte	$01
	.addr	L0009
	.byte	$01
	.byte	$02
	.addr	L000D
	.byte	$01
	.byte	$03
	.addr	L0011
	.byte	$01
	.byte	$04
	.addr	L0015
	.byte	$01
	.byte	$05
	.addr	L0019
	.byte	$01
	.byte	$06
	.addr	L001D
	.byte	$01
	.byte	$07
	.addr	L0021
_HelpText:
	.byte	$01
	.byte	$00
	.addr	L0025
	.byte	$01
	.byte	$01
	.addr	L0029
	.byte	$01
	.byte	$02
	.addr	L002D
	.byte	$01
	.byte	$03
	.addr	L0031
	.byte	$01
	.byte	$04
	.addr	L0035
	.byte	$01
	.byte	$05
	.addr	L0039
	.byte	$01
	.byte	$06
	.addr	L003D
	.byte	$01
	.byte	$07
	.addr	L0041
	.byte	$01
	.byte	$08
	.addr	L0045
	.byte	$01
	.byte	$09
	.addr	L0049
	.byte	$01
	.byte	$0A
	.addr	L004D
	.byte	$01
	.byte	$0B
	.addr	L0051
	.byte	$01
	.byte	$0C
	.addr	L0055
	.byte	$01
	.byte	$0D
	.addr	L0059
	.byte	$01
	.byte	$0E
	.addr	L005D
	.byte	$01
	.byte	$0F
	.addr	L0061
	.byte	$01
	.byte	$10
	.addr	L0065
	.byte	$01
	.byte	$11
	.addr	L0069
_AsmFrame:
	.byte	$B0
	.byte	$B2
	.byte	$AB
	.byte	$DB
	.byte	$00
	.byte	$00
	.byte	$1E
	.byte	$0F
	.byte	$1D
	.byte	$0E
	.byte	$01
	.addr	_AsmHandler
	.byte	$00
	.word	$0000
_RegFrame:
	.byte	$B2
	.byte	$AE
	.byte	$AB
	.byte	$B3
	.byte	$1E
	.byte	$00
	.byte	$27
	.byte	$09
	.byte	$08
	.byte	$08
	.byte	$01
	.addr	_RegHandler
	.byte	$08
	.addr	_RegText
_StackFrame:
	.byte	$AB
	.byte	$B3
	.byte	$DB
	.byte	$B3
	.byte	$1E
	.byte	$09
	.byte	$27
	.byte	$0F
	.byte	$08
	.byte	$05
	.byte	$01
	.addr	_StackHandler
	.byte	$00
	.word	$0000
_CStackFrame:
	.byte	$DB
	.byte	$B3
	.byte	$B1
	.byte	$BD
	.byte	$1E
	.byte	$0F
	.byte	$27
	.byte	$18
	.byte	$08
	.byte	$08
	.byte	$01
	.addr	_CStackHandler
	.byte	$00
	.word	$0000
_DumpFrame:
	.byte	$AB
	.byte	$DB
	.byte	$AD
	.byte	$B1
	.byte	$00
	.byte	$0F
	.byte	$1E
	.byte	$18
	.byte	$1D
	.byte	$08
	.byte	$01
	.addr	_DumpHandler
	.byte	$00
	.word	$0000
_HelpFrame:
	.byte	$B0
	.byte	$AE
	.byte	$AD
	.byte	$BD
	.byte	$00
	.byte	$00
	.byte	$27
	.byte	$18
	.byte	$26
	.byte	$17
	.byte	$00
	.addr	_HelpHandler
	.byte	$12
	.addr	_HelpText
_Frames:
	.addr	_AsmFrame
	.addr	_RegFrame
	.addr	_StackFrame
	.addr	_CStackFrame
	.addr	_DumpFrame
	.addr	_HelpFrame
_ActiveFrame:
	.word	$FFFF
_ActivePrompt:
	.word	$0000
_DbgBreakCount:
	.byte	$00

.segment	"RODATA"

L002D:
	.byte	$C6,$33,$2C,$20,$55,$20,$20,$20,$20,$20,$D2,$55,$4E,$20,$55,$4E
	.byte	$54,$49,$4C,$20,$53,$55,$42,$52,$4F,$55,$54,$49,$4E,$45,$20,$52
	.byte	$45,$54,$55,$52,$4E,$53,$00
L023D:
	.byte	$C3,$41,$4E,$4E,$4F,$54,$20,$53,$45,$54,$20,$42,$52,$45,$41,$4B
	.byte	$50,$4F,$49,$4E,$54,$20,$2D,$20,$50,$52,$45,$53,$53,$20,$41,$20
	.byte	$4B,$45,$59,$00
L0251:
	.byte	$D4,$4F,$4F,$20,$4D,$41,$4E,$59,$20,$42,$52,$45,$41,$4B,$50,$4F
	.byte	$49,$4E,$54,$53,$20,$2D,$20,$50,$52,$45,$53,$53,$20,$41,$20,$4B
	.byte	$45,$59,$00
L0069:
	.byte	$53,$20,$20,$20,$20,$20,$20,$20,$20,$20,$D3,$4B,$49,$50,$20,$4E
	.byte	$45,$58,$54,$20,$49,$4E,$53,$54,$52,$55,$43,$54,$49,$4F,$4E,$00
L003D:
	.byte	$31,$2D,$35,$20,$20,$20,$20,$20,$20,$20,$D3,$45,$4C,$45,$43,$54
	.byte	$20,$41,$43,$54,$49,$56,$45,$20,$57,$49,$4E,$44,$4F,$57,$00
L005D:
	.byte	$50,$20,$20,$20,$20,$20,$20,$20,$20,$20,$D5,$53,$45,$20,$41,$53
	.byte	$20,$4E,$45,$57,$20,$D0,$C3,$20,$56,$41,$4C,$55,$45,$00
L0055:
	.byte	$46,$20,$20,$20,$20,$20,$20,$20,$20,$20,$C6,$4F,$4C,$4C,$4F,$57
	.byte	$20,$49,$4E,$53,$54,$52,$55,$43,$54,$49,$4F,$4E,$00
L0029:
	.byte	$C6,$32,$2C,$20,$54,$20,$20,$20,$20,$20,$D4,$4F,$47,$47,$4C,$45
	.byte	$20,$42,$52,$45,$41,$4B,$50,$4F,$49,$4E,$54,$00
L0238:
	.byte	$C9,$4E,$56,$41,$4C,$49,$44,$20,$49,$4E,$50,$55,$54,$20,$2D,$20
	.byte	$50,$52,$45,$53,$53,$20,$41,$20,$4B,$45,$59,$00
L0172:
	.byte	$D0,$52,$45,$53,$53,$20,$41,$4E,$59,$20,$4B,$45,$59,$20,$54,$4F
	.byte	$20,$43,$4F,$4E,$54,$49,$4E,$55,$45,$00
L0031:
	.byte	$C6,$34,$2C,$20,$48,$20,$20,$20,$20,$20,$D2,$55,$4E,$20,$54,$4F
	.byte	$20,$43,$55,$52,$53,$4F,$52,$00
L0065:
	.byte	$52,$20,$20,$20,$20,$20,$20,$20,$20,$20,$D2,$45,$44,$52,$41,$57
	.byte	$20,$53,$43,$52,$45,$45,$4E,$00
L004D:
	.byte	$41,$2F,$5A,$20,$20,$20,$20,$20,$20,$20,$CD,$4F,$56,$45,$20,$55
	.byte	$50,$2F,$44,$4F,$57,$4E,$00
L0049:
	.byte	$C3,$55,$52,$53,$4F,$52,$20,$20,$20,$20,$CD,$4F,$56,$45,$20,$55
	.byte	$50,$2F,$44,$4F,$57,$4E,$00
L0059:
	.byte	$4F,$20,$20,$20,$20,$20,$20,$20,$20,$20,$C7,$4F,$54,$4F,$20,$4F
	.byte	$52,$49,$47,$49,$4E,$00
L0035:
	.byte	$C6,$37,$2C,$20,$53,$50,$41,$43,$45,$20,$D3,$54,$45,$50,$20,$49
	.byte	$4E,$54,$4F,$00
L0039:
	.byte	$C6,$38,$2C,$20,$45,$4E,$54,$45,$52,$20,$D3,$54,$45,$50,$20,$4F
	.byte	$56,$45,$52,$00
L0041:
	.byte	$2B,$20,$20,$20,$20,$20,$20,$20,$20,$20,$D0,$41,$47,$45,$20,$44
	.byte	$4F,$57,$4E,$00
L0051:
	.byte	$43,$20,$20,$20,$20,$20,$20,$20,$20,$20,$C3,$4F,$4E,$54,$49,$4E
	.byte	$55,$45,$00
L0045:
	.byte	$2D,$20,$20,$20,$20,$20,$20,$20,$20,$20,$D0,$41,$47,$45,$20,$55
	.byte	$50,$00
L016E:
	.byte	$D0,$52,$45,$53,$53,$20,$C6,$31,$20,$46,$4F,$52,$20,$48,$45,$4C
	.byte	$50,$00
L0061:
	.byte	$51,$20,$20,$20,$20,$20,$20,$20,$20,$20,$D1,$55,$49,$54,$00
L0025:
	.byte	$C6,$31,$2C,$20,$3F,$20,$20,$20,$20,$20,$C8,$45,$4C,$50,$00
L0232:
	.byte	$C7,$4F,$54,$4F,$3A,$20,$00
L0009:
	.byte	$D3,$D2,$00
L001D:
	.byte	$C3,$D3,$00
L0021:
	.byte	$C8,$C9,$00
L0019:
	.byte	$D3,$D0,$00
L03EC:
	.byte	$2D,$3E,$00
L0005:
	.byte	$D0,$C3,$00
L0011:
	.byte	$D8,$00
L000D:
	.byte	$C1,$00
L0015:
	.byte	$D9,$00

.segment	"BSS"

_AsmAddr:
	.res	2,$00
_DumpAddr:
	.res	2,$00
_CStackAddr:
	.res	2,$00
_StackAddr:
	.res	1,$00
_PromptColor:
	.res	1,$00
_PromptLength:
	.res	1,$00
_DbgBreaks:
	.res	48,$00

; ---------------------------------------------------------------
; unsigned char __near__ AsmHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AsmHandler: near

.segment	"CODE"

	jsr     decsp3
L0323:	jsr     _UpdateAsm
	jsr     stax0sp
	jsr     _GetKeyUpdate
	ldy     #$02
	sta     (sp),y
	cmp     #$11
	jeq     L0354
	cmp     #$2B
	beq     L032E
	cmp     #$2D
	beq     L0332
	cmp     #$41
	jeq     L034C
	cmp     #$46
	beq     L033E
	cmp     #$47
	beq     L0341
	cmp     #$4F
	beq     L0345
	cmp     #$50
	beq     L0348
	cmp     #$54
	beq     L0338
	cmp     #$5A
	jeq     L0354
	cmp     #$89
	beq     L0338
	cmp     #$91
	beq     L034C
	jmp     L054F
L032E:	dey
	lda     (sp),y
	sta     _AsmAddr+1
	dey
	lda     (sp),y
	sta     _AsmAddr
	jmp     L0323
L0332:	jsr     decsp3
	lda     _AsmAddr
	dey
	sta     (sp),y
	iny
	lda     _AsmAddr+1
	sta     (sp),y
	lda     _AsmFrame+9
	ldy     #$00
	sta     (sp),y
	jsr     _AsmBack
	sta     _AsmAddr
	stx     _AsmAddr+1
	jmp     L0323
L0338:	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     pushax
	jsr     _DbgToggleUserBreak
	jmp     L0323
L033E:	jsr     _AsmFollow
	jmp     L0323
L0341:	lda     #<(_AsmAddr)
	ldx     #>(_AsmAddr)
	jsr     pushax
	jsr     _InputGoto
	jmp     L0323
L0345:	jsr     _AsmHome
	jmp     L0323
L0348:	lda     _AsmAddr
	sta     _brk_pc
	lda     _AsmAddr+1
	sta     _brk_pc+1
	jmp     L0323
L034C:	jsr     decsp3
	lda     _AsmAddr
	dey
	sta     (sp),y
	iny
	lda     _AsmAddr+1
	sta     (sp),y
	lda     #$01
	ldy     #$00
	sta     (sp),y
	jsr     _AsmBack
	sta     _AsmAddr
	stx     _AsmAddr+1
	jmp     L0323
L0354:	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     _DbgDisAsmLen
	clc
	adc     _AsmAddr
	sta     _AsmAddr
	txa
	adc     _AsmAddr+1
	sta     _AsmAddr+1
	jmp     L0323
L054F:	ldx     #$00
	lda     (sp),y
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ RegHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_RegHandler: near

.segment	"CODE"

	jmp     _GetKeyUpdate

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ StackHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_StackHandler: near

.segment	"CODE"

	jsr     decsp1
	lda     _StackFrame+9
	jsr     pusha
L03B4:	jsr     _GetKeyUpdate
	ldy     #$01
	sta     (sp),y
	cmp     #$11
	beq     L03CD
	cmp     #$2B
	beq     L03BD
	cmp     #$2D
	beq     L03C1
	cmp     #$41
	beq     L03C8
	cmp     #$4F
	beq     L03C5
	cmp     #$5A
	beq     L03CD
	cmp     #$91
	beq     L03C8
	jmp     L0550
L03BD:	dey
	lda     (sp),y
	clc
	adc     _StackAddr
	sta     _StackAddr
	jmp     L03BB
L03C1:	dey
	lda     (sp),y
	eor     #$FF
	sec
	adc     _StackAddr
	sta     _StackAddr
	jmp     L03BB
L03C5:	jsr     _StackHome
	jmp     L03BB
L03C8:	dec     _StackAddr
	jmp     L03BB
L03CD:	inc     _StackAddr
	jmp     L03BB
L0550:	ldx     #$00
	lda     (sp),y
	jmp     incsp2
L03BB:	jsr     _UpdateStack
	jmp     L03B4

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ CStackHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_CStackHandler: near

.segment	"CODE"

	jsr     decsp1
	lda     _CStackFrame+9
	asl     a
	jsr     pusha
L03F8:	jsr     _GetKeyUpdate
	ldy     #$01
	sta     (sp),y
	cmp     #$11
	beq     L0413
	cmp     #$2B
	beq     L0401
	cmp     #$2D
	beq     L0405
	cmp     #$41
	beq     L040C
	cmp     #$4F
	beq     L0409
	cmp     #$5A
	beq     L0413
	cmp     #$91
	beq     L040C
	jmp     L0551
L0401:	dey
	lda     (sp),y
	clc
	adc     _CStackAddr
	sta     _CStackAddr
	tya
	adc     _CStackAddr+1
	sta     _CStackAddr+1
	jmp     L03FF
L0405:	dey
	lda     (sp),y
	eor     #$FF
	sec
	adc     _CStackAddr
	sta     _CStackAddr
	lda     #$FF
	adc     _CStackAddr+1
	sta     _CStackAddr+1
	jmp     L03FF
L0409:	jsr     _CStackHome
	jmp     L03FF
L040C:	lda     _CStackAddr
	sec
	sbc     #$02
	sta     _CStackAddr
	bcs     L03FF
	dec     _CStackAddr+1
	jmp     L03FF
L0413:	lda     #$02
	clc
	adc     _CStackAddr
	sta     _CStackAddr
	bcc     L03FF
	inc     _CStackAddr+1
	jmp     L03FF
L0551:	ldx     #$00
	lda     (sp),y
	jmp     incsp2
L03FF:	jsr     _UpdateCStack
	jmp     L03F8

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ DumpHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DumpHandler: near

.segment	"CODE"

	jsr     decsp1
	ldx     #$00
	lda     _DumpFrame+9
	jsr     shlax3
	jsr     pushax
L043B:	jsr     _GetKeyUpdate
	ldy     #$02
	sta     (sp),y
	cmp     #$11
	beq     L045A
	cmp     #$2B
	beq     L0444
	cmp     #$2D
	beq     L0448
	cmp     #$41
	beq     L0453
	cmp     #$47
	beq     L044C
	cmp     #$4F
	beq     L0450
	cmp     #$5A
	beq     L045A
	cmp     #$91
	beq     L0453
	jmp     L0552
L0444:	dey
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     _DumpAddr
	sta     _DumpAddr
	txa
	adc     _DumpAddr+1
	sta     _DumpAddr+1
	jmp     L0442
L0448:	dey
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	eor     #$FF
	sec
	adc     _DumpAddr
	sta     _DumpAddr
	txa
	eor     #$FF
	adc     _DumpAddr+1
	sta     _DumpAddr+1
	jmp     L0442
L044C:	lda     #<(_DumpAddr)
	ldx     #>(_DumpAddr)
	jsr     pushax
	jsr     _InputGoto
	jmp     L0442
L0450:	jsr     _DumpHome
	jmp     L0442
L0453:	lda     _DumpAddr
	sec
	sbc     #$08
	sta     _DumpAddr
	bcs     L0442
	dec     _DumpAddr+1
	jmp     L0442
L045A:	lda     #$08
	clc
	adc     _DumpAddr
	sta     _DumpAddr
	bcc     L0442
	inc     _DumpAddr+1
	jmp     L0442
L0552:	ldx     #$00
	lda     (sp),y
	jmp     incsp3
L0442:	jsr     _UpdateDump
	jmp     L043B

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ HelpHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_HelpHandler: near

.segment	"CODE"

	lda     _ActiveFrame
	ldx     _ActiveFrame+1
	jsr     pushax
	jsr     decsp3
	lda     #$05
	ldy     #$01
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #$01
	ldy     #$00
	sta     (sp),y
	jsr     _ActivateFrame
	jsr     _AnyKeyPrompt
	jsr     _cgetc
	ldy     #$00
	lda     (sp),y
	jsr     pusha
	jsr     _Redraw
	ldx     #$00
	txa
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ DisplayPrompt (__near__ unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DisplayPrompt: near

.segment	"CODE"

	jsr     decsp1
	lda     #$01
	jsr     _textcolor
	ldy     #$00
	sta     (sp),y
	lda     _ActivePrompt
	ora     _ActivePrompt+1
	beq     L0153
	lda     _PromptColor
	jsr     _textcolor
	jsr     decsp2
	lda     #$28
	sec
	sbc     _PromptLength
	lsr     a
	ldy     #$01
	sta     (sp),y
	lda     #$18
	dey
	sta     (sp),y
	lda     _PromptLength
	jsr     _chlinexy
L0153:	ldy     #$02
	lda     (sp),y
	sta     _ActivePrompt+1
	dey
	lda     (sp),y
	sta     _ActivePrompt
	dey
	lda     (sp),y
	sta     _PromptColor
	lda     _ActivePrompt
	ldx     _ActivePrompt+1
	jsr     _strlen
	sta     _PromptLength
	lda     #$01
	jsr     _textcolor
	jsr     decsp2
	lda     #$28
	sec
	sbc     _PromptLength
	lsr     a
	ldy     #$01
	sta     (sp),y
	lda     #$18
	dey
	sta     (sp),y
	lda     _ActivePrompt
	ldx     _ActivePrompt+1
	jsr     _cputsxy
	lda     _PromptColor
	jsr     _textcolor
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ SingleStep (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_SingleStep: near

.segment	"CODE"

	jsr     decsp1
	lda     _brk_pc
	sta     ptr1
	lda     _brk_pc+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	cmp     #$10
	beq     L0495
	cmp     #$20
	jeq     L04A9
	cmp     #$30
	beq     L0495
	cmp     #$40
	beq     L04A4
	cmp     #$4C
	beq     L047F
	cmp     #$50
	beq     L0495
	cmp     #$60
	beq     L04A1
	cmp     #$6C
	beq     L0483
	cmp     #$70
	beq     L0495
	cmp     #$90
	beq     L0495
	cmp     #$B0
	beq     L0495
	cmp     #$D0
	beq     L0495
	cmp     #$F0
	beq     L0495
	jmp     L047D
L047F:	jsr     _GetArg16
	jmp     L0554
L0483:	jsr     _GetArg16
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jmp     L0554
L0495:	lda     _brk_pc
	ldx     _brk_pc+1
	iny
	jsr     ldaidx
	dey
	sta     (sp),y
	lda     (sp),y
	beq     L047D
	ldx     #$00
	lda     (sp),y
	bpl     L049E
	dex
L049E:	clc
	adc     _brk_pc
	pha
	txa
	adc     _brk_pc+1
	tax
	pla
	clc
	adc     #$02
	bcc     L049F
	inx
L049F:	jsr     pushax
	jsr     _DbgSetTmpBreak
	jmp     L047D
L04A1:	jsr     _SetRTSBreak
	jmp     incsp2
L04A4:	lda     #$01
	jsr     pusha
	jsr     _GetStack16
	jmp     L0554
L04A9:	iny
	lda     (sp),y
	beq     L047D
	jsr     _GetArg16
	jmp     L0554
L047D:	lda     _brk_pc
	ldx     _brk_pc+1
	jsr     pushax
	lda     _brk_pc
	ldx     _brk_pc+1
	jsr     _DbgDisAsmLen
	jsr     tosaddax
L0554:	jsr     pushax
	jsr     _DbgSetTmpBreak
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ RedrawStatic (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_RedrawStatic: near

.segment	"CODE"

	lda     #$FF
	sta     _ActiveFrame
	sta     _ActiveFrame+1
	lda     #$00
	jsr     _bordercolor
	lda     #$00
	jsr     _bgcolor
	jsr     _clrscr
	lda     #$00
	jsr     _cursor
	lda     #$0F
	jsr     _textcolor
	jsr     _DrawFrames
	jsr     _HelpPrompt
	jsr     decsp3
	ldy     #$03
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	tay
	sta     (sp),y
	jsr     _ActivateFrame
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ Redraw (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Redraw: near

.segment	"CODE"

	ldy     #$00
	lda     (sp),y
	jsr     pusha
	jsr     _RedrawStatic
	jsr     _UpdateAsm
	jsr     _UpdateReg
	jsr     _UpdateStack
	jsr     _UpdateCStack
	jsr     _UpdateDump
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ GetKeyUpdate (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_GetKeyUpdate: near

.segment	"BSS"

L04CB:
	.res	1,$00

.segment	"CODE"

	jmp     L04CE
L0555:	lda     L04CB
	beq     L04D4
	cmp     #$01
	beq     L04D7
	cmp     #$02
	beq     L04DA
	cmp     #$03
	beq     L04DD
	jmp     L0556
L04D4:	jsr     _UpdateAsm
	jmp     L0556
L04D7:	jsr     _UpdateStack
	jmp     L0556
L04DA:	jsr     _UpdateCStack
	jmp     L0556
L04DD:	jsr     _UpdateDump
L0556:	lda     L04CB
	clc
	adc     #$01
	and     #$03
	sta     L04CB
L04CE:	jsr     _kbhit
	tax
	beq     L0555
	jmp     _cgetc

.endproc

; ---------------------------------------------------------------
; void __near__ DrawFrame (register __near__ struct $anon-struct-0008*, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DrawFrame: near

.segment	"CODE"

	ldy     #$01
	ldx     #$04
	jsr     regswap2
	ldy     #$0B
	jsr     subysp
	ldy     #$0B
	lda     (sp),y
	beq     L00D0
	lda     #$01
	jsr     _textcolor
	ldy     #$00
	sta     (sp),y
	lda     #$B0
	ldy     #$07
	sta     (sp),y
	lda     #$AE
	dey
	sta     (sp),y
	lda     #$AD
	dey
	sta     (sp),y
	lda     #$BD
	jmp     L0558
L00D0:	lda     #$0F
	jsr     _textcolor
	ldy     #$00
	sta     (sp),y
	lda     (regbank+4),y
	ldy     #$07
	sta     (sp),y
	ldy     #$01
	lda     (regbank+4),y
	ldy     #$06
	sta     (sp),y
	ldy     #$02
	lda     (regbank+4),y
	ldy     #$05
	sta     (sp),y
	ldy     #$03
	lda     (regbank+4),y
L0558:	ldy     #$04
	sta     (sp),y
	lda     (regbank+4),y
	dey
	sta     (sp),y
	ldy     #$05
	lda     (regbank+4),y
	ldy     #$02
	sta     (sp),y
	ldy     #$08
	lda     (regbank+4),y
	ldy     #$01
	sta     (sp),y
	jsr     decsp2
	ldy     #$05
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	ldy     #$04
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	ldy     #$09
	lda     (sp),y
	jsr     _cputcxy
	ldy     #$01
	lda     (sp),y
	jsr     _chline
	ldy     #$06
	lda     (sp),y
	jsr     _cputc
	jsr     decsp2
	ldy     #$05
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	ldy     #$04
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	ldy     #$00
	sta     (sp),y
	ldy     #$09
	lda     (regbank+4),y
	jsr     _cvlinexy
	ldy     #$05
	lda     (sp),y
	jsr     _cputc
	ldy     #$01
	lda     (sp),y
	jsr     _chline
	ldy     #$04
	lda     (sp),y
	jsr     _cputc
	jsr     decsp2
	ldy     #$06
	lda     (regbank+4),y
	ldy     #$01
	sta     (sp),y
	ldy     #$04
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	ldy     #$09
	lda     (regbank+4),y
	jsr     _cvlinexy
	lda     #$0F
	jsr     _textcolor
	ldy     #$0D
	lda     (regbank+4),y
	ldy     #$08
	sta     (sp),y
	ldy     #$0F
	lda     (regbank+4),y
	tax
	dey
	lda     (regbank+4),y
	ldy     #$09
	jsr     staxysp
	jmp     L010D
L010B:	jsr     decsp2
	ldy     #$05
	lda     (sp),y
	jsr     pusha0
	ldy     #$0E
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     (ptr1,x)
	jsr     tosadda0
	ldy     #$01
	sta     (sp),y
	ldy     #$04
	lda     (sp),y
	jsr     pusha0
	ldy     #$0E
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$01
	lda     (ptr1),y
	jsr     tosadda0
	ldy     #$00
	sta     (sp),y
	ldy     #$0C
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$03
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _cputsxy
	ldy     #$09
	ldx     #$00
	lda     #$04
	jsr     addeqysp
L010D:	ldy     #$08
	lda     (sp),y
	pha
	sec
	sbc     #$01
	sta     (sp),y
	pla
	tax
	bne     L010B
	lda     (sp,x)
	jsr     _textcolor
	ldy     #$0C
	lda     (sp),y
	sta     regbank+4
	iny
	lda     (sp),y
	sta     regbank+5
	iny
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ DrawFrames (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DrawFrames: near

.segment	"CODE"

	jsr     decsp3
	lda     #$00
	ldy     #$02
L055A:	sta     (sp),y
	cmp     #$06
	bcs     L0118
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L055B
	inx
	clc
L055B:	adc     #<(_Frames)
	sta     ptr1
	txa
	adc     #>(_Frames)
	sta     ptr1+1
	dey
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     stax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0A
	lda     (ptr1),y
	beq     L0119
	jsr     decsp3
	ldy     #$04
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$00
	tay
	sta     (sp),y
	jsr     _DrawFrame
L0119:	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	jmp     L055A
L0118:	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ ActivateFrame (int, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ActivateFrame: near

.segment	"CODE"

	jsr     decsp1
	lda     regbank+4
	ldx     regbank+5
	jsr     pushax
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	cpx     _ActiveFrame+1
	bne     L055E
	cmp     _ActiveFrame
	jeq     L012B
L055E:	ldx     _ActiveFrame+1
	bmi     L012D
	jsr     decsp3
	lda     _ActiveFrame
	ldx     _ActiveFrame+1
	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     #<(_Frames)
	sta     ptr1
	lda     tmp1
	adc     #>(_Frames)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	iny
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$00
	tay
	sta     (sp),y
	jsr     _DrawFrame
L012D:	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     _ActiveFrame
	stx     _ActiveFrame+1
	txa
	jmi     L0133
	lda     _ActiveFrame
	ldx     _ActiveFrame+1
	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     #<(_Frames)
	sta     ptr1
	lda     tmp1
	adc     #>(_Frames)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	sta     regbank+4
	stx     regbank+4+1
	ldy     #$03
	lda     (sp),y
	beq     L013D
	ldy     #$05
	lda     (regbank+4),y
	clc
	adc     #$01
	ldy     #$02
L055D:	sta     (sp),y
	lda     (sp),y
	jsr     pusha0
	ldy     #$07
	lda     (regbank+4),y
	jsr     tosicmp0
	bcs     L013D
	jsr     decsp2
	ldy     #$04
	lda     (regbank+4),y
	clc
	adc     #$01
	ldy     #$01
	sta     (sp),y
	ldy     #$04
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	ldy     #$08
	lda     (regbank+4),y
	jsr     _cclearxy
	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	jmp     L055D
L013D:	jsr     decsp3
	lda     regbank+4
	ldy     #$01
	sta     (sp),y
	iny
	lda     regbank+4+1
	sta     (sp),y
	lda     #$01
	ldy     #$00
	sta     (sp),y
	jsr     _DrawFrame
L0133:	lda     _ActivePrompt
	ldx     _ActivePrompt+1
	jsr     pushax
	jsr     _DisplayPrompt
L012B:	ldy     #$00
	lda     (sp),y
	sta     regbank+4
	iny
	lda     (sp),y
	sta     regbank+5
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; void __near__ HelpPrompt (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_HelpPrompt: near

.segment	"CODE"

	lda     #<(L016E)
	ldx     #>(L016E)
	jsr     pushax
	jmp     _DisplayPrompt

.endproc

; ---------------------------------------------------------------
; void __near__ AnyKeyPrompt (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AnyKeyPrompt: near

.segment	"CODE"

	lda     #<(L0172)
	ldx     #>(L0172)
	jsr     pushax
	jmp     _DisplayPrompt

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ IsAbortKey (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_IsAbortKey: near

.segment	"CODE"

	ldx     #$00
	lda     (sp,x)
	cmp     #$1B
	bne     L0560
	lda     #$01
	jmp     incsp1
L0560:	lda     (sp,x)
	cmp     #$03
	bne     L0561
	lda     #$01
	jmp     incsp1
L0561:	txa
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Input (__near__ unsigned char*, __near__ unsigned char*, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Input: near

.segment	"CODE"

	ldy     #$0A
	jsr     subysp
	lda     #$00
	ldy     #$01
	sta     (sp),y
	lda     #$18
	dey
	sta     (sp),y
	lda     #$28
	jsr     _cclearxy
	lda     #$01
	jsr     _textcolor
	ldy     #$05
	sta     (sp),y
	jsr     decsp2
	lda     #$00
	ldy     #$01
	sta     (sp),y
	lda     #$18
	dey
	sta     (sp),y
	ldy     #$0E
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _cputsxy
	lda     #$0F
	jsr     _textcolor
	jsr     _wherex
	ldy     #$03
	sta     (sp),y
	lda     #$01
	jsr     _cursor
	ldy     #$04
	sta     (sp),y
	lda     #$00
	ldy     #$01
	sta     (sp),y
	iny
	sta     (sp),y
L0192:	jsr     _cgetc
	ldy     #$00
	sta     (sp),y
	tay
	lda     __ctype,y
	and     #$07
	beq     L0197
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	ldy     #$08
	cmp     (sp),y
	bcs     L0197
	ldy     #$02
	lda     (sp),y
	clc
	ldy     #$09
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$00
	lda     (sp),y
	sta     (ptr1),y
	jsr     decsp2
	ldy     #$04
	lda     (sp),y
	clc
	iny
	adc     (sp),y
	ldy     #$01
	sta     (sp),y
	lda     #$18
	dey
	sta     (sp),y
	ldy     #$02
	lda     (sp),y
	jsr     _cputcxy
	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	jmp     L0565
L0197:	ldy     #$02
	lda     (sp),y
	beq     L01B0
	ldy     #$00
	lda     (sp),y
	cmp     #$14
	bne     L056E
	ldy     #$02
	lda     (sp),y
	sec
	sbc     #$01
	sta     (sp),y
	jsr     decsp2
	ldy     #$04
	lda     (sp),y
	clc
	iny
	adc     (sp),y
	ldy     #$01
	sta     (sp),y
	lda     #$18
	dey
	sta     (sp),y
	lda     #$20
	jsr     _cputcxy
	ldy     #$02
	lda     (sp),y
	clc
	iny
	adc     (sp),y
	jsr     pusha
	lda     #$18
	jsr     _gotoxy
	jmp     L01C5
L01B0:	tay
L056E:	lda     (sp),y
	cmp     #$0D
	bne     L056C
	ldy     #$02
	lda     (sp),y
	clc
	ldy     #$09
	adc     (sp),y
	sta     ptr1
	lda     #$00
	iny
	adc     (sp),y
	sta     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	lda     #$01
	jmp     L056D
L056C:	lda     (sp),y
	jsr     pusha
	jsr     _IsAbortKey
	tax
	beq     L01C5
	lda     #$02
L056D:	ldy     #$01
L0565:	sta     (sp),y
L01C5:	ldy     #$01
	lda     (sp),y
	jeq     L0192
	ldy     #$04
	lda     (sp),y
	jsr     _cursor
	ldy     #$05
	lda     (sp),y
	jsr     _textcolor
	jsr     _DrawFrames
	lda     _ActiveFrame
	ldx     _ActiveFrame+1
	ldy     #$06
	jsr     staxysp
	lda     #$FF
	sta     _ActiveFrame
	sta     _ActiveFrame+1
	jsr     decsp3
	ldy     #$0A
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$00
	tay
	sta     (sp),y
	jsr     _ActivateFrame
	ldy     #$01
	lda     (sp),y
	cmp     #$01
	jsr     booleq
	ldy     #$0D
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ InputHex (__near__ unsigned char*, __near__ unsigned int*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InputHex: near

.segment	"CODE"

	ldy     #$0F
	jsr     subysp
	ldy     #$12
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$03
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     sp
	ldx     sp+1
	clc
	adc     #$0A
	bcc     L01DF
	inx
L01DF:	ldy     #$01
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$04
	ldy     #$00
	sta     (sp),y
	jsr     _Input
	tax
	jeq     L0226
	ldy     #$05
	lda     (sp),y
	tay
	lda     __ctype,y
	and     #$08
	bne     L0573
	tax
	jmp     L0226
L0573:	lda     sp
	ldx     sp+1
	clc
	adc     #$05
	bcc     L01F3
	inx
L01F3:	ldy     #$03
	jsr     staxysp
	ldy     #$00
	tya
	sta     (sp),y
	iny
	sta     (sp),y
	jmp     L01F8
L01F6:	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     shlax4
	jsr     stax0sp
	ldy     #$02
	lda     (sp),y
	tay
	lda     __ctype,y
	and     #$04
	beq     L020B
	ldy     #$02
	lda     (sp),y
	sec
	sbc     #$30
	jmp     L0570
L020B:	ldy     #$02
	lda     (sp),y
	ldx     #$00
	jsr     _toupper
	sec
	sbc     #$B7
	ldy     #$02
L0570:	sta     (sp),y
	ldx     #$00
	jsr     addeq0sp
	ldy     #$03
	ldx     #$00
	lda     #$01
	jsr     addeqysp
L01F8:	ldy     #$04
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$00
	lda     (ptr1),y
	ldy     #$02
	sta     (sp),y
	tax
	beq     L056F
	lda     (sp),y
	tay
	lda     __ctype,y
	and     #$08
	bne     L01F6
L056F:	ldy     #$0B
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	ldx     #$00
	tya
L0226:	ldy     #$0E
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ ErrorPrompt (__near__ unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ErrorPrompt: near

.segment	"CODE"

	lda     _ActivePrompt
	ldx     _ActivePrompt+1
	jsr     pushax
	ldy     #$05
	jsr     pushwysp
	jsr     _DisplayPrompt
	jsr     _cgetc
	jsr     pushw0sp
	jsr     _DisplayPrompt
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ InputGoto (__near__ unsigned int*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InputGoto: near

.segment	"CODE"

	jsr     decsp5
	lda     #<(L0232)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L0232)
	sta     (sp),y
	ldy     #$06
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	jsr     _InputHex
	ldy     #$00
	sta     (sp),y
	lda     (sp),y
	bne     L0578
	lda     #<(L0238)
	ldx     #>(L0238)
	jsr     pushax
	jsr     _ErrorPrompt
L0578:	ldx     #$00
	lda     (sp,x)
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ BreakInRomError (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_BreakInRomError: near

.segment	"CODE"

	lda     #<(L023D)
	ldx     #>(L023D)
	jsr     pushax
	jmp     _ErrorPrompt

.endproc

; ---------------------------------------------------------------
; void __near__ DbgSetTmpBreak (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DbgSetTmpBreak: near

.segment	"CODE"

	jsr     _DbgGetBreakSlot
	jsr     pushax
	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$00
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     #$80
	ldy     #$03
	sta     (ptr1),y
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ DbgToggleUserBreak (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DbgToggleUserBreak: near

.segment	"CODE"

	lda     regbank+4
	ldx     regbank+5
	jsr     pushax
	ldy     #$05
	jsr     pushwysp
	jsr     _DbgIsBreak
	sta     regbank+4
	stx     regbank+4+1
	lda     regbank+4
	ora     regbank+4+1
	beq     L0248
	lda     #$00
	ldy     #$03
	sta     (regbank+4),y
	dec     _DbgBreakCount
	jmp     L0258
L0248:	lda     _DbgBreakCount
	cmp     #$0A
	bcc     L024E
	lda     #<(L0251)
	ldx     #>(L0251)
	jsr     pushax
	jsr     _ErrorPrompt
	jmp     L0258
L024E:	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _DbgIsRAM
	stx     tmp1
	ora     tmp1
	bne     L0254
	jsr     _BreakInRomError
	jmp     L0258
L0254:	jsr     _DbgGetBreakSlot
	sta     regbank+4
	stx     regbank+4+1
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$00
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	tya
	ldy     #$03
	sta     (regbank+4),y
	inc     _DbgBreakCount
L0258:	ldy     #$00
	lda     (sp),y
	sta     regbank+4
	iny
	lda     (sp),y
	sta     regbank+5
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ DbgResetTmpBreaks (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DbgResetTmpBreaks: near

.segment	"CODE"

	jsr     decsp1
	lda     #<(_DbgBreaks)
	ldx     #>(_DbgBreaks)
	jsr     pushax
	lda     #$00
	ldy     #$02
L057A:	sta     (sp),y
	cmp     #$0A
	bcs     L0263
	dey
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$03
	lda     (ptr1),y
	cmp     #$80
	bne     L026A
	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	tya
	ldy     #$03
	sta     (ptr1),y
L026A:	ldx     #$00
	lda     #$04
	jsr     addeq0sp
	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	jmp     L057A
L0263:	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ DbgTmpBreaksOk (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DbgTmpBreaksOk: near

.segment	"CODE"

	jsr     decsp1
	lda     #<(_DbgBreaks)
	ldx     #>(_DbgBreaks)
	jsr     pushax
	lda     #$00
	ldy     #$02
L057B:	sta     (sp),y
	ldx     #$00
	lda     (sp),y
	cmp     #$0A
	bcs     L057D
	dey
	lda     (sp),y
	sta     ptr1+1
	lda     (sp,x)
	sta     ptr1
	ldy     #$03
	lda     (ptr1),y
	cmp     #$80
	bne     L0279
	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	lda     (sp,x)
	sta     ptr1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _DbgIsRAM
	stx     tmp1
	ora     tmp1
	bne     L0279
	jsr     _BreakInRomError
	jsr     _DbgResetTmpBreaks
	ldx     #$00
	txa
	jmp     incsp3
L0279:	ldx     #$00
	lda     #$04
	jsr     addeq0sp
	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	jmp     L057B
L057D:	lda     #$01
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ AsmBack (unsigned int, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AsmBack: near

.segment	"CODE"

	ldy     #$43
	jsr     subysp
	lda     #$06
	jsr     pusha0
L0286:	lda     #$00
	ldy     #$02
	sta     (sp),y
	ldy     #$49
	jsr     pushwysp
	ldy     #$47
	ldx     #$00
	lda     (sp),y
	jsr     mulax3
	jsr     tossubax
	sec
	ldy     #$00
	sbc     (sp),y
	pha
	txa
	iny
	sbc     (sp),y
	tax
	pla
	ldy     #$43
	jsr     staxysp
L028F:	ldy     #$44
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _DbgDisAsmLen
	ldy     #$43
	jsr     addeqysp
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L0581
	inx
	clc
L0581:	adc     #$03
	bcc     L0298
	inx
	clc
L0298:	adc     sp
	sta     ptr1
	txa
	adc     sp+1
	sta     ptr1+1
	ldy     #$44
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$00
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	iny
	lda     (sp),y
	clc
	adc     #$01
	and     #$1F
	sta     (sp),y
	ldy     #$44
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$46
	cmp     (sp),y
	txa
	iny
	sbc     (sp),y
	bcc     L028F
	ldy     #$44
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$46
	cmp     (sp),y
	bne     L0583
	txa
	iny
	cmp     (sp),y
	beq     L02A1
L0583:	ldy     #$01
	lda     (sp),y
	bne     L0585
	dey
	lda     (sp),y
	cmp     #$0C
	bne     L0585
L02A1:	ldy     #$02
	ldx     #$00
	lda     (sp),y
	sec
	ldy     #$45
	sbc     (sp),y
	sec
	sbc     #$01
	and     #$1F
	asl     a
	bcc     L0582
	inx
	clc
L0582:	adc     #$03
	bcc     L02A8
	inx
	clc
L02A8:	adc     sp
	sta     ptr1
	txa
	adc     sp+1
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jmp     L0287
L0585:	ldx     #$00
	lda     #$01
	jsr     addeq0sp
	jmp     L0286
L0287:	ldy     #$48
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ UpdateAsm (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateAsm: near

.segment	"CODE"

	ldy     #$2A
	jsr     subysp
	lda     _AsmFrame+8
	jsr     pusha
	lda     _AsmFrame+4
	clc
	adc     #$01
	jsr     pusha
	jsr     decsp3
	lda     _AsmAddr
	ldy     #$01
	sta     (sp),y
	iny
	lda     _AsmAddr+1
	sta     (sp),y
	tya
	ldy     #$00
	sta     (sp),y
	jsr     _AsmBack
	jsr     pushax
	lda     _AsmFrame+5
	clc
	adc     #$01
	ldy     #$04
L0588:	sta     (sp),y
	cmp     _AsmFrame+7
	jcs     L02B4
	jsr     decsp4
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     sp
	ldx     sp+1
	clc
	adc     #$0A
	bcc     L02C0
	inx
L02C0:	ldy     #$00
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$07
	lda     (sp),y
	jsr     _DbgDisAsm
	ldy     #$05
	sta     (sp),y
	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	cpx     _brk_pc+1
	bne     L02C2
	cmp     _brk_pc
	bne     L02C2
	lda     #$2D
	ldy     #$0A
	sta     (sp),y
	lda     #$3E
	iny
	sta     (sp),y
L02C2:	jsr     pushw0sp
	jsr     _DbgIsBreak
	stx     tmp1
	ora     tmp1
	beq     L02CC
	lda     #$2A
	ldy     #$0B
	sta     (sp),y
L02CC:	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	cpx     _AsmAddr+1
	bne     L02D3
	cmp     _AsmAddr
	bne     L02D3
	lda     #$01
	jsr     _revers
	jsr     decsp2
	lda     #$01
	tay
	sta     (sp),y
	ldy     #$06
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	lda     sp
	ldx     sp+1
	clc
	adc     #$08
	bcc     L02DB
	inx
L02DB:	jsr     _cputsxy
	lda     #$00
	jsr     _revers
	jmp     L02DE
L02D3:	jsr     decsp2
	lda     #$01
	iny
	sta     (sp),y
	ldy     #$06
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	lda     sp
	ldx     sp+1
	clc
	adc     #$08
	bcc     L02E3
	inx
L02E3:	jsr     _cputsxy
L02DE:	ldy     #$05
	lda     (sp),y
	ldx     #$00
	jsr     addeq0sp
	ldy     #$04
	clc
	lda     #$01
	adc     (sp),y
	jmp     L0588
L02B4:	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$2E
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ AsmArg16 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AsmArg16: near

.segment	"CODE"

	lda     _AsmAddr
	ldx     _AsmAddr+1
	clc
	adc     #$01
	bcc     L02EA
	inx
L02EA:	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ AsmFollow (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AsmFollow: near

.segment	"CODE"

	lda     _AsmAddr
	sta     ptr1
	lda     _AsmAddr+1
	sta     ptr1+1
	ldx     #$00
	lda     (ptr1,x)
	cmp     #$10
	beq     L02FA
	cmp     #$20
	beq     L02F0
	cmp     #$30
	beq     L02FA
	cmp     #$40
	beq     L058B
	cmp     #$4C
	beq     L02F0
	cmp     #$50
	beq     L02FA
	cmp     #$60
	beq     L058A
	cmp     #$6C
	beq     L02F6
	cmp     #$70
	beq     L02FA
	cmp     #$90
	beq     L02FA
	cmp     #$B0
	beq     L02FA
	cmp     #$D0
	beq     L02FA
	cmp     #$F0
	beq     L02FA
	rts
L02F0:	jsr     _AsmArg16
	jmp     L058C
L02F6:	jsr     _AsmArg16
	jmp     L0593
L02FA:	lda     _AsmAddr
	ldx     _AsmAddr+1
	clc
	adc     #$02
	bcc     L030B
	inx
L030B:	jsr     pushax
	lda     _AsmAddr
	ldx     _AsmAddr+1
	clc
	adc     #$01
	bcc     L030D
	inx
L030D:	ldy     #$00
	jsr     ldaidx
	jsr     tosaddax
	jmp     L058C
L058A:	lda     _DbgSP
	clc
	adc     #$01
	bcc     L0314
	inx
L0314:	inx
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	clc
	adc     #$01
	bcc     L058C
	inx
	jmp     L058C
L058B:	lda     _DbgSP
	clc
	adc     #$02
	bcc     L031B
	inx
L031B:	inx
L0593:	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
L058C:	sta     _AsmAddr
	stx     _AsmAddr+1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ AsmHome (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AsmHome: near

.segment	"CODE"

	lda     _brk_pc
	sta     _AsmAddr
	lda     _brk_pc+1
	sta     _AsmAddr+1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ InitAsm (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitAsm: near

.segment	"CODE"

	jsr     _AsmHome
	jmp     _UpdateAsm

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ UpdateReg (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateReg: near

.segment	"CODE"

	lda     _RegFrame+4
	clc
	adc     #$05
	jsr     pusha
	ldy     #$00
	lda     (sp),y
	clc
	adc     #$02
	jsr     pusha
	lda     _RegFrame+5
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _brk_pc
	ldx     _brk_pc+1
	jsr     _cputhex16
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _brk_sr
	jsr     _cputhex8
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _brk_a
	jsr     _cputhex8
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _brk_x
	jsr     _cputhex8
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _brk_y
	jsr     _cputhex8
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _DbgSP
	jsr     _cputhex8
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _DbgCS
	ldx     _DbgCS+1
	jsr     _cputhex16
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _DbgHI
	ldx     _DbgHI+1
	jsr     _cputhex16
	ldx     #$00
	txa
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ InitReg (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitReg: near

.segment	"CODE"

	jmp     _UpdateReg

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ UpdateStack (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateStack: near

.segment	"CODE"

	lda     _StackAddr
	jsr     pusha
	lda     _StackFrame+4
	clc
	adc     #$01
	jsr     pusha
	ldy     #$00
	lda     (sp),y
	clc
	adc     #$06
	jsr     pusha
	jsr     decsp1
	lda     _StackFrame+7
	sec
	sbc     #$01
	ldy     #$00
L0595:	sta     (sp),y
	ldx     #$00
	lda     (sp),y
	sec
	sbc     _StackFrame+5
	sta     tmp1
	lda     tmp1
	beq     L0396
	bcc     L0396
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     _gotoxy
	ldy     #$03
	lda     (sp),y
	jsr     _cputhex8
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     _gotoxy
	ldy     #$03
	lda     (sp),y
	sta     ptr1
	lda     #$01
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     _cputhex8
	ldy     #$03
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	ldy     #$00
	lda     (sp),y
	sec
	sbc     #$01
	jmp     L0595
L0396:	ldy     #$03
	lda     (sp),y
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ StackHome (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_StackHome: near

.segment	"CODE"

	lda     _DbgSP
	clc
	adc     #$01
	sta     _StackAddr
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ InitStack (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitStack: near

.segment	"CODE"

	jsr     _StackHome
	jmp     _UpdateStack

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ UpdateCStack (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateCStack: near

.segment	"CODE"

	lda     _CStackAddr
	ldx     _CStackAddr+1
	jsr     pushax
	lda     _CStackFrame+4
	clc
	adc     #$05
	jsr     pusha
	jsr     decsp1
	lda     _CStackFrame+7
	sec
	sbc     #$01
	ldy     #$00
L0597:	sta     (sp),y
	sec
	sbc     _CStackFrame+5
	sta     tmp1
	lda     tmp1
	beq     L03D9
	bcc     L03D9
	iny
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     _gotoxy
	ldy     #$03
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	dey
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _cputhex16
	ldy     #$02
	ldx     #$00
	tya
	jsr     addeqysp
	ldy     #$00
	lda     (sp),y
	sec
	sbc     #$01
	jmp     L0597
L03D9:	jsr     decsp2
	lda     _CStackFrame+4
	clc
	adc     #$01
	iny
	sta     (sp),y
	lda     _CStackFrame+7
	sec
	sbc     #$01
	dey
	sta     (sp),y
	lda     #<(L03EC)
	ldx     #>(L03EC)
	jsr     _cputsxy
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ CStackHome (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_CStackHome: near

.segment	"CODE"

	lda     _DbgCS
	sta     _CStackAddr
	lda     _DbgCS+1
	sta     _CStackAddr+1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ InitCStack (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitCStack: near

.segment	"CODE"

	jsr     _CStackHome
	jmp     _UpdateCStack

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ UpdateDump (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateDump: near

.segment	"CODE"

	ldy     #$29
	jsr     subysp
	lda     _DumpAddr
	ldx     _DumpAddr+1
	jsr     pushax
	lda     _DumpFrame+4
	clc
	adc     #$01
	jsr     pusha
	ldy     #$04
	jsr     pushwysp
	lda     _DumpFrame+5
	clc
	adc     #$01
	ldy     #$05
L0598:	sta     (sp),y
	cmp     _DumpFrame+7
	bcs     L0423
	jsr     decsp2
	dey
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	ldy     #$07
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	jsr     decsp5
	ldy     #$0B
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$03
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     sp
	ldx     sp+1
	clc
	adc     #$0D
	bcc     L0431
	inx
L0431:	ldy     #$01
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$08
	ldy     #$00
	sta     (sp),y
	jsr     _DbgMemDump
	jsr     _cputsxy
	ldy     #$03
	ldx     #$00
	lda     #$08
	jsr     addeqysp
	ldy     #$05
	clc
	lda     #$01
	adc     (sp),y
	jmp     L0598
L0423:	dey
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$2E
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ DumpHome (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DumpHome: near

.segment	"CODE"

	lda     #$00
	sta     _DumpAddr
	sta     _DumpAddr+1
	rts

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ GetArg16 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_GetArg16: near

.segment	"CODE"

	lda     _brk_pc
	ldx     _brk_pc+1
	clc
	adc     #$01
	bcc     L0470
	inx
L0470:	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	rts

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ GetStack16 (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_GetStack16: near

.segment	"CODE"

	ldx     #$00
	lda     (sp,x)
	clc
	adc     _DbgSP
	bcc     L059A
	inx
	clc
L059A:	adc     #$01
	bcc     L0474
	inx
L0474:	inx
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ SetRTSBreak (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_SetRTSBreak: near

.segment	"CODE"

	lda     #$00
	jsr     pusha
	jsr     _GetStack16
	clc
	adc     #$01
	bcc     L0479
	inx
L0479:	jsr     pushax
	jmp     _DbgSetTmpBreak

.endproc

; ---------------------------------------------------------------
; void __near__ DbgEntry (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DbgEntry: near

.segment	"DATA"

L04E5:
	.byte	$01

.segment	"CODE"

	jsr     decsp2
	lda     L04E5
	beq     L04E7
	lda     #$00
	sta     L04E5
	jsr     pusha
	jsr     _RedrawStatic
	jsr     _InitAsm
	jsr     _InitReg
	jsr     _InitStack
	jsr     _InitCStack
	jsr     _UpdateDump
L04E7:	jsr     _AsmHome
	jsr     _UpdateReg
	jsr     _StackHome
	jsr     _CStackHome
	lda     #$00
	tay
	sta     (sp),y
	jmp     L059D
L04F8:	lda     _ActiveFrame
	ldx     _ActiveFrame+1
	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     #<(_Frames)
	sta     ptr1
	lda     tmp1
	adc     #>(_Frames)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	sta     ptr1
	stx     ptr1+1
	ldy     #$0C
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     callax
	ldy     #$01
	sta     (sp),y
	lda     (sp),y
	jeq     L059C
	cmp     #$0D
	jeq     L0531
	cmp     #$20
	jeq     L0527
	cmp     #$31
	beq     L0503
	cmp     #$32
	beq     L0503
	cmp     #$33
	beq     L0503
	cmp     #$34
	beq     L0503
	cmp     #$35
	beq     L0503
	cmp     #$3F
	beq     L0511
	cmp     #$43
	jeq     L059C
	cmp     #$48
	beq     L051D
	cmp     #$51
	jeq     L054B
	cmp     #$52
	jeq     L0547
	cmp     #$53
	jeq     L0541
	cmp     #$55
	beq     L0516
	cmp     #$85
	beq     L0511
	cmp     #$86
	beq     L0516
	cmp     #$88
	beq     L0527
	cmp     #$8A
	beq     L051D
	cmp     #$8C
	beq     L0531
	jmp     L04FA
L0503:	jsr     decsp3
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	sec
	sbc     #$31
	bcs     L050E
	dex
L050E:	ldy     #$01
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$00
	tay
	sta     (sp),y
	jsr     _ActivateFrame
	jmp     L04FA
L0511:	jsr     _HelpHandler
	jmp     L04FA
L0516:	jsr     _SetRTSBreak
	lda     #$01
	ldy     #$00
	sta     (sp),y
	jmp     L059D
L051D:	lda     _brk_pc
	ldx     _brk_pc+1
	cpx     _AsmAddr+1
	bne     L059E
	cmp     _AsmAddr
	beq     L04FA
L059E:	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     pushax
	jsr     _DbgSetTmpBreak
	lda     #$01
	ldy     #$00
	sta     (sp),y
	jmp     L059D
L0527:	tya
	jsr     pusha
	jsr     _SingleStep
	jsr     _DbgTmpBreaksOk
	tax
	beq     L04FA
	lda     #$01
	ldy     #$00
	sta     (sp),y
	jmp     L059D
L0531:	lda     #$00
	jsr     pusha
	jsr     _SingleStep
	jsr     _DbgTmpBreaksOk
	tax
	beq     L04FA
	lda     #$01
	ldy     #$00
	sta     (sp),y
	jmp     L059D
L059C:	tya
	dey
	sta     (sp),y
	jmp     L059D
L0541:	lda     _brk_pc
	ldx     _brk_pc+1
	jsr     _DbgDisAsmLen
	clc
	adc     _brk_pc
	sta     _brk_pc
	txa
	adc     _brk_pc+1
	sta     _brk_pc+1
	jsr     _InitAsm
	jmp     L04FA
L0547:	lda     _ActiveFrame
	jsr     pusha
	jsr     _Redraw
	jmp     L04FA
L054B:	jsr     _clrscr
	ldx     #$00
	lda     #$01
	jsr     _exit
L04FA:	ldy     #$00
L059D:	lda     (sp),y
	jeq     L04F8
	jmp     incsp2

.endproc

