;
; File generated by co65 v 2.14.0 using model `cc65-module'
;
.fopt		compiler,"co65 v 2.14.0"
.case		on
.debuginfo	off
.export		_lynx_stdjoy_joy

;
; CODE SEGMENT
;
.segment	"CODE"
_lynx_stdjoy_joy:
	.byte	$6A
	.byte	$6F
	.byte	$79
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$80
	.byte	$40
	.byte	$20
	.byte	$10
	.byte	$01
	.byte	$02
	.byte	$00
	.byte	$00
	.word	_lynx_stdjoy_joy+24
	.word	_lynx_stdjoy_joy+28
	.word	_lynx_stdjoy_joy+29
	.word	_lynx_stdjoy_joy+34
	.byte	$00
	.byte	$00
	.byte	$A9
	.byte	$00
	.byte	$A2
	.byte	$00
	.byte	$60
	.byte	$A9
	.byte	$01
	.byte	$A2
	.byte	$00
	.byte	$60
	.byte	$A2
	.byte	$00
	.byte	$AD
	.byte	$B0
	.byte	$FC
	.byte	$29
	.byte	$F3
	.byte	$60

;
; DATA SEGMENT
;
.segment	"DATA"
DATA:

;
; BSS SEGMENT
;
.segment	"BSS"
BSS:
	.res	0

;
; ZEROPAGE SEGMENT
;
.import	__ZP_START__		; Linker generated symbol
ZEROPAGE = __ZP_START__

.end
