;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_malloc
	.import		_free
	.import		_read
	.import		_open
	.import		_close
	.import		__oserror
	.import		__directerrno
	.export		_opendir
	.import		__cwd

; ---------------------------------------------------------------
; __near__ struct DIR* __near__ __fastcall__ opendir (register __near__ const unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_opendir: near

.segment	"CODE"

	jsr     pushax
	ldy     #$00
	ldx     #$04
	jsr     regswap2
	lda     regbank+2
	ldx     regbank+3
	jsr     pushax
	ldx     #$02
	lda     #$05
	jsr     _malloc
	sta     regbank+2
	stx     regbank+2+1
	cpx     #$00
	bne     L000D
	cmp     #$00
	bne     L000D
	lda     #$02
	jsr     __directerrno
	jmp     L0042
L000D:	ldy     #$00
	lda     (regbank+4),y
	cmp     #$2E
	bne     L0017
	lda     #<(__cwd)
	sta     regbank+4
	lda     #>(__cwd)
	sta     regbank+4+1
L0017:	lda     regbank+2
	ldx     regbank+2+1
	jsr     pushax
	jsr     decsp4
	lda     regbank+4
	ldy     #$02
	sta     (sp),y
	iny
	lda     regbank+4+1
	sta     (sp),y
	lda     #$01
	ldy     #$00
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	ldy     #$04
	jsr     _open
	ldy     #$00
	jsr     staxspidx
	cpx     #$FF
	bne     L0041
	cmp     #$FF
	beq     L001B
L0041:	jsr     decsp4
	iny
	lda     (regbank+2),y
	tax
	dey
	lda     (regbank+2),y
	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     regbank+2
	ldx     regbank+2+1
	clc
	adc     #$05
	bcc     L0026
	inx
L0026:	ldy     #$00
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldx     #$02
	lda     #$00
	jsr     _read
	cpx     #$02
	bne     L0022
	cmp     #$00
	bne     L0022
	ldy     #$28
	lda     (regbank+2),y
	ldy     #$02
	sta     (regbank+2),y
	ldy     #$29
	lda     (regbank+2),y
	ldy     #$03
	sta     (regbank+2),y
	lda     #$01
	iny
	sta     (regbank+2),y
	lda     regbank+2
	ldx     regbank+2+1
	jmp     L000C
L0022:	lda     __oserror
	bne     L0036
	lda     #$07
	jsr     __directerrno
L0036:	ldy     #$01
	lda     (regbank+2),y
	tax
	dey
	lda     (regbank+2),y
	jsr     _close
L001B:	lda     regbank+2
	ldx     regbank+2+1
	jsr     _free
L0042:	ldx     #$00
	txa
L000C:	pha
	ldy     #$00
L003F:	lda     (sp),y
	sta     regbank+2,y
	iny
	cpy     #$04
	bne     L003F
	pla
	jmp     incsp4

.endproc

