;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_stdout
	.export		_puts
	.import		_strlen
	.import		_write

; ---------------------------------------------------------------
; int __near__ __fastcall__ puts (__near__ const unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_puts: near

.segment	"DATA"

L0003:
	.byte	$0A

.segment	"CODE"

	jsr     pushax
	jsr     decsp4
	lda     _stdout
	sta     ptr1
	lda     _stdout+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	ldy     #$02
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _strlen
	jsr     _write
	cpx     #$80
	bcs     L0013
	jsr     decsp4
	lda     _stdout
	sta     ptr1
	lda     _stdout+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	ldy     #$02
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #<(L0003)
	ldy     #$00
	sta     (sp),y
	iny
	lda     #>(L0003)
	sta     (sp),y
	ldx     #$00
	tya
	jsr     _write
	cpx     #$80
	bcs     L0013
	ldx     #$00
	txa
	jmp     incsp2
L0013:	lda     _stdout
	sta     ptr1
	lda     _stdout+1
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	ora     #$04
	sta     (ptr1),y
	ldx     #$FF
	txa
	jmp     incsp2

.endproc

